### ISSUE TITLE
Cursor jumps to the end of input while editing the value in the middle

### ISSUE THREAD

**Issue by prokopsimek** [swarmpit/swarmpit#126]
Cursor jumps to the end of input while editing the value in the middle.

**Comment by nohaapav** [comment]
https://github.com/callemall/material-ui/issues/4430

Material UI bug. We'll check for workaround

**Comment by lumir-mrkva** [comment]
related to #129

**Comment by nohaapav** [comment]
Will be fixed by https://github.com/swarmpit/swarmpit/issues/159
