### ISSUE TITLE
Running swarmpit on a arm swarm

### ISSUE THREAD

**Issue by cbailly42** [swarmpit/swarmpit#130]

**Comment by a1exanderjung** [comment]
Would love to see this feature so as to deploy to a Raspberry Pi swarm/cluster.

**Comment by nohaapav** [comment]
First we need to optimize swarmpit in matter of memory usage. Also some JVM customization needs to be done.

@lumir-mrkva will take a look :)

**Comment by chabad360** [comment]
Any updates on this?

**Comment by nohaapav** [comment]
@chabad360 We're now pretty busy with rewriting swarmpit to fully responsive ui .. Then we're going to optimize jvm to run swarmpit on arm ..

**Comment by chabad360** [comment]
Any eta?

**Comment by nohaapav** [comment]
@chabad360 Will discuss with @lumir-mrkva on Monday

**Comment by nohaapav** [comment]
@rthill Hi we did quite a huge refactoring to new UI in recent months so we had no time to focus on this one.

Anyway @lumir-mrkva you're speaking with someone at dockercon regarding arm release. How much effort we need to put in to finalize this one ?

**Comment by kuerious** [comment]
^-- So for this, we just "pull" it locally and run the original script?

**Comment by kenits** [comment]
It work with docker manifest. When you on arm64v8 and pull tag v2.1.0 docker will pull v2.1.0-linux-arm64v8 image. And if you on amd64 similarly. Tag v2.1.0 is not real it create by manifest as reference to other images.
In my case i change original agent image in swarmpit script on this, and every machine pull right image.
Like:
swarmpit/agent:2.1 to kenits/swarmpit_agent:v2.1.0

Sorry for my English, i know it very bad.

**Comment by bd8392** [comment]
Hi :-) I love Swarmpi! It's really great development! I also wanted to use it on a pi, but it sadly doesn't work :-( could you say when it will become available in the future? :-) kind regards

**Comment by lumir-mrkva** [comment]
@bd8392 in few minutes :)

**Comment by lumir-mrkva** [comment]
- [x] multiarch agent
- [x] multiarch swarmpit
- [ ] multiarch installer
- [x] stack tested on armv7
- [ ] stack tested on arm64
- [x] agent supporting armv6
- [ ] whole stack support for armv6
- [ ] one compose file supports every architecture

**Comment by bd8392** [comment]
@lumir-mrkva Amazing! That was Fast! =) Great thanks =) I will get out mi pi and test it =)

**Comment by bd8392** [comment]
Sadly I didn't get it to work =( Maybe I'm getting something wrong? I tried two methods:

First:

docker run -it --rm \
  --name swarmpit-installer \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  swarmpit/install:edge

Second with this compose file:

https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml

The Compose doesn't fire up the services, and the installer throws: 
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size

Tested on Hypriot-OS

**Comment by nohaapav** [comment]
@bd8392 there is special compose .. See ARM installation section: https://github.com/swarmpit/swarmpit#installation-on-arm-based-cluster

**Comment by bd8392** [comment]
Oh Yes this works! =) Thanks =) Think we can close the issue ;-)

**Comment by bd8392** [comment]
ok celebrated too early...I get the Interface for the account-creation now, but the admin account doesn't get created and the ui frezes...

**Comment by nohaapav** [comment]
@bd8392 It's probably related to https://github.com/swarmpit/swarmpit/issues/425
The current password hashing [algorithm](https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/config.clj#L12) is a bit heavy for ARM. It should work though, you just have to wait bit longer (up to 50 seconds i guess)

**Comment by bd8392** [comment]
waited about ten minutes now to see the dashboard loading, but got almost immidetely kicked back to the login =(

**Comment by lumir-mrkva** [comment]
@bd8392 yeah, login can take MINUTES currently, just be sure you put in right password :) and get cup of coffee. this will be fixed in future with #425

**Comment by lumir-mrkva** [comment]
core fixed, remaining minor issues tracked in #431 and #432

**Comment by midu16** [comment]
Hello,

Is there any resolution regarding the compatibility of swarmpit on armv6 ? I didnt manage to make  it work on  armv6.

Thank you,
M
