### ISSUE TITLE
Gitlab Registry for Custom Registry

### ISSUE THREAD

**Issue by davidjameshowell** [swarmpit/swarmpit#131]
Error Message
`Registry creation failed. Reason: Registry credentials does not match any known registry`

I am attempting to add a custom registry provided by Gitlab. I have attempted `https://registry.gitlab.com` and `https://registry.gitlab.com/` and `https://registry.gitlab.com/user.name` but do not understand the specific error message below. I attempted to dive in to the code but am not familiar with Clojure to understand.

I recreated this in a PWD environment to rule out an environmental issue on my end.

**Comment by nohaapav** [comment]
@davidjameshowell Hi David, hope that this thread answer your question.

https://github.com/swarmpit/swarmpit/issues/114

As we're using gitlab as well we will probably add support for gitlab registry auth flow as well soon.

**Comment by davidjameshowell** [comment]
Thank you @nohaapav! I should have searched the issue more thoroughly next time!

**Comment by nohaapav** [comment]
Issue to support custom token with registry added in 1.3 
https://github.com/swarmpit/swarmpit/issues/157
