### ISSUE TITLE
Swarmpit cannot add registry over HTTPS protected by LetsEncrypt SSL

### ISSUE THREAD

**Issue by Vratislav** [swarmpit/swarmpit#132]
# Bug

When adding registry protected by LetsEncrypt SSL certificate, the Swarmpit errors out.

<img width="963" alt="screenshot 2017-09-17 14 48 25" src="https://user-images.githubusercontent.com/346066/30520951-79441122-9bb7-11e7-9877-6a73fdddc549.png">

On the registry server, the following message is displayed in the console output:

```
2017/09/17 12:48:17 [INFO][] acme: Obtaining bundled SAN certificate
2017/09/17 12:48:18 http: TLS handshake error from 89.177.30.171:61515: map[:acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: DNS name was empty]
```

This seems to be a TLS issue.

# Expected behaviour

I should be able to add the registry

# Replication

To replicate, start a registry with the following command:

```
docker run -it -p 443:5000 --name registry \
  -v registry_configuration:/etc/docker/registry/ \
  -v registry:/var/lib/registry \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
  -e REGISTRY_HTTP_HOST=https://validhost.example.com \
  -e REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/etc/docker/registry/letsencrypt.json \
  -e REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=user@example.com \
  registry:2
```

then try to add it via the swarmpit UI.

*Isolation of the issue*

Fire up the repl and invoke 

```clojure
(swarmpit.registry.client/info {:url "https://validhost.example.com"})
```
The call will fail with:
```
ExceptionInfo Registry failure: Received fatal alert: internal_error  clojure.core/ex-info (core.clj:4725)
```

The same error as before will be logged on the docker registry server

# Investigation

This seems to be related to poor TLS 1.2 support in `http-kit`. See https://github.com/http-kit/http-kit/issues/334 

I've tried workaround described in https://github.com/http-kit/http-kit/issues/228 but it seems to fail (I am not a Clojure programmer so maybe I did not implement it properly).

**Comment by nohaapav** [comment]
This is special case we need to dig a bit into. If ACME certificates are used in proxy in front of registry (nginx, traefik) everything works as expected.

**Comment by nohaapav** [comment]
all clients now using clj-http instead of httpkip .. Lets encrypt certificate should not be an issue anymore
Related to : https://github.com/swarmpit/swarmpit/issues/138
