### ISSUE TITLE
service log stops tailing after service update

### ISSUE THREAD

**Issue by lumir-mrkva** [swarmpit/swarmpit#135]
stops when only task in service is deleted and created new one

**Comment by atmosx** [comment]
I came here to report the same issue. This is a very old, known swarm bug but there is a bypass that works for me from [reported on moby's issue](https://github.com/moby/moby/issues/33183):

```
docker service logs -f --since 10m tv_web
```

If smarmpit could implement this command as default and possibly offer a box or drop-down menu for log fetch, would be great!

**Comment by nohaapav** [comment]
@atmosx Hi atmosx .. we're going to improve logs experience in this release so yep, it's going to happen ;)

**Comment by steffen201706** [comment]
docker service  logs is completly death - with or without any switch

`
~$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

`

**Comment by nohaapav** [comment]
@steffen201706 Well if `docker service logs` is dead you should raise the issue in docker project :)

**Comment by nohaapav** [comment]
@atmosx Interesting. Thanks for pointing that out. We're tailing just last 2000 lines by default. See

```
(defn service-logs
  [id]
  (-> (execute {:method  :GET
                :api     (str "/services/" id "/logs")
                :options {:query-params {:details    true
                                         :stdout     true
                                         :stderr     true
                                         :timestamps true
                                         :tail       2000}}})
      :body))
```
I have tried to fetch log from one service with intensive logging by tailing last 2000. See:
```
(-> (execute {:method  :GET
              :api     (str "/services/" "92e4dkxonknguvg9tp4v5il9s" "/logs")
              :options {:query-params {:details    true
                                       :stdout     true
                                       :stderr     true
                                       :timestamps false
                                       :tail       2000}}})
    :body)
Execution error (ExceptionInfo) at swarmpit.http/execute-in-scope (http.clj:83).
Docker error: Request timeout
```
Then i did the same with your approach for last 24 hours:
```
(count (clojure.string/split-lines (-> (execute {:method  :GET
                                                 :api     (str "/services/" "92e4dkxonknguvg9tp4v5il9s" "/logs")
                                                 :options {:query-params {:details    true
                                                                          :stdout     true
                                                                          :stderr     true
                                                                          :timestamps true
                                                                          :since      1554832440}}})
                                       :body)))
=> 25889
```
How the hell is this even possible .. 25000 lines in 2 sec vs 2000 with timeout ..
