### ISSUE TITLE
can't start swarmpit with the shown commands

### ISSUE THREAD

**Issue by derPuntigamer** [swarmpit/swarmpit#137]
I've tried to run swarmpit on my local machine with the commands presented on the website. I've created a Docker swarm locally.

I've deployed my stack on my local swarm with:

```bash 
➜ docker stack deploy -c docker-compose.yml swarmpit

➜ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                          NAMES
95fdb2d55193        swarmpit/swarmpit:1.1   "java -jar swarmpi..."   8 minutes ago       Up 8 minutes        8080/tcp                       swarmpit_app.1.hur7cnlh36w657c37qt7oytt8
0cf0da64c22c        klaemo/couchdb:2.0.0    "tini -- /docker-e..."   9 minutes ago       Up 8 minutes        4369/tcp, 5984/tcp, 9100/tcp   swarmpit_db.1.yd1suiqaw7y1eeqpkk510q3xo
```

still, the localhost:888 hangs. Container logs:
**swarmpit:**
```
➜ docker container logs -f 95fdb2d55193
Swarmpit is starting...
16:24:10.126 [main] INFO  swarmpit.server - Server running on port 8080
16:24:10.242 INFO  [org.quartz.core.QuartzScheduler] (main) Quartz Scheduler v.2.2.1 created.
16:24:10.245 INFO  [org.quartz.core.QuartzScheduler] (main) Scheduler meta-data: Quartz Scheduler (v2.2.1) 'SimpleQuartzScheduler:-1011881444' with instanceId 'SIMPLE_NON_CLUSTERED:-1011881444'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

16:24:10.246 INFO  [org.quartz.core.QuartzScheduler] (main) Scheduler SimpleQuartzScheduler:-1011881444_$_SIMPLE_NON_CLUSTERED:-1011881444 started.
16:24:10.246 INFO  [org.projectodd.wunderboss.scheduling.Scheduling] (main) Quartz started

```
**db:** https://pastebin.com/Yur4VeYX

I'm very eager to try out swarmpit, please help me (and the future users) to get started!

**Comment by derPuntigamer** [comment]
the issue may be solved with #5 (if it will be implemented)

**Comment by nohaapav** [comment]
Hi @derPuntigamer, could you please provide more info. Which release are u using, os etc .. 
Sometimes swarmpit hangs due to waiting for DB to be initialized in case of new installation. This problem is known and we're currently working on it [issue](https://github.com/swarmpit/swarmpit/issues/96)

**Comment by lumir-mrkva** [comment]
@derPuntigamer everything looks fine to me, are you sure that your services are published on localhost? try to use http://0.0.0.0:888. if you are using some vm to run docker, try it's ip address.

if that won't help, please provide more information about your setup (docker version, docker node inspect, docker info, your os...).

**Comment by derPuntigamer** [comment]
http://0.0.0.0:888 did it, thank you! Silly mistake...

**Comment by mpazhani** [comment]
How to access URL from remote machines ?
