### ISSUE TITLE
cannot set an env variable with values that contain an equal sign

### ISSUE THREAD

**Issue by fmobus** [swarmpit/swarmpit#156]
As described in title, if I try to set an environment variable with a value that contains an equal sign, it appears that swarmpit splits it and drops whatever is after that character.

Steps to reproduce:
1. create a service with any image
2. add an environment variable with name `MYVAR`
3. set `MYVAR` value to be `firstpart=second=third`
4. save the service

What happens:
- upon viewing the service, `MYVAR` with value `firstpart` 

What should happen:
- upon viewing the service `MYVAR` should have value `firstpart=second=third`

**Comment by nohaapav** [comment]
Fixed with https://github.com/swarmpit/swarmpit/commit/e1f4468aa1a5eeff92af53f5227cd6a1b375ebe9
