### ISSUE TITLE
weird login screen on Firefox

### ISSUE THREAD

**Issue by morph027** [swarmpit/swarmpit#160]
Using Chrome, everything looks nice, but using Firefox i got strange red borders around login input fields:

https://screenshots.firefox.com/nZ57I3PzfE4s7WzR/swarmpit.swarm

**Comment by nohaapav** [comment]
These field are using formsy validation. Probably just some css issue we need to fix.

**Comment by nohaapav** [comment]
Fixed by adding:

`input:invalid {
    box-shadow: none;
}`

Lets fetch latest version once deployed

**Comment by morph027** [comment]
Well, that was fast ;)

**Comment by nohaapav** [comment]
@morph027 ;) small fixes are done within 24 hours usually .. Otherwise free pizza !!!
