### ISSUE TITLE
Secret with Custom File Name is being overridden upon updating a Service via SwarmPit

### ISSUE THREAD

**Issue by mpsmith** [swarmpit/swarmpit#166]
Steps to reproduce:
1. Create a service with any image, set replicas to 1.
2. Create a secret `echo myval | docker secret create mysecret -`
3. Add the secret to the service, with a custom file name: `docker service update --secret-add source=mysecret,target=/custompath/mysecret`
4. In Swarmpit, choose the service, and change value for replicas to 0, then Save the service

What happens:
- upon inspecting the service with `docker service inspect ...`, the custom secret filename (.Spec.TaskTemplate.Secrets.File.Name), has been overwritten with the value of the secret name (.Spec.TaskTemplate.Secrets.SecretName).   

Compare .Spec and .PreviousSpec to see more clearly.  i.e. - 
```
                        {
                            "File": {
                                "Name": "/custompath/mysecret",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 292
                            },
                            "SecretID": "xxx",
                            "SecretName": "yyy"
                        }
```
vs 
```
"Secrets": [
                        {
                            "File": {
                                "Name": "yyy",      # <---- whoops? should stayed /custompath/mysecret
                                "UID": "0",
                                "GID": "0",
                                "Mode": 292
                            },
                            "SecretID": "xxx",
                            "SecretName": "yyy"
                        }
                    ]
```

What should happen:
- upon viewing the service with `docker service inspect...`, the custom secret filename should have been preserved.

**Comment by nohaapav** [comment]
@mpsmith Thanks Matthew for reporting this bug. Should be fixed. Please fetch latest version.

**Comment by mpsmith** [comment]
Tried it out.  Works great!   Thanks for the quick turn-around!
