### ISSUE TITLE
Updating a service does not preserve Arguments

### ISSUE THREAD

**Issue by mpsmith** [swarmpit/swarmpit#169]
Steps to reproduce:
1. Create a service with an image, passing arguments  i.e. -  `docker service create --replicas 1 --name pinger alpine ping docker.com`
2. In Swarmpit, update the service, set the replicas to 2, and Save the service

What happens:
- service fails to restart because arguments are no longer being passed  (compare .Spec and .PreviousSpec to see clearly)

```
          ...
          "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "alpine:latest@sha256:b40e202395eaec699f2d0c5e01e6d6cb8e6b57d77c0e0221600cf0b5940cf3ab",
                    "Args": [
                        "ping",
                        "docker.com"
                    ],
                    "DNSConfig": {},
                    ...
```
vs
```
            ...
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "alpine:latest",
                    "StopGracePeriod": 10000000000,       //// missing 'Args' Node+children
                    "DNSConfig": {},
                     ...
```

What should happen:
- arguments for the service ( .Spec.TaskTemplate.ContainerSpec.Args) should be preserved

**Comment by nohaapav** [comment]
This is mainly because swarmpit does not support arguments yet. Will add support as well ;)

**Comment by nohaapav** [comment]
@mpsmith Hey Matthew, should be ok now. Please check latest version.

This finding was actually more than just argument issue. 
There was a premise in the beginning that services should be created only via swarmpit. If this is the case service data should be preserved and working well during update. But if service is created via cli with unknown data for swarmpit(e.g. arguments) these were cut off during update.

Thanks to your discovery i've added merge [function](https://github.com/swarmpit/swarmpit/commit/308b61b0793de60b7b3512a2136eaa4da8e1e915) which basically take original service(before update) and apply update delta. This should prevent data loss if service is created within cli or any other tool with service data not supported in swarmpit yet.

**Comment by mpsmith** [comment]
@nohaapav Thanks!  I like your overall approach of applying a delta to the existing state.  That seems like it should cover other things that might pop-up.
