### ISSUE TITLE
Ups something goes wrong

### ISSUE THREAD

**Issue by sanchobouillant** [swarmpit/swarmpit#170]
Hi,

I installed swarmpit with:

git clone https://github.com/swarmpit/swarmpit
docker stack deploy -c swarmpit/docker-compose.yml swarmpit

I connect with admin/admin then i have a 500 error on /services.

Where can i find some log to see what happened ?

**Comment by nohaapav** [comment]
@sanchobouillant Hi Julien, just open browser console. You should see what is going wrong.

<img width="1609" alt="screen shot 2017-11-05 at 1 43 48 pm" src="https://user-images.githubusercontent.com/4179104/32414852-92d6a340-c22f-11e7-9e08-7eaa7ca192d2.png">

**Comment by sanchobouillant** [comment]
{"cause":null,"via":[{"type":"java.lang.NullPointerException","message":null}],"trace":[]}

It help ?

**Comment by nohaapav** [comment]
Could you provide more info:

Like which endpoint returns such error? req/resp
What version of docker are u using ?
What os are u using?

**Comment by sanchobouillant** [comment]
Docker version 17.09.0-ce, build afdb6d4
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3

/#/login is working
/#/services error 500

I have a private registry working in se the same server.

Do you need more informations ?

**Comment by nohaapav** [comment]
@sanchobouillant Could you try one more thing:

After login go to browser local storage, copy paste token value -> it should be some bearer type e.g. `Bearer eyJhbGciOiJ`

Then call backend services endpoint `/services` with `Authorization` header with given token value and copy paste result here please.

**Comment by sanchobouillant** [comment]
Same error with postman

![image](https://user-images.githubusercontent.com/5731199/32465145-bfbba14e-c342-11e7-9aad-dfb30da2114a.png)

**Comment by nohaapav** [comment]
@sanchobouillant What if you try to reach some service data by id/name ? E.g. 

`/services/{id}`

**Comment by nohaapav** [comment]
As this seems to be dead thread closing .. Feel free to reopen & continue discussion
