### ISSUE TITLE
How to add new nodes?

### ISSUE THREAD

**Issue by markuman** [swarmpit/swarmpit#171]
E.g. I've got a new AWS EC2 instance and want to run there a new node?

**Comment by nohaapav** [comment]
@markuman Hi, not possible via swarmpit currently. You need to use swarm cli to do that. For now we're focusing on resource management, not infrastructure. But in future we're going to support adding nodes as well.

Anyway that is not priority right now :)

**Comment by markuman** [comment]
And how to do it with swarm cli?

**Comment by nohaapav** [comment]
Please check official docker swarm documentation:

https://docs.docker.com/engine/swarm/join-nodes/

**Comment by markuman** [comment]
ok, got it. thx
