### ISSUE TITLE
Cannot add gitlab registry

### ISSUE THREAD

**Issue by markuman** [swarmpit/swarmpit#172]
When I use `https://registry.gitlab.com` and add my login data, I got the error `Registry creation failed. Reason: Registry credentials does not match any known registry`
Thats all. Can someone reproduce this? Or is there a more detailed error message?

**Comment by markuman** [comment]
Hm ok, browser console says `Failed to load resource: the server responded with a status of 400 (Bad Request)` Any ideas?

**Comment by nohaapav** [comment]
@markuman This is because swarmpit currently support only basic auth based registry. Gitlab is using custom token. There is already issue in this release to add custom token support:

https://github.com/swarmpit/swarmpit/issues/157
