### ISSUE TITLE
Read only user

### ISSUE THREAD

**Issue by kassanmoor** [swarmpit/swarmpit#174]
Would be niace have a third role read only user, than can only see stuff (logs, envs )without mess anything

**Comment by nohaapav** [comment]
@kassanmoor Hi, this will be ready once we finish resource role management.

Check related issues:

https://github.com/swarmpit/swarmpit/issues/125
https://github.com/swarmpit/swarmpit/issues/94

**Comment by NeilInnes** [comment]
I have created a fork that allows "view only"/"read only" users to be created: https://github.com/NeilInnes/swarmpit_view_only
