### ISSUE TITLE
Serve TLS (aka the obligatory letsencrypt support issue)

### ISSUE THREAD

**Issue by dalu** [swarmpit/swarmpit#175]
swarmpit is reachable on port 888 via http only
swarmpit should utilize https
the cheapest and most simple way (with a valid cert) is using letsencrypt

for this swarmpit should have 2 parameters added to its cli/docker configuration

`ACME_EMAIL` the email address associated with the domain
`ACME_DOMAIN` the domain where this swarmpit is hosted e.g. https://mydomain.tld:888/ would be mydomain.tld

If you have questions please ask

**Comment by dalu** [comment]
Ok, but if that nginx or traefik host is remote and the transport is unencrypted this leads to "NSA reading your credentials".

Docker swarm exposes services on the public IP addrs of all nodes.

Now you have a traefik running with acme support on port 80 which is configured to read from master node port 888,

master 10.0.0.1
worker1 10.0.0.2

swarmpit running on master
traefik running on master and worker1 but worker1 is used to access swarmpit
the request goes from worker1 <-via-http-> master.
all communication between worker1 and master is unencrypted, because swarmpit does not utilize transport layer security.

I don't mean to be a smartass if you know what I mean, however it is good practice for services to communicate via some kind of encryption even if on the same host.
separation of concerns is all well and nice but there are real world needs that need to be considered.

I will close this, but for me this also mean I won't use swarmpit because it doesn't provide the security necessary I'm looking for.

Cheers.

**Comment by lumir-mrkva** [comment]
@dalu its surely good idea to support https communication for transport, but i don't see necessity of letsencrypt integration - swarmpits certificate would be configured by using secret or env variable

**Comment by lumir-mrkva** [comment]
@dalu btw. if you are concerned about communication between your cluster nodes, you can use overlay network with encrypted communication, see https://docs.docker.com/engine/userguide/networking/overlay-security-model/
