### ISSUE TITLE
Disable authentication

### ISSUE THREAD

**Issue by markvr** [swarmpit/swarmpit#176]
Firstly this looks awesome and is exactly what I've been looking for!

I was wondering if it's possible to disable the authentication entirely?  Then I could proxy it behind Apache, which we have plugged into our onsite single sign on system.  This would mean my users could login using their domain credentials, rather than needing individual accounts in Swarmpit itself.

**Comment by nohaapav** [comment]
@markvr Hi, yes there is plan to implement SSO in future (i guess beginning of 2018) :) Unfortunately it's not possible to disable auth at the moment as we're using JWT token to handle BE auth.

**Comment by nohaapav** [comment]
Closing in favour of https://github.com/swarmpit/swarmpit/issues/181
