### ISSUE TITLE
Unable to run swarmpit on my docker host

### ISSUE THREAD

**Issue by rsoika** [swarmpit/swarmpit#178]
I try to install and run swarmpit in my linux docker host.
I installed it from git hub

`git clone https://github.com/swarmpit/swarmpit -b 1.2`

started the swarm mode

`docker swarm init`

and run the docker command:

```
$ docker stack deploy -c swarmpit/docker-compose.yml swarmpit
Creating network swarmpit_net
Creating service swarmpit_db
Creating service swarmpit_app
```

But I got no UI on localhost:888 
I also tried to change the port to 8080 with no result. 
How can I see what is going wrong in my setup?

I am running docker version:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I fear that I am missing something in the install guide.

**Comment by nohaapav** [comment]
@rsoika Hi Ralph, setup is most probably ok. You can always check swarmpit_app log if server is running .. Try to use http://0.0.0.0:888. if you are using some vm to run docker, try it's ip address.

**Comment by rsoika** [comment]
Thanks for your feedback! 
Yes it is working with  http://0.0.0.0:888.
Why is http://localhost:888 not working?

**Comment by nohaapav** [comment]
@rsoika Check this [feed](https://github.com/moby/moby/issues/2509#issuecomment-27568447)
