### ISSUE TITLE
Configs in the "Data"

### ISSUE THREAD

**Issue by develar** [swarmpit/swarmpit#179]
I am impressed. Still not clear for me why you decided to implement your own solution instead of contributing to Portainer, but I like swarmpit interface :)

Is it possible to add `Configs` to the `Data` (as we have already `Secrets`)?

Docs: https://docs.docker.com/engine/swarm/configs/ (in general, the same as secrets).

**Comment by nohaapav** [comment]
@develar Thank you. Actually we're searching for some solution few months ago (swarm mode was introduced into docker) and we didn't like portainer interface (user interaction, validation), also portainer was missing lot of features that it has now .. Apart from that we had our vision how to manage swarm cluster so we started writing something on our own. For last 5 months we're trying to cover most of swarm API and now we're introducing some fancy features we would love to have in management platform (monitoring/event handling and many more) :) 

We're also operating over huge Fintech cluster so we need to be as flexible as possible to bring new features on customer demand ;)

I've created new issue in current release for config data [see](https://github.com/swarmpit/swarmpit/issues/180)
