### ISSUE TITLE
Problem with longer logs

### ISSUE THREAD

**Issue by martinfibiger** [swarmpit/swarmpit#187]
After using swarmpit for longer time, logs are getting long and are not shown correctly. Way to reproduce: choose long running microservice, press button [log]. Log content is shown but the end is missing. Sometimes you get further log after a while sometimes not. Sometimes chrome crashes.

**Comment by nohaapav** [comment]
This happens due to huge json-file that even docker was unable to fetch .. We need to be able to setup logging properties e.g. (rolling policy for json-file) and pre-fill some default value to prevent this.

Closing in favour of https://github.com/swarmpit/swarmpit/issues/188
