### ISSUE TITLE
compose -> swarmpit should depends on db .. otherwise install script may fail + use swarmpit as network name .. 

### ISSUE THREAD

**Issue by nohaapav** [swarmpit/swarmpit#19]

**Comment by lumir-mrkva** [comment]
@nohaapav will fix dependency, install script didn't fail, but swarmpit_app was restarting until db was ready. stack name is atomatically prepended in all objects created from stack file, including a network.

**Comment by nohaapav** [comment]
ahhh .. you're right .. so closing the issue
