### ISSUE TITLE
Missing name validation error text

### ISSUE THREAD

**Issue by prokopsimek** [swarmpit/swarmpit#200]
**Description**

Missing name validation error text while creating new service.

**Steps to reproduce the issue:**
1. Open "services/new" form
2. set service name e.g. "app manager"
3. set other attributes
4. Save new service

**What happens:**
Error is thrown and visible on the bottom of the page "Service creation failed. Reason:"

**What should happen:**
Display "Name invalid - do not use spaces" error

**Comment by nohaapav** [comment]
Not swarmpit issue .. Closing ..
