### ISSUE TITLE
Container & Host Port wrong title

### ISSUE THREAD

**Issue by Matts** [swarmpit/swarmpit#205]
**Description**

It seems that the "Container port" and  "Host port" seem to be the wrong way around. I was playing around with the letsencrypt reverse proxy companion (together with nginx proxy) and had to create [this issue](https://github.com/jwilder/nginx-proxy/issues/1056) because I thought it was their fault, but after playing around I set the "Container Port" to the port I was expecting in the proxy and it worked.

**Steps to reproduce the issue:**
1. Create a new service

**What happens:**
It shows "Container Port" and "Host Post" while it seems to have the reverse behaviour

**Additional information (e.g. docker version, cluster setup,...):**
swarmpit 1.4-473144b
I

**Comment by nohaapav** [comment]
Work completely fine. Host port is exposed public port(node port). Container port is port exposed within container. It might look reversed if you compare with docker cli (exposed->container) but still working ok.

One note regarding your proxy issue. It is much better to put proxy container within same overlay network as swarmpit so you can reach swarmpit directly on port 8080 without port exposing.
