### ISSUE TITLE
Enable autoredeploy for existing service

### ISSUE THREAD

**Issue by sarkistlt** [swarmpit/swarmpit#211]
first, thanks for really cool UI, exactly what I was looking for.
Question is, I can see that if I will start new service with swarmpit it will allow me to set autoredeploy, but I can't do that for already running services that I have in my swarm.
any plans to support autoredeploy for existed services?

**Comment by nohaapav** [comment]
@sarkistlt Hi, yes we can enable autoredeploys for existing services already. We had to finalize this issue before enabling https://github.com/swarmpit/swarmpit/issues/197 but now there is no showstopper.

**Comment by sarkistlt** [comment]
I still can't enable it for services that was deployed from docker-compose.yml, or this fix is not in latest image yet?

**Comment by nohaapav** [comment]
not done yet, see [status](https://github.com/swarmpit/swarmpit/projects/8) . Will add support probably during this week ..
