### ISSUE TITLE
redeploy of service keeps deprecated tasks running

### ISSUE THREAD

**Issue by rsoika** [swarmpit/swarmpit#213]
I am not sure if this is a bug or expected behavior. But I have the situation that after redploying taks from the UI I got multiple still running tasks.

**Steps to reproduce the issue:**
1. I deploy from cli a stack containing Wordpress+MySQL
2. swarmpit shows the two services and also two tasks.
3. now I open the mysql service from the swarmpit ui and click on 'redeploy'
4. a new task is started,

**What happens:**
the old (deprecated) mysql task is still running. Why does this happen?

**What should happen:**
I expect that the old mysql task is stopped and removed 

Is this an issue of docker-swarm in general or something in swarmpit? I am really not sure about this strange behavior. So if this is my poor knowledge about docker-swarm, don't be upset. 

Is there a feature planed that I can remove tasks from the UI?

**Comment by nohaapav** [comment]
@rsoika Hi Ralph, we're using task api so there shouldn't be a problem on our side. We also saw similar issue in our clusters so probably some swarm inconsistency. If you set replicas to 0 and back i bet that task will be removed.

**Comment by rsoika** [comment]
Thanks for your answer. Yes I also think so and I will try to figure out how to handle this issue best.
