### ISSUE TITLE
Generating token without expiration date

### ISSUE THREAD

**Issue by BatuhanK** [swarmpit/swarmpit#215]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

We want to use `/services` and `/services/:serviceId` endpoint programatically for generating and manipulating services from our backend, right now we are using token which generated via `/login` endpoint but it has expiration date. Are there any way to generate token without expiration date, if not can we get it in the future or should we implement our logic with current login flow?

And I want to thank @nohaapav @lumir-mrkva for this amazing project, recently docker-cloud announced that they will shutdown their swarm management ui and swarmpit is perfect replacement for that.

**Comment by nohaapav** [comment]
@BatuhanK Hi, we are thinking about some default swarmpit settings page so maybe we can include token expiration as well.

**Comment by nohaapav** [comment]
@BatuhanK We decided to add this functionality in user drop down menu next to change password form. That way you can generate and revoke custom user tokens and set validity based on your needs or leave empty for everlasting. How does that sounds to you ?

**Comment by BatuhanK** [comment]
Sounds perfect! Thanks @nohaapav
