### ISSUE TITLE
Support of volume driver options

### ISSUE THREAD

**Issue by NotSpecial** [swarmpit/swarmpit#216]
I am currently playing around with swarmpit in the docker playground and first of all:
It's looking amazing, this is the kind of UI for docker swarm I was looking for! Thank you for your work :)

Docker allows to specify various [driver options for volumes](https://docs.docker.com/engine/reference/commandline/volume_create/#usage) and unfortunately, I noticed that it is not possible to specify these options in the interface, I can only specify name and driver, nothing else.
Unfortunately, the kind of volumes I am working with can only be created with some specific options passed to the driver.

Would it be possible to support this feature?

**Comment by nohaapav** [comment]
@NotSpecial Hi, yes for sure :) Will add support asap. Please see progress in following future req:

https://github.com/swarmpit/swarmpit/issues/217
