### ISSUE TITLE
UI support for stacks

### ISSUE THREAD

**Issue by rsoika** [swarmpit/swarmpit#218]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

I have the following suggestion: I typically start my services as a stack from the docker swarm CLI like:

`docker stack deploy -c apps/wordpress/docker-compose.yml wordpress-demo`

In this case a mysql service and a wordpress service is started. They are listed in swarmpit as services

'db_wordpress-demo' and 'app_wordpress-demo'

Some of my stacks contains up to 4 differnt services. So the service view in swarmpit becomes very long and is not very clear. Are there any plans to view the result from the command

`docker stack ls`

This would be a much nicer information. 

Also it would be cool if I can update a complete stack with 'deploy'. For now I rerun my cli command. But  I guess that this is not possible because swarmpit does not know the location of the docker-compose.yml file?

Another problem in my eyes is the 'delete' command form the service view in swarmpit. To me it seems that the service is removed from the manager-node view. But it is still running on the worker-node. So I need to manually stop the services on the worker-node. Is there any chance to control a stack completely form the Swarmpit UI in the future: 

- docker stack list
- Stop stack 
- Update stack

**Comment by nohaapav** [comment]
@rsoika Hi Ralph:

Are u using latest build with stack API ? 

Basically `docker stack ls` is stack list:

<img width="1636" alt="screen shot 2018-04-02 at 4 02 53 pm" src="https://user-images.githubusercontent.com/4179104/38199080-9c021588-368f-11e8-9911-cc3630388db9.png">

To see stack resources you can just click on stack e.g.:

<img width="1634" alt="screen shot 2018-04-02 at 4 06 02 pm" src="https://user-images.githubusercontent.com/4179104/38199133-cb085432-368f-11e8-8576-9215b0d76ca6.png">

U can update stack by clicking edit -> change stack and then deploy .. if there is no change just use redeploy. If stack is external -> not created via swarmpit just click edit and copy/paste stackfile and click deploy .. That way stackfile will be linked to existing stack.

Not sure if i understand the delete problem in service view ..

**Comment by rsoika** [comment]
Thanks a lot for your answer. This sounds very promising.I run swarmpit in my docker-swarm productive environment. I tried the latest image form docker hub, but it does not work (only blank page, no java script errors). I switched back to latest stable 1.3.1. 

So I will have to wait until 1.4 comes out and than I will test it. And yes, I am in deed  not absolutely sure if I have some inconsistency on my swarm cluster. Or maybe my docker-compose.yml files are not free of bugs...

Thanks again - you can close this issue.

**Comment by nohaapav** [comment]
@rsoika i see that there were some dependency updates yesterday. That probably caused the issue. Will fix it asap.

**Comment by nohaapav** [comment]
@rsoika Btw latest should be ok now. Please check ;)

**Comment by rsoika** [comment]
@nohaapav Ok the 'latest' image on docker hub runs now perfect.
And the new View 'Stacks' is really a strong improvement and I find it very helpfull.

The feature toTo edit a docker-compose.yml definition is very cool. But in a productive environment my concept is to store all docker-compose files in Git to have a central code repository. I described this also in my imixs-cloud project https://github.com/imixs/imixs-cloud/blob/master/doc/VERSIONCONTROL.md

But for testing a new stack this feature is really great!
