### ISSUE TITLE
AWS Elastic Container Repository support

### ISSUE THREAD

**Issue by mhermosi** [swarmpit/swarmpit#236]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Hi Folks, 

AWS ECR (Elastic Container Registry) has a way to generate a 12 hour password which outputs a docker login command on Unix environment. so basically based on your AWS parameter KEY, SECRET and REGION it generates a dynamic docker login command. This command is necessary for authenticate on AWS private docker registry, so it would be nice to be able to have an integration so I can continue using swarmpit. the Add registry only support basic authentication and Amazon provides a tool called Amazon ECR Docker Credential Helper (https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/) which may be the way of authenticating and adding ECR Registry on swarmpit

Thanks,

-Martin

**Comment by nohaapav** [comment]
@mhermosi Hi Martin, actually registry API does support basic auth with fallback in case that request fails with 401 and header Www-Authenticate is provided in response.

Fallback then use token api and based on auth token call registry api again. See registry token auth: https://docs.docker.com/registry/spec/auth/token/#authorization-server-endpoint-descriptions

This is standardized way of how registry should work.

Could you check if AWS ECR works the same ? I mean Www-Authenticate is returned in case of wrong auth(401) ?

**Comment by mhermosi** [comment]
mmm actually the problem with AWS ECR is not how docker login is performed. is how the dynamic password is obtained. the aws client basically generates a string "docker login -u AWS -p A_very_long_dynamic_password" https://ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com", that is the reason I added the link related with credential helper.. it seems to be a way to use a credential helper for software interaction, they use as an example Jenkins. I am reading more about this.

**Comment by mhermosi** [comment]
How I picture this, is basically storing some AWS necessary information on swarmpit to let the password generation AWS_KEY, AWS_SECRET and AWS_REGION

**Comment by nohaapav** [comment]
@mhermosi I will create some AWS registry instance in order to support this as well.

**Comment by mhermosi** [comment]
Great Thanks Pavol, I'm still reading on my side too

**Comment by cadavre** [comment]
Hi, I'm also looking for a solution that would ease using ECR with Docker Swarm. Having this in Swarmpit would give it a huge advantage over Portainer in this matter.

**Comment by nohaapav** [comment]
@cadavre Hi cadavre .. We're going to support all major registries in next release .. ECR, Azure, gitlab.com .. google as well probably .. but first 3 are the priorities

**Comment by cadavre** [comment]
Just as a follow-up...

ECR's 12h TTL token is obtained mostly via `awscli`s `aws ecr get-login`. This uses AWS key ID, key secret and region. But there are also EC2 IAM Roles which can give access to particular nodes (i.e. EC2 instances with manager role) without need for passing secret credentials. It uses then instance metadata to obtain credentials and use them in behalf of key id+secret. It is very convenient because we don't need to store credentials anywhere in browsable UI or env_vars.

It would be awesome if Swarmpit could leverage this option as well. If you'll use any of official AWS SDKs I believe it will come out-of-the-box.

**Comment by nohaapav** [comment]
Hi, i guess we're going to support ecr login based on AWS parameter KEY, SECRET and REGION in first phase. Later on we can discuss other possibilities. IAM user is from my perspective the easiest and most straightforward way to setup access even for new user and i don't want to overcomplicate things in the very beginning :)

**Comment by cadavre** [comment]
True. I'd do the same in the beginning. But please keep this in mind. :)

**Comment by cadavre** [comment]
For me – one of gamechangers for Swarmpit. Looking forward to check it.

**Comment by isbkch** [comment]
Any update on this?

**Comment by nohaapav** [comment]
@isbkch See the tag. This change is done in 1.7 .. You can use latest (edge) version to check it out ..

**Comment by isbkch** [comment]
I missed that. Thank you, I'll give it a try
