### ISSUE TITLE
[Stacks] Error: No such image xxx/yyy:zz

### ISSUE THREAD

**Issue by abellion** [swarmpit/swarmpit#237]
**Description**

When deploying a stack, these tasks are in `rejected` state with the following error : 

> No such image: provider/software:tag

When hitting "Redeploy" button from the UI, everything works.

**Steps to reproduce the issue:**
1. Connect the UI to a DockerHub registry
2. Deploy a stack with an image from this registry

**What happens:**
The tasks cannot find the image.

**What should happen:**
They should be able to retrieve the image from the DockerHub registry.

**Additional information (e.g. docker version, cluster setup,...):**
Latest Docker / Swarmpit setup within a cluster (5 servers).

**Comment by abellion** [comment]
It seems yeah.

Adding the `--with-registry-auth ` flag should do the trick as stated there : https://github.com/moby/moby/issues/31534#issuecomment-304642411 and confirmed on https://github.com/moby/moby/issues/31534#issuecomment-314555207 for latest version.

I don't know if this flag can be given through the API but I guess it can. Looking forward for your thoughts. Thanks !

**Comment by nohaapav** [comment]
Well this flag is always used so it is not an issue in this case ..

**Comment by abellion** [comment]
That's weird because everything works well from the CLI but not in swarmpit.

Have you been able to reproduce the issue ?

I don't know clojure but I guess stack are deployed from this function : https://github.com/swarmpit/swarmpit/blob/bdcfae4c173f4d3924363d97ae4f35efebcd13a3/src/clj/swarmpit/docker/engine/cli.clj#L23

I see that the flag is given at the end, maybe that's the issue ? Do you think making as follow would do the trick ?

```clj
(defn- stack-deploy-cmd
  [name file]
  ["docker" "stack" "deploy" "--with-registry-auth" "--compose-file" file name])
```

**Comment by nohaapav** [comment]
@abellion Well easiest way to test if order is causing the problem is to run deployment with following command from cli:

```
docker stack deploy --compose-file $compose-file $stack-name --with-registry-auth
```

Btw are u using public images or private ?

**Comment by abellion** [comment]
Just tested, order doesn't seem to be the problem.

This is private images.

**Comment by nohaapav** [comment]
@abellion ok .. in that case did you add distribution user (dockerhub | registry) in swarmpit ?

**Comment by abellion** [comment]
Yes from dockerhub !

**Comment by nohaapav** [comment]
btw is it possible to provide your stack ? i'm mainly interesting about images of services being deployed ..

**Comment by nohaapav** [comment]
Will try to reproduce your issue. In our current clusters 20/15/15 it's working just fine and we're using private registry and dockerhub as well. We're getting this error only when nodes are full so docker can't deploy new task. But still even if task end up with such error new one is spawned on node which has free resources.

**Comment by abellion** [comment]
Could it be because deployment doesn't happen on manager node ?

I've noticed that some data are missing concerning worker nodes (eg. volumes or networks IPs).

**Comment by nohaapav** [comment]
@abellion well swarmpit should be running on manager node so the stack command is triggered there unless you changed swarmpit_app placement.

**Comment by abellion** [comment]
Oh sorry I wasn't clear. Indeed Swarmpit runs on the manager node, but services inside stack don't target the manager (but workers).

**Comment by rarous** [comment]
@nohaapav I have the same issue on `lates`.  Redeploy workaround works, but it is really annoying.

**Comment by nohaapav** [comment]
@abellion Does this happens to you also just for latest tag ? Could you try please ?

**Comment by nohaapav** [comment]
@abellion @rarous if you can copy/paste docker.log during deploy action that would be awesome to see why engine is complaining about that ..

**Comment by nohaapav** [comment]
Also please check this thread if the problem is not related:

https://www.bountysource.com/issues/42660413-docker-stack-deploy-does-not-pull-images-from-private-registry-on-17-03-0-ce-mac1

**Comment by abellion** [comment]
Yes I will try this week, thanks for having taken the time to look at it !

**Comment by abellion** [comment]
@nohaapav I can confirm it works now ! Thank you !
