### ISSUE TITLE
Docker organisation private repository - authentication failure

### ISSUE THREAD

**Issue by ben-motiv** [swarmpit/swarmpit#239]
**Description**

When trying to start a service from an image hosted in a docker hub organisation private repository I get an authentication required error.

**Steps to reproduce the issue:**
1. Add dockerhub account that has permissions on the organisation
2. Create a new service - repositories on the organisation will be selectable under "search private"
3. Enter a service name, click "create" - Service creation failed. authentication required.

**What happens:**
On clicking create the following error shows up in red at the bottom of the screen:
Service creation failed. authentication required.

**What should happen:**

The service should be created.

**Additional information (e.g. docker version, cluster setup,...):**
Tested on swarmpit 1.4 and latest, single node swarm, 
17.12.1-ce

**Comment by ben-motiv** [comment]
This is happening on all private repositories for me on dockerhub - personal or organization. Looks to be a duplicate of #203 however deletion of the swarmpit db volume, or removal and re-adding the dockerhub account has made no difference. Have tried 1.3.1, 1.4 and latest master branch.

**Comment by BatuhanK** [comment]
Are there any solutions for that? Adding&removing dockerhub user is not fixing the issue.
@nohaapav

**Comment by nohaapav** [comment]
@BatuhanK I need more details in order to see what is happening .. Already tried swarmpit with 4 separate accounts and organizations and everything works just fine. 

Are you sure that private image you're using has latest tag if left blank ? See my previous comment.

**Comment by BatuhanK** [comment]
@nohaapav We can't create any services using private images because it gives `Repositories fetching failed.` error.
Also if we try to edit an existing service it fails because of `/repository/tags?repository=tusla/REPO-NAME` request gives 401

**Comment by BatuhanK** [comment]
@nohaapav 
```js
{"role":"User","_id":"c601ae6986fb1890a9e7*****000ab5","namespaces":["tusla"],"_rev":"1-390d695ba25786b81******8dfde1d","name":null,"username":"tusla","public":false,"type":"dockeruser","location":"","company":"","owner":"admin"}
```

**Comment by nohaapav** [comment]
@BatuhanK Try this please:

```GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:tusla/REPO-NAME:pull```

with req headers:

```
Authorization: "Basic BASE64(user + ":" + password)"
```

Then call:

```GET https://index.docker.io/v2/tusla/REPO-NAME/tags/list```

with given token from previous request:

```
Authorization: "Bearer ${token}"
```

**Comment by BatuhanK** [comment]
@nohaapav It's not working.
GET https://index.docker.io/v2/tusla/REPO-NAME/tags/list with token gives this error.
```js
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
                {
                    "Type": "repository",
                    "Class": "",
                    "Name": "tusla/whatsapp-instance",
                    "Action": "pull"
                }
            ]
        }
    ]
}
```

But we didn't made any changes on this repo, why getting unauthorized errors now :/

**Comment by nohaapav** [comment]
@BatuhanK Well at least we know where the problem is .. Looks like the user u are using have insufficient privileges for that repository.. Are you sure your dockerhub account setup is ok ? 

I was trying the same flow for my public and organization accounts and it's working just fine..

**Comment by nohaapav** [comment]
@BatuhanK TA-DA .. great to hear that ;)
