### ISSUE TITLE
Create service from private repository: manifest unknown

### ISSUE THREAD

**Issue by goncalo-oliveira** [swarmpit/swarmpit#240]
**Description**

I've just installed a clean stack and tried to create a service with an image from a private repository. The service promptly replies with the message "".

**Steps to reproduce the issue:**
1. Add a private repository account (https)
2. Create a new service with an image from the private repository
3. Hit create

**What happens:**

I receive the error message "Service creation failed. manifest unknown". This is the message coming out of the http request, that comes out as a 404.

```javascript
{"error":"manifest unknown"}
```

**What should happen:**

Service should have been created.

**Additional information (e.g. docker version, cluster setup,...):**

Docker version:
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

The request sent:
```javascript
{
	"labels": [{
		"name": "com.df.notify",
		"value": "true"
	}, {
		"name": "com.df.port",
		"value": "80"
	}],
	"repository": {
		"name": "r.privateregistry.com/hello",
		"tag": "latest"
	},
	"mounts": [],
	"secrets": [],
	"mode": "replicated",
	"variables": [],
	"networks": [],
	"ports": [],
	"logdriver": {
		"name": "json-file",
		"opts": []
	},
	"replicas": 1,
	"deployment": {
		"autoredeploy": false,
		"restartPolicy": {
			"condition": "any",
			"delay": 5,
			"attempts": 0
		},
		"update": {
			"parallelism": 1,
			"delay": 0,
			"order": "stop-first",
			"failureAction": "pause"
		},
		"rollback": {
			"parallelism": 1,
			"delay": 0,
			"order": "stop-first",
			"failureAction": "pause"
		},
		"placement": []
	},
	"serviceName": "hello",
	"resources": {
		"reservation": {
			"cpu": 0,
			"memory": 0
		},
		"limit": {
			"cpu": 0,
			"memory": 0
		}
	},
	"configs": null
}
```

**Comment by goncalo-oliveira** [comment]
@nohaapav thanks for the quick reply. You're right, it's a registry issue. It turns out that this image doesn't have a _latest_ tag. Setting a specific tag (which exists) does the trick.

Many thanks!

**Comment by nohaapav** [comment]
@goncalo-oliveira yes we're using latest by default if nothing is filled .. and that end up with wrong manifest .. Glad that it works for you now ..
