### ISSUE TITLE
Volume name not encoded in URL

### ISSUE THREAD

**Issue by plockare** [swarmpit/swarmpit#254]
**Description**

The volume name is not taking care of '/' character. The name should be encoded in the URL so the detail view would be accessible.

**Steps to reproduce the issue:**
1. Set volume name as `23844.s44.wedos.net/s23844`
2. Go to page `/#/volumes/23844.s44.wedos.net/s23844`

**What happens:**

404 is returned.

**What should happen:**

We should see detail of the volume.

**Comment by lumir-mrkva** [comment]
@plockare volume name can be only `[a-zA-Z0-9][a-zA-Z0-9_.-]` and that is url safe
