### ISSUE TITLE
Mobile friendly UI

### ISSUE THREAD

**Issue by rarous** [swarmpit/swarmpit#256]
Make UI mobile friendly PWA.

**Comment by lumir-mrkva** [comment]
- [ ] distribution make private button, add lock when account is private
- [ ] rename distributions to registries
- [ ] **navigation crashes when loading**
- [ ] count resources in stack info summary
- [ ] links with new tab icon
- [ ] grey secondary label in list
- [ ] center labels in collumn
- [ ] break words in env vriables to fix responsivity
- [ ] stack name in service name on info page
- [ ] remove service name from tasks list in service info
- [ ] invert sort of tasks in service info
- [ ] remove brackets from memory usage in task list 
- [ ] autoredeploy status in summary
- [ ] smaller titles in cards (highlight summary card)
- [ ] contents navigation in service edit
- [ ] add service name to service edit title
- [ ] service create wizard like registries
- [ ] show resources in task info
- [ ] keep search in every view
- [ ] (mobile) keep search value between search input toggles
- [ ] show newest (created) tasks on top
- [ ] show count of linked services in config/secret list & summary
- [ ] remove “Name” “Value” labels in key value inputs
- [ ] 1/3 & 2/3 network, volume, configs, secrets ... info
- [ ] see service link in task info
- [ ] fix see stack when stack doesn't exist
- [ ] % tooltip in pie chart (nodes)
- [ ] **crash on pending tasks**
- [ ] (mobile) search button doesn't trigger keyboard, input is not focused
- [ ] (mobile) actions menu in info can move randomly to left
- [ ] (mobile - safari) inputs can have stiked through labels

**Comment by lumir-mrkva** [comment]
- [ ] make list items "clickable", allow to open items in new tab

**Comment by nohaapav** [comment]
Rest can be moved to next release. Closing ...
