### ISSUE TITLE
Feature request: copy "exec through ssh" into clipboard

### ISSUE THREAD

**Issue by Vanuan** [swarmpit/swarmpit#259]
**Description**

Currently to exec into a container one must open service, see which machines have the task deployed, ssh into the machine, use docker ps command to fine the container, use docker exec command.

It would be much easier if UI has some "copy exec command" button which would put the string `ssh {{node}} docker exec -ti {{containerID}} sh` into a clipboard.

**Steps to implement:**
1. Form an ssh command
2. Add "copy" button to the tasks or services screen
3. Use exec command to copy text:
```
 var sshExecCmd = document.getElementById("ssh-exec-command");
 sshExecCmd.select();
 document.execCommand("copy");
```

**What should happen:**

Then I can paste the command to my terminal and go straight into container.

**Additional information (e.g. docker version, cluster setup,...):**

I saw there's #93 planned, but this one is much easier to implement and can be re-purposed after the former is ready.

**Comment by rarous** [comment]
Swarmpit does not know public IPs/DNS of nodes, so you can't reliably generate SSH command. I believe #93 is high on priority list for next release.

**Comment by Vanuan** [comment]
AFAIK `docker node ls` lists public FQDN of nodes.

**Comment by lumir-mrkva** [comment]
for this to work swarmpit would have to have access to the private key and I don't think that's a good idea

**Comment by Vanuan** [comment]
Why? Wouldn't this work:

GET /v1.24/nodes HTTP/1.1

resp[].Description.Hostname
