### ISSUE TITLE
Peformance improvement request: use --since to fetch logs

### ISSUE THREAD

**Issue by Vanuan** [swarmpit/swarmpit#260]
**Description**

Currently there's a long delay after you click "Logs" button. It's cause by swarmpit fetching fresh logs from docker daemon. This is not only bad user experience but causes issues in docker swarm due to manager being busy.

Suggestions:

- fetch only last minute logs (--since 1m) and add UI to fetch older logs
- add a feature to disable logs (so that users are forced to use Fluentd, ELK or whatever)
- use logging driver rather than docker.sock to fetch logs

**Comment by nohaapav** [comment]
We're aware of this issue and working on it.

**Comment by Dids** [comment]
Any updates on this? I'm seeing timeouts (#274) with more and more services, even when using json-file options that limit log files to 3x1MB.

**Comment by nohaapav** [comment]
@Dids Hi, yes in this release we're going to improve log experience.

**Comment by nohaapav** [comment]
We are going to use agent to fetch logs in 1.7. That means only container API will be used. 

Advantages:
- if service instance not hosted on manager -> manager not being busy
- load is distributed
- even in case of cluster inconsistencies we'll be still able to fetch
   container logs unless overlay network broken
- fetching same amount of logs via container api is way more faster, service api tends to
   timeout for log intensive services

Apart of that we're going by default fetch logs for last 15 minutes with dropdown of different choices: 15m, 30m, 1h, 4h, 8h, 12h, 24h, ALL .. 

Last one, logs button is going to be disabled for other than json-file journald driver and we will prefetch all log drivers based on engine plugins, same as for volumes, networks
