### ISSUE TITLE
clicking on node in nodes view navigates to absolute url

### ISSUE THREAD

**Issue by ediphy-dwild** [swarmpit/swarmpit#263]
**Description**

When swarmpit is placed behind a proxy at a non '/' url, when clicking on a machine in the nodes view, the url navigated to is that of an absolute path, which fails to route back to the swarmpit instance, resulting in a 404

**Steps to reproduce the issue:**
1. when accessing swarmpit behind eg https://my.domain.com/admin/service/swarmpit, things generally work fine
2. click on a node in the nodes view

**What happens:**
the url location collapses to (eg) https://my.domain.com/#/nodes/<yadayada>

**What should happen:**
https://my.domain.com/admin/service/swarmpit/#/nodes/<yadayada>
(when entered manually, this url navigates correctly to a description of the node in question)

The rest (i think) of the links in the webapp work correctly, the only issue we have is with the nodes view.

**Additional information (e.g. docker version, cluster setup,...):**
running docker image: swarmpit/swarmpit:1.5

Client:
 Version:	17.12.0-ce
 API version:	1.32 (downgraded from 1.35)
 Go version:	go1.9.2
 Git commit:	486a48d
 Built:	unknown-buildtime
 OS/Arch:	darwin/amd64
 Experimental:	false

Server:
 Engine:
  Version:	17.09.0-ce
  API version:	1.32 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	afdb6d4
  Built:	Tue Sep 26 22:40:48 2017
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by lumir-mrkva** [comment]
@ediphy-dwild thank you for a report, it should be working as expected now
