### ISSUE TITLE
Support custom links in service UI

### ISSUE THREAD

**Issue by rarous** [swarmpit/swarmpit#264]
Add support to create links from Swarmpit UI to 3rd party services. Typically you will add label like `io.swarmpit.service.link` with URL as value and then Swarmpit will add Button/CTA on service detail with the URL.

**Comment by nohaapav** [comment]
add label `swarmpit.service.link.name1` with value to make it work. If you wish to have multiple buttons just specify:

`swarmpit.service.link.name1` results in [NAME1] button
`swarmpit.service.link.name_test`results in [NAME TEST] button
