### ISSUE TITLE
Unable to create Artifactory docker repository without credentials

### ISSUE THREAD

**Issue by warmfusion** [swarmpit/swarmpit#266]
**Description**

Unable to create new service from Artifactory hosted docker registry.

**What happens:**

1. Registry is added  ( https://docker.artifactory.company.name - Fully valid certificate )
1. A service is created
1. An error is displayed showing "Service creation failed. Not Acceptable"

Looking at the artifactory server logs, we see the following

```
==> ./access.log <==
2018-07-30 09:20:47,302 [DENIED LOGIN]  for NA/127.0.0.1.

==> ./request.log <==
20180730092047|1|REQUEST|127.0.0.1|non_authenticated_user|GET|/api/docker/docker/v2/myservice/manifests/servicetag|HTTP/1.1|401|0
20180730092047|1|REQUEST|127.0.0.1|anonymous|GET|/api/docker/docker/v2/token|HTTP/1.1|406|0
```

When using authentication, and given valid credentials the error messages change to;

```==> ./request.log <==
20180730091753|189|REQUEST|127.0.0.1|warmfusion|GET|/api/docker/docker/v2/_catalog|HTTP/1.1|200|0

==> ./access.log <==
2018-07-30 09:17:55,903 [DENIED LOGIN]  for NA/127.0.0.1.

==> ./request.log <==
20180730091755|0|REQUEST|127.0.0.1|non_authenticated_user|GET|/api/docker/docker/v2/fte-feeds/tags/list|HTTP/1.1|401|0
20180730091755|8|REQUEST|127.0.0.1|anonymous|GET|/api/docker/docker/v2/token|HTTP/1.1|200|0
```

**What should happen:**

Service is created

**Additional information (e.g. docker version, cluster setup,...):**

SwarmPit: 1.6-2a0a14b
Docker:  18.03.1-ce
3 Node cluster

## Update - 2018-08-03

Removal of all existing attempts to create a repository, and then creating a new Artifactory backed repository using credentials appears to work properly. As such, it seems this issue is limited to the case where a repository is being added without having credentials defined.

**Comment by nohaapav** [comment]
@warmfusion Is this standard v2 registry ?

**Comment by warmfusion** [comment]
We're using standard artifactory configuration so a v2 api endpoint.

The login api is fully compatible with the docker client as can be seen here;

```
UKML0090:~ tjackson02$ docker login docker.artifactory.company.name
Username: tjackson02
Password:
Login Succeeded
```

We've been able to boot services on the same docker swarm cluster using portainer, and use this registry a lot for local and CI based dev activities.

Note that we also don't require user login to pull images from the containers (at least at the moment) as its all behind our firewall stacks.

**Comment by nohaapav** [comment]
@warmfusion 
1)Did you use same swarmpit user for registry creation/registration as for service creation ? Just curious .. 
2)Are u able to list images in your custom registry ?

**Comment by nohaapav** [comment]
Swarmpit needs valid registry credentials during registry registration if not insecure. So we can skip case 1.  What error exactly is returned by Swarmpit during service creation in case 2 (authentication used)?

**Comment by drujon** [comment]
Hi, joining the thread.
1) We have tried with the same user and different users.
2) Yes, when creating a service swarmpit lists all available images.

There is a problem with authentication disabled, but I just deleted all previous entries and added it with auth enabled and worked.

**Comment by drujon** [comment]
But with authentication enabled it can list images but fails with the error pasted in the issue
"Service creation failed. Not Acceptable"

**Comment by warmfusion** [comment]
Updated ticket desc/title to reflect changed behaviour based on @drujon 's investigation

**Comment by nohaapav** [comment]
@drujon It's strange that you are able to create registry without authentication. If registry is secured with auth required this should not happen.

What happens if you call following url from browser:
`GET https://{your_registry_url}/v2/`

This error should pop-up if no credentials were provided:

```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": null
        }
    ]
}
```

**Comment by nohaapav** [comment]
Just tried myself to create/update service with insecured v2 without credentials and everything worked well.  If problem persist feel free to reopen.
