### ISSUE TITLE
unable to try Swarmpit

### ISSUE THREAD

**Issue by carvajalluis** [swarmpit/swarmpit#273]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
-->

**Description**

unable to try Swarmpit when following up installation steps .

**Steps to reproduce the issue:**
1. create a swarm cluster
1. follow up install steps
1. `docker stack deploy -c swarmpit/docker-compose.yml swarmpit`
2. `docker stack ps swarmpit`

**What happens:**

unable to access swarmpit on any node at port 888

C:\VCS>docker stack ps swarmpit
ID                  NAME                                           IMAGE                   NODE                    DESIRED STATE       CURRENT STATE              ERROR                              PORTS
06jcryolue14        swarmpit_agent.pllgg63sd4madk6to1qul2bng       swarmpit/agent:2.0      linuxkit-00155d015104   Running             Preparing 12 seconds ago
tfx72472blxx         \_ swarmpit_agent.pllgg63sd4madk6to1qul2bng   swarmpit/agent:2.0      linuxkit-00155d015104   Shutdown            Rejected 12 seconds ago    "No such image: swarmpit/agent…"
ta2ujscvr2p6         \_ swarmpit_agent.pllgg63sd4madk6to1qul2bng   swarmpit/agent:2.0      linuxkit-00155d015104   Shutdown            Rejected 17 seconds ago    "No such image: swarmpit/agent…"
oiyb02n7n6l3         \_ swarmpit_agent.pllgg63sd4madk6to1qul2bng   swarmpit/agent:2.0      linuxkit-00155d015104   Shutdown            Rejected 33 seconds ago    "No such image: swarmpit/agent…"
curf1tv6p7nt         \_ swarmpit_agent.pllgg63sd4madk6to1qul2bng   swarmpit/agent:2.0      linuxkit-00155d015104   Shutdown            Rejected 38 seconds ago    "No such image: swarmpit/agent…"
imv8lpi5ica8        swarmpit_agent.kk0s9azl0rmw5xy27fv5j6gxp       swarmpit/agent:2.0      n1                      Running             Running 53 seconds ago
hhth6bm6t52i        swarmpit_agent.jf0lb2wpfo7dlkqkclkeyelss       swarmpit/agent:2.0      n2                      Running             Running 53 seconds ago
8kxigdyp1qz1        swarmpit_agent.2b3xyc8irmr78n7jr9ve2tfuk       swarmpit/agent:2.0      n3                      Running             Running 53 seconds ago
zgxz0bal3q5a        swarmpit_db.1                                  klaemo/couchdb:2.0.0    n1                      Running             Running 55 seconds ago
s785i5bt9hms        swarmpit_app.1                                 swarmpit/swarmpit:1.5   n2                      Running             Running 56 seconds ago

**What should happen:**
 I should be able to experience swarmpit for the first time with no hazel

**Additional information (e.g. docker version, cluster setup,...):**

C:\VCS>docker -v
Docker version 18.06.1-ce, build e68fc7a

C:\VCS>docker-machine ls
NAME   ACTIVE   DRIVER   STATE     URL                      SWARM   DOCKER        ERRORS
n1     -        hyperv   Running   tcp://10.15.1.103:2376           v18.06.1-ce
n2     *        hyperv   Running   tcp://10.15.5.43:2376            v18.06.1-ce
n3     -        hyperv   Running   tcp://10.15.1.89:2376            v18.06.1-ce

**Comment by lumir-mrkva** [comment]
@carvajalluis interesting, it looks like swarmpit is running ok according to `docker stack ps`, can you pls send me `docker inspect` and `docker logs` of `swarmpit_app` container?

**Comment by macduff23** [comment]
Hello,

I recently tried to deploy swarmpit on docker swarm 2nodes 
Ubuntu 17/docker17.x
Ubuntu16/docker17x

Install - 
git clone https://github.com/swarmpit/swarmpit -b 1.5
docker stack deploy -c swarmpit/docker-compose.yml swarmpit

The install was successful both containers are online on each node.
no access ERR - internal server error connection denied.

A whole other issue maybe:
Thought I would just decom the swarmpit containers and the couchDB container.. for now but I cannot .

I tried scrubbing all docker containers and volumes.  
Container cleanup script:
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
And image cleanup script:

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -a -q)

root@chief:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
swarmpit/swarmpit   <none>              a1dbc88b5164        3 days ago          272 MB
swarmpit/agent      <none>              66ac38690cb2        3 months ago        8.09 MB

root@chief:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
0f7839c89aa8        bridge              bridge              local
c0ff8c8d2d80        docker_gwbridge     bridge              local
41ab2e9204f0        host                host                local
j4b91dkyzwzs        ingress             overlay             swarm
e55e5d009301        none                null                local
23zzf4huejnq        swarmpit_net        overlay             swarm

The interesting thing is I cannot get the 3 containers to remain stopped - or remove them.

Any thoughts would be appreciated , many thanks

**Comment by nohaapav** [comment]
@macduff23 Just wait till new release .. we're preparing brand new responsive ui .. 💯

**Comment by macduff23** [comment]
Pavol - Illhave to come back to swarmpit is the new release out I would
love to give it another try I currently have been using swarmprom - its ok
the UI is kinda generic and ugly. Cheers. thanks

**Comment by nohaapav** [comment]
Hi, new release will be out in few days, definitely in December. We initially thought that release will be out at Dockercon but unfortunately we're very busy to finish it in time. Few screens regarding graphics here:

<img width="1525" alt="screen shot 2018-12-04 at 11 08 30 am" src="https://user-images.githubusercontent.com/4179104/49434871-8823f800-f7b5-11e8-9183-4fcb195bc6d8.png">
<img width="448" alt="screen shot 2018-12-04 at 11 09 48 am" src="https://user-images.githubusercontent.com/4179104/49434886-8fe39c80-f7b5-11e8-87f9-059823a78135.png">

**Comment by macduff23** [comment]
- OH wow looks Good wow good job! looking forward to it! cheers thats
badass!

**Comment by Dids** [comment]
@nohaapav Figured I wouldn't open a new issue just for this, but should the new UI already be a part of Swarmpit 1.6? I still see the old UI, while even the website is showing off the new UI, so I'm wondering if I've missed something, or if it just hasn't been released yet?

**Comment by nohaapav** [comment]
@Dids Hi Dids, try to delete browser cache. The new UI is indeed part of 1.6 ;) You can simply verify this by opening swarmpit in incognito window.

**Comment by Dids** [comment]
@nohaapav Unfortunately that didn't work either, and I even tried several browsers (and cleared the cache).

Here's what it looks like with Incognito mode, and you can see the version too:
![Screenshot](https://i.imgur.com/RsIOpOn.png)

**Comment by nohaapav** [comment]
This is not 1.6 release version, but some old 1.6 snapshot based on screenshot. Update the swarmpit to 1.6 or latest (1.7 snapshot) to see the change.

**Comment by Dids** [comment]
@nohaapav You're absolutely correct. It showed the `app` service as last updated a few hours ago, so I figured it was auto-updating, but nope, redeploying fix it.

Thank you, the new UI looks amazing! :)

**Comment by lambotchi** [comment]
There seems to be a problem deploying swarmpit on a swarm with multiple nodes. I simple make sure that it is a single docker swarm beforee running swarmpit and then join nodes afterwards.
