### ISSUE TITLE
Show last updated and Error in "Tasks" overview

### ISSUE THREAD

**Issue by hpbieker** [swarmpit/swarmpit#275]
When looking at the "Tasks" overview, you get some nice information, but it really does not give a good overview.

If you see below I have some tasks that were rejected. However, it does not tell me if this is a new or old problem. If it is old I do not really care, but if it is new I certainly have to dig into this.

My suggestion is therefore to add a "Last updated" column and an "Error" column in the task overview.

![image](https://user-images.githubusercontent.com/24992762/46190867-880b0600-c2f5-11e8-913b-91f4633371ac.png)

![image](https://user-images.githubusercontent.com/24992762/46190986-0e274c80-c2f6-11e8-8ec0-7ffa3039cd79.png)

**Comment by nohaapav** [comment]
@hpbieker Hi Hans, we're working on new responsive UI so we'll consider to add these columns as well.. Btw you can actually filter relevant tasks updated at specific date by simply writing 

2018-09-22

Search is full-text (we're searching through every attribute value in task json)

**Comment by nohaapav** [comment]
Done. Error shown on state hover.
