### ISSUE TITLE
No information about volumes in current engine state

### ISSUE THREAD

**Issue by rustamzh** [swarmpit/swarmpit#277]
After creation of stack with volume if I want to make minor changes I need to rely on _Last deployed_ option of docker-compose source, because _Current engine state_ does not reflect volumes mounted in containers. Is it possible to fix it? (Reflect volumes in generated docker-compose file)

**Comment by nohaapav** [comment]
@rustamzh Could you provide example ?

**Comment by sguilly** [comment]
See #352

**Comment by nohaapav** [comment]
Closing in favour of #352
