### ISSUE TITLE
OutOfMemoryError errors in log

### ISSUE THREAD

**Issue by hpbieker** [swarmpit/swarmpit#279]
**Description**
I keep getting out of memory log entries, and Swarmpit becomes unresponsive:
```
Wed Oct 17 08:28:26 GMT 2018 [worker-4] ERROR - GET /stacks
java.lang.OutOfMemoryError: Java heap space
Exception in thread "async-dispatch-3" java.lang.OutOfMemoryError: Java heap space
Exception in thread "async-dispatch-6" java.lang.OutOfMemoryError: Java heap space
Wed Oct 17 10:24:06 GMT 2018 [worker-4] ERROR - GET /services
java.lang.OutOfMemoryError: Java heap space
Exception in thread "async-dispatch-4" java.lang.OutOfMemoryError: Java heap space
```

**Steps to reproduce the issue:**
It comes back automatically.

**What happens:**
I get out of memory exceptions in the log. Some parts does not function.

**What should happen:**
It should not give out of memory. Garbage collection should work :-)

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by nohaapav** [comment]
Well it looks like you are physically out of memory .. Can you provide some systems statistics/additional info ?

**Comment by constantineav** [comment]
java.lang.OutOfMemoryError: Java heap space
free -m
              total        used        free      shared  buff/cache   available
Mem:          15661        9657        2416           2        3587        7473
Swap:             0           0           0

what other additional information do I need to provide?
