### ISSUE TITLE
database_does_not_exist in logs

### ISSUE THREAD

**Issue by sinacek** [swarmpit/swarmpit#280]
**Description**
I start new swarmpit stack and in logs i found error:
`swarmpit_db.1.da1e113j2hv6@host    | [error] 2018-10-17T22:57:11.828692Z nonode@nohost emulator -------- Error in process <0.21970.32> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk... `

This error doesn't limit me in any way

**Steps to reproduce the issue:**
1. Create new Swarmpit stack
2. `docker service logs swarmpit_db`

**What should happen:**
It should works without error in logs.

**Comment by lumir-mrkva** [comment]
dublicate / subset of #192
