### ISSUE TITLE
Image search in repositories is broken in case of '/' in the name

### ISSUE THREAD

**Issue by filemon** [swarmpit/swarmpit#285]
**Description**
The list of images retrieved while using backslash in the name is incorrect.

**Steps to reproduce the issue:**
1. Search for public image `topmonks/docker-napp`

**What happens:**

The list contains many unrelevant images (completely different names)

**What should happen:**

I should see only the relevant finds

**Additional information (e.g. docker version, cluster setup,...):**

<img width="834" alt="screenshot 2018-11-15 at 14 05 58" src="https://user-images.githubusercontent.com/35973/48555008-38ea5600-e8e0-11e8-90e0-9c888c124414.png">

**Comment by nohaapav** [comment]
@filemon Could you check within new UI .. Looks fine to me now.

<img width="1657" alt="Screen Shot 2019-03-15 at 5 50 52 PM" src="https://user-images.githubusercontent.com/4179104/54447971-f7ad6a00-474a-11e9-9461-ba5b1435f8d2.png">
