### ISSUE TITLE
Save the generated stack file for future deployment

### ISSUE THREAD

**Issue by filemon** [swarmpit/swarmpit#286]
**Description**
Newly created stack file can only be Deployed. This is very likely to fail in case the original service exports a port or there is another clash with already running service. There is no Save action. Workaround is to copy paste the generated stack file, stop the service and create/deploy the copied stack file. 

**Steps to reproduce the issue:**
1. Edit-Compose on the already running service with an exported port

**What happens:**
1. Stack can only be deployed (but can't due to the port conflict)

**What should happen:**
1.  (Easier) It should be allowed to save the generated stack file for future deployment
2. (Harder) Swarmpit should save the stack, stop original the service and redeploy it automatically when user clicks on Deploy button. Warning would be nice. 

**Additional information (e.g. docker version, cluster setup,...):**

<img width="1228" alt="screenshot 2018-11-19 at 10 43 35" src="https://user-images.githubusercontent.com/35973/48699391-a13f7d00-ebe9-11e8-91ea-4ab9cb73b090.png">

**Comment by nohaapav** [comment]
Done opt 1)
