### ISSUE TITLE
Feature Request: Show Containers that are not part of a Stack

### ISSUE THREAD

**Issue by dmpro** [swarmpit/swarmpit#287]
Being able to see running and stopped "standalone" containers, that are not part of an active Stack and perform common actions on them, like start/stop/delete/inspect, would be really helpful, as I often just run standalone containers both locally and within my company.

This is basically equivalent to seeing the results of `docker container ls -a`, filtered to remove any container that is part of an active Stack, as a list within the UI.

Not being able to view and manage these containers within swarmpit means running 2 different tools - locally I just use IntelliJ's Docker support, but we also use Portainer (although looking to switch to swarmpit).

**Comment by lumir-mrkva** [comment]
@dmpro i suppose these containers are still belonging to service and tracked by swarm right? we're not planning to manage single engine containers.

**Comment by nohaapav** [comment]
Please see very first section of ROADMAP overview:

https://github.com/swarmpit/swarmpit/blob/master/ROADMAP.md#overview

As Lumir stated we won't be supporting majority of container API as there is no point for that. Just use service abstraction even for single container ..

**Comment by dmpro** [comment]
Ok, I hadn't seen that first line in the roadmap, so apologies for that. I guess that's fair enough.
