### ISSUE TITLE
Allow management of "extra_hosts" from UI

### ISSUE THREAD

**Issue by Andycharalambous** [swarmpit/swarmpit#292]
It would be nice to be able to view and manage the "extra_hosts" config from the UI. 

Also, any hand-written extra_hosts config I add into a stack's configuration yaml is lost when viewing the currently deployed view of a stack - I've gone in to this view many times to make a small amend and found that I've inadvertently blown away all other configs that swarmpit for some reason doesn't display under the currently deployed editor.

**Comment by nohaapav** [comment]
@lumir-mrkva Could you please check this stack engine state inconsistency please ..
