### ISSUE TITLE
Can't connect to hosted Gitlab registry

### ISSUE THREAD

**Issue by sinacek** [swarmpit/swarmpit#296]
**Description**
I'm dont see any images from my hosted gitlab private registy. I can add there credentials, but then I don't see any images by find in 'Create new service -> other registries' 

**Steps to reproduce the issue:**
1. Create docker registry on hosted gitlab.
2. Run swarmpit.
3. Add Gitlab credentials to swarmpit.
4. Try find image 'tick' in Gitlab registry.

**What happens:**
I don't see any images from registry.

**What should happen:**
Find any image from private registry.

**Additional information (e.g. docker version, cluster setup,...):**
Swarmpit 1.6 (the newest)
Gitlab 11.6 (the newest)
@plockare has credentials to our gitlab.

**Comment by nohaapav** [comment]
@sinacek Hey, is it working with swarmpit 1.5 for you ? 1.6 is still in development and we did some major changes there so this might be consequence. Anyway thx for reporting.

**Comment by sinacek** [comment]
No, 1.5 also doesn't work with my registry.

**Comment by nohaapav** [comment]
Ok i will check the registry when @plockare is online :) .. hopefully gitlab didn't move from traditional v2 to some custom setup.

**Comment by sinacek** [comment]
I'm able with gitlab use `docker login` and it also works with https://github.com/v2tec/watchtower

**Comment by nohaapav** [comment]
Well I'm actually using gitlab registry with no issue at all .. Waiting for @plockare to provide some details to check what is wrong on your side.

**Comment by nohaapav** [comment]
Stupid question but are u using your gitlab user + private token with api access ?

**Comment by sinacek** [comment]
Yes, I tried it again. It works for you?

**Comment by nohaapav** [comment]
First of all make sure that your registry is exposed on different url than gitlab .. See:

```
GITLAB_OMNIBUS_CONFIG: |
        ### GitLab
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['client_max_body_size'] = '1024m'
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        ### Registry
        registry_external_url 'http://registry.example.com'
        gitlab_rails['registry_enabled'] = true
        registry['enable'] = true
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5001
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
```

Then gitlab user + private token should work. See mail email

**Comment by kthamm** [comment]
Hey, I am experiencing a similar issue. When adding a registry on swarmpit from gitlab.com, it doesn't find any images as well, when I try to create a new service with swarmpit. docker login does work though.

Just to make sure I didn't do anything wrong cofiguring the registry:
- I used https://registry.gitlab.com as url
- My gitlab.com username as user
- A personal acces token created with all scopes (api, read_user, read_reposity and  read_registry) as password
- And set it to not be public

A error message 'Repositories fetching failed. authentication required' shows up when I select the registry while trying to create a new service.

**Comment by sarendsen** [comment]
Facing the same issue as kthamm

**Comment by nohaapav** [comment]
@kthamm @sarendsen Hi guys, i was debugging this a bit and it looks like you need to have admin role within your gitlab account. Then it should work. Not sure why user role is not enough. Need to check magic behind in more details.

**Comment by sarendsen** [comment]
@nohaapav tnx, for the debugging. Though im owner of the gitlab account + repos and still the authentication fails.

**Comment by nohaapav** [comment]
<img width="1416" alt="screen shot 2019-01-14 at 12 45 34 pm" src="https://user-images.githubusercontent.com/4179104/51110873-55304380-17fa-11e9-9949-b5f3deb7ab10.png">

So you have `admin` role right ? I've tried 2 identical accounts, one with admin role, one with regular .. Admin is working fine, Regular getting the error above.

Anyway this problem is related only to access to registry catalog. You should be able to create service from private images by using regular account (by e.g. stack api), you just can't search for service list.

**Comment by nohaapav** [comment]
@kthamm ah .. i see .. Yeah that will the the root cause. I have hosted gitlab which works fine if i have admin access in place. Probably some gitlab restriction.

In that case there is not much we can do regarding repository listing.  As i mentioned you still can use your private repository with regular user, you just can't use this swarmpit feature. We need to
introduce some text field for such cases so you can specify image manually in service api. As workaround you can use stack API. In new release (end of week) we'll introduce this functionality
for sure.

**Comment by nohaapav** [comment]
@kthamm Ok confirmed. I've created account on gitlab.com .. unfortunately they don't support v2 catalog api for regular access (all users), just admin access. 

They don't even have some custom api to list all the images for all projects of specific user, you can list only images for particular project .. 

`https://gitlab.com/<user>/<project_name>/container_registry.json?format=json&private_token=`

That means we will have to list all the projects (repositories) first and then fetch images for each (and merge) .. So in theory it's possible to make it work, unfortunately we won't make it in 1.6. 

Anyway in 1.7 we're going to support AWS, Azure and other custom registries so we can add gitlab.com support as well ;)

**Comment by nohaapav** [comment]
@sinacek How is this related to this issue ? Your gitlab runs out of resources .. This issue is related to catalog api access ? Am i missing something :) ?

**Comment by sinacek** [comment]
It's related for auto deployment which was my goal. Catalog api access was just way how test access to repository for me. My Gitlab runs out of resources only when I add credentials into swarmpit.

**Comment by nohaapav** [comment]
I really don't believe that registry api call every minute is the cause of failing gitlab unless some poor gitlab nginx configuration. Even our registry client has default timeout set to 15 sec in case that something go wrong. Some more details would be nice. We have currently like 20+ projects hosted on gitlab with autoredeploy in place with no issue even if registry is busy and not responding .. 

Could you please share some gitlab logs, symptoms so i can take a look. Personal email is fine ;)

**Comment by sarendsen** [comment]
Love the 1.6 rework and great to hear this will be supported! Should we make this a feature request then?

**Comment by nohaapav** [comment]
@sarendsen Please do

**Comment by sinacek** [comment]
I had probably problem on company firewall.

**Comment by nohaapav** [comment]
https://github.com/swarmpit/swarmpit/issues/341

**Comment by peacememories** [comment]
Hi, sorry to revive this dead issue. I have the same issue with our new swarmpit 1.7 setup.

We have a gitlab server at `https://<domain>` and a gitlab container registry at `https://<domain>:4567`. I created a deploy token for our repository, and tried to add it to swarmpit.

# Using Gitlab Registry option
1. I entered `https://<domain>` as Gitlab url
2. I entered `https://<domain>:4567` as Registry url
3. I entered our token username as username
4. I entered our token password as password
5. The creation succeeds :heavy_check_mark: 
6. I start creating a new service
7. I switch to the newly created registry
8. I get an error slide-in: `Repositories fetching failed. 401 Unauthorized` :x: 

Note: If i use the wrong password the creation of the registry fails, so the login seems to succeed at first

# Using Registry v2 option
1. I enter `https://<domain>:4567` as url
2. I activate "secured"
3. I entered our token username as username
4. I entered our token password as password
5. The creation succeeds :heavy_check_mark: 
6. I start creating a new service
7. I switch to the newly created registry
8. I get an error slide-in: `Repositories fetching failed. authentication required` :x: 
9: The swarmpit container logs the following:
    
    > Jan 28, 2020 1:16:36 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
    > WARNING: Invalid cookie header: "Set-Cookie: experimentation_subject_id=ImIwYWYxYTFkLTM3NDMtNDhkYi1iODg0LTM4NjAwZmVhOTQyOSI%3D--3f6b0483880ae6a6b8aa9dca6ac7d76e39baa65c; domain=.<domain>; path=/; expires=Sat, 28 Jan 2040 13:16:36 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 28 Jan 2040 13:16:36 -0000

Note: same as with the gitlab registry option

# About our registry
The registry is running on a cert by Comodo, so I needed to add the CA-cert to every linux system I used it on. I did this in the host running the docker swarm as well as the docker container running swarmpit (of course this is only temporary).

# What works

* Logging into the registry on the host with `docker login https://<domain>:4567`
* Logging into the registry on the swarmpit container with `docker login https://<domain>:4567`

# Autoredeploy

I pulled an image from the registry manually (after logging in on the host), and created a service using that, enabling autodeploy. The autodeploy fails with the following message:

> SEVERE: Service sb5wpaey2jv96dd2ctr75f5r5 autoredeploy failed!  {:status 408, :body {:error Request timeout}}

**Comment by nohaapav** [comment]
@peacememories What about latest swarmpit (1.9)?

**Comment by peacememories** [comment]
Oh, I did not notice there was a new one. Are there upgrade instructions anywhere? Do I just rerun the installer?

**Comment by nohaapav** [comment]
@peacememories that won't work as you already have swarmpit installed .. the best way is to update stack with the one in master or delete existing stack and install again ...

**Comment by peacememories** [comment]
@nohaapav I've updated to `:latest` by redeploying the stack (i've left all other services the same, I hope this is correct) - the new interface is very nice btw - but the problem still persists.

**Comment by nohaapav** [comment]
@peacememories Problem is probably caused by ssl termination. Anyway it's hard for me to say what is the root cause as this require some deeper debugging. If you can somehow provide your registry credentials i can take a look into issue ..

**Comment by peacememories** [comment]
Update:
For one, public gitlab seems to be exhibiting the same behaviour:
* Using a deploy token with `read_registry` permissions results in `Repositories fetching failed. 401 Unauthorized`
* Using a personal access token with `read_registry` permissions results in `Repositories fetching failed. insufficient_scope`
* Using a personal access token with full permissions seems to work
* Using a deploy token with all permissions still results in the 401

So it seems I *have* to use a personal access token, and it needs more permissions than to just read the registry? This seems odd, especially since logging into the registry with my deploy token, as well as with a restricted personal access token seems to work just fine.

**Comment by nohaapav** [comment]
@peacememories I've just link my gitlab acc and deployed service without any issue. First of all you have mentioned `read_registry` scope. We explicitly mentioned that `API` scope must be used in wizard. See:

<img width="1097" alt="Screen Shot 2020-01-30 at 1 02 26 PM" src="https://user-images.githubusercontent.com/4179104/73448349-ef5d1e00-4360-11ea-92df-9b2f6dc30f90.png">

**Comment by peacememories** [comment]
True, I'm sorry I've missed that. Why is this scope needed though? Shouldn't registry read permissions be enough?
Also using a `Registry v2` connection doesn't work either, as mentioned above, even though logging in via `docker login` seems to work. I think gitlab uses registry v2 by now? At least it seems that way.

**Comment by peacememories** [comment]
Being able to use deploy tokens would be very useful to me because we have many projects under an organization that need to be deployed to this swarm, and it might get awkward if this all runs over a single user. Creating a dummy user is also difficult for us because of restrictions by the IT department (one user per employee, etc.)

**Comment by nohaapav** [comment]
@peacememories You need `API` scope because of how gitlab works. You can't list registry projects via `_catalog` api unless you are admin. So we have to check all the projects by gitlab API instead. See my comment: https://github.com/swarmpit/swarmpit/issues/296#issuecomment-454058881

Registry v2 works if you have e.g. REGISTRY_AUTH_HTPASSWD_REALM in place. But i assume that gitlab do not configure such auth by default because of security policy.

**Comment by shakeelosmani** [comment]
For me with all the permissions set using the personal access token, swarmpit sees the registry and creates the service but then it fails with no such images. Any idea what could be wrong. I can tell you the image exists in gitlab

![Screen Shot 2020-05-03 at 3 42 54 PM](https://user-images.githubusercontent.com/9120484/80924042-ebbca700-8d54-11ea-89aa-840831ce88a8.png)

**Comment by nohaapav** [comment]
@shakeelosmani Are you sure that you have enough space on all VM disks ? Sometimes docker reject images if there is not enough available space to pull .. Btw did you link registry via gitlab registry api ?

**Comment by shakeelosmani** [comment]
@nohaapav yes I verified I have more than enough space on each instance. Also I connected the registry via the swarmpit UI

**Comment by nohaapav** [comment]
@shakeelosmani i mean did you use `registry v2` option or `gitlab registry` option ?

**Comment by shakeelosmani** [comment]
gitlab registry

**Comment by shakeelosmani** [comment]
@nohaapav well it turned out to be a insecure registry issue. The error message could have been better by bubbling up the original docker pull error that would say something like https client trying to pull http resource, not a big deal though!

**Comment by nohaapav** [comment]
@shakeelosmani Well this is actually error we get from docker dem. It's not generated on Swarmpit side. That's why i asked initially if you have enough space on disk 'cause docker returns pretty much the same error if you haven't.
