### ISSUE TITLE
Can't see the network details

### ISSUE THREAD

**Issue by V-Smeets** [swarmpit/swarmpit#297]
**Description**

swarmpit version: 1.6-bf45a6a
Docker version: 18.09.1
Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit), Firefox gives the same error.

I can't see the details of any network. The browser shows a complete blank screen. The console of the browser shows the java script error: Invalid timezone format

**Steps to reproduce the issue:**
1. Open the swarmpit app in a browser.
2. Open "Networks"
3. Select/Open any network (e.g. "bridge")

**What happens:**
The browser shows a complete empty screen.
The console window of the browser reports a java script error.

**What should happen:**
The details of the network should be shown.

**Additional information (e.g. docker version, cluster setup,...):**
The log file of the browser shows the full error message.
[network-bridge.log](https://github.com/swarmpit/swarmpit/files/2753045/network-bridge.log)

The har file shows the relevant HTTP-packages that were requested from the server.
[network-bridge.har.txt](https://github.com/swarmpit/swarmpit/files/2753047/network-bridge.har.txt)

In line 117 of the har file, you see the json text that the server sends. It contains a date field with the value "2019-01-13T10:27:29.390395564+01:00". The mili/micro/nano seconds part is not accepted.

Regards,
Vincent

**Comment by nohaapav** [comment]
@V-Smeets Hi Vincent, thx for reporting .. 1.6 is still in progress.
We moved to brand new ui and now we're fixing the issues related ;)
