### ISSUE TITLE
Why does Swarmpit take up so much memory?

### ISSUE THREAD

**Issue by laurenskling** [swarmpit/swarmpit#298]
Running many containers need a lot of memory, memory costs money. So i'm very economic about my memory.
why is swarmpit taking up so much memory? :O
any idea's how to reduce the used memory?

swarmpit_app.1 | swarmpit/swarmpit:1.5 | xxxxxx | 0.13% | 65.57% | 704.1MB

**Comment by lumir-mrkva** [comment]
swarmpit is running in JVM and that can easily lot of memory. you can try to reduce its usage by imposing a memory limit on the swarmpit service. there is [1GB set as default,](https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml#L18) but you maybe should be able to push it as low as 300 MB

**Comment by lumir-mrkva** [comment]
#299 should also help with memory usage
