### ISSUE TITLE
Node health check?

### ISSUE THREAD

**Issue by Kenits** [swarmpit/swarmpit#300]
**Description**
Sorry for my  bad English
Is it normal that a non-working node shows its state as ram and disk?
II think it's a UI bug.

**Steps to reproduce the issue:**
1. Start swarmpit like this.
```
git clone https://github.com/swarmpit/swarmpit
docker stack deploy -c swarmpit/docker-compose.yml swarmpit
```
2. Get some load non-master node
3. Power off worker-node

**What happens:**

Ram and disk status are frozen and do not change

**What should happen:**

All status bars have dropped to zero and become inactive.

**Additional information (e.g. docker version, cluster setup,...):**
Docker:
- Docker version 18.09.1, build 4c52b90

Swarmpit:
- image swarmpit:latest
- version 1.6  
- CONTAINER ID 5a9ec24285ce

Screenshot how it looks:
![pic](https://user-images.githubusercontent.com/26982430/51343349-4ae6a180-1aa7-11e9-959c-507099d1a87c.PNG)

**Comment by lumir-mrkva** [comment]
i guess, we just show the last data received, there is no timeout

**Comment by lumir-mrkva** [comment]
we'll fix it with planned stats improvements

**Comment by Kenits** [comment]
It's good
