### ISSUE TITLE
[1.6] New UI feedback

### ISSUE THREAD

**Issue by abellion** [swarmpit/swarmpit#302]
Hi there,

Thanks for the great work, as always. Today I tried the upcoming 1.6 release and it looks gorgeous ! I've deployed a few services as well as some stacks, nodes, etc to try the UI out. I took some notes while testing it and here is my feedback : 

### Login page

On my 13" screen, the `Username` and `Password` fields are at the bottom of the screen due to the large Swarmpit logo. I think having the fields more at the top would ease the usage.

![image](https://user-images.githubusercontent.com/9916488/51427985-6fa15d00-1bfe-11e9-8905-d7c2edd87607.png)

### Clickable part

Some clickable parts are not real navigation links and thus it prevents the user from opening something as a new tab, copy the link, etc.

This issue appears in all of the left navigation links and in all of the tables rows on the different swarm's components pages (Stacks, Services, Tasks, Networks, Volumes, Secrets, Configs and Users).

Having real links would really be useful when we want to quickly compare two things by opening them as new tabs, for example two services, two volumes, etc...

### Forms

I saw that some forms don't take 100% width. This concerns :

- `stacks/create` page,
- `networks/create` page,
- `volumes/create` page,
- `secrets/create` page,
- `configs/create` page,
- `users/create` page,
- `registries/create` page,
- `services/create/wizard/config?repository=XXX` page.

When creating one of those having the form 100% width would ease copy pasting things as well as visualising the form's content.

![image](https://user-images.githubusercontent.com/9916488/51428027-0a9a3700-1bff-11e9-8afa-1cc6eccf7415.png)

### Swarm's components

The swarm's components pages (`nodes/XX`, `services/XX`, `stacks/XX`, `tasks/XXX`, `networks/XXX`, etc...) are divided into "cards" (one for the networks, one for the tasks, etc...).

On my screen, these cards appear both on the left and on the right which makes inspecting a component's content a bit destabilising. This makes my eyes going from right to left and vice versa and that is not confortable.

Maybe forcing every card to be 100% width would be better ? I tried as a mobile viewport and it appears much more readable.

![image](https://user-images.githubusercontent.com/9916488/51428037-3d442f80-1bff-11e9-8803-a985634614ec.png)

**Comment by lumir-mrkva** [comment]
@abellion thank you very much for feedback ❤️ 

we will be working more on the component layout in future, so we'll appreciate your feedback. this setup allows us to add more data to page easily and to be responsive for mobile devices at the same time.

**Comment by nohaapav** [comment]
@lumir-mrkva Maybe we can introduce layout switch .. It's super easy to do and everybody is happy :)

**Comment by abellion** [comment]
Hey @nohaapav, I'm on a 13" screen. I can see the button hovering :

![image](https://user-images.githubusercontent.com/9916488/51431603-80b49300-1c2b-11e9-8122-bf3aaf0b90b9.png)

**Comment by abellion** [comment]
@nohaapav @lumir-mrkva A layout switch to make the tiles 100% width would do it ! 

For the record, I found some screenshots of the former Docker Cloud UI, if it can help improving the layout.

__Node Details__ : 

![Node Details](https://raw.githubusercontent.com/docker/docker.github.io/a30770ed50975dc5655b2b9c72666b2b051cf5a3/docker-cloud/apps/images/lbd-four-nodes.png)

__Service Details__ :

![Service Details](https://raw.githubusercontent.com/docker/docker.github.io/a30770ed50975dc5655b2b9c72666b2b051cf5a3/docker-cloud/apps/images/lbd-containers-start.png)

__Service Edit__ :

![Service Edit](https://raw.githubusercontent.com/docker/docker.github.io/a30770ed50975dc5655b2b9c72666b2b051cf5a3/docker-cloud/apps/images/lbd-web-conf.png)

__Stack Edit__ :

![Stack Edit](https://raw.githubusercontent.com/docker/docker.github.io/a30770ed50975dc5655b2b9c72666b2b051cf5a3/docker-cloud/apps/images/stack-create.png)

**Comment by nohaapav** [comment]
@abellion Will check that screen .. Strange .. i can see the button on every device so far .. 

Ad layout) One of the reason why we started swarmpit was that we didn't like UIs out there :)
So far no one was complaining about grid view, so let's wait for more feedback. We actually like
it, having no difficulties to read the data. Once 1.6 is released we're having session with our UX
team so we can discuss the possibilities there.

**Comment by abellion** [comment]
@nohaapav sounds good !

I'm on Google Chrome ;)

**Comment by nohaapav** [comment]
@hickscorp Looks like css is not loaded. Some more details would be nice. Try to open app in incognito window and make sure there is no ad block ..

**Comment by laurenskling** [comment]
Just wanted to show my love for the new UI here. Thanks for putting all the effort in this. Looks awesome 🌈
