### ISSUE TITLE
Wrong port deletion

### ISSUE THREAD

**Issue by nitrix** [swarmpit/swarmpit#307]
BUG REPORT
---------------------------------------------------

**Description**

Deleting a port on the service creation page (likely the edition page too) always deletes the last port.

**Steps to reproduce the issue:**
1. Click Services
2. Click New Service
3. Find an image that has multiple exposed ports.
4. Click on it.
5. Pick "latest" for the tag to trigger a page update with the exposed ports.
6. Scroll to the ports section and delete one of them.

**What happens:**

The last port in the list gets removed.

**What should happen:**

The port that was clicked is the one that should be removed.

**Additional information (e.g. docker version, cluster setup,...):**

Version 1.6 of the new "mobile UI".

**Comment by nohaapav** [comment]
Thanks for reporting .. Looks like items are deleted ok just wrong rendering on fe for this type of edit table (react-keys)

**Comment by nohaapav** [comment]
@nitrix I pushed the fix to 1.6 .. Could you just redeploy swarmpit_app service to see how it works for you now. Thanks.

**Comment by nitrix** [comment]
@nohaapav Confirmed, your commit fixed the problem!

I really appreciate the fast reply, thanks (:
