### ISSUE TITLE
Can't see node live node metrics for newly joined node in the swarm

### ISSUE THREAD

**Issue by angheladrianclaudiu** [swarmpit/swarmpit#310]
**Description**

Node metrics are not shown in the nodes view.
**Steps to reproduce the issue:**
1. Select Nodes from the menu list
2. Check the node info

**What happens:**
When checking the node information, node metrics are not shown even though it correctly shows the number of cores and the amount of RAM.

**What should happen:**
It should show the live node metrics

**Additional information:**
Whis is the log for the agent on this node:
```
docker logs 5008ff70b3c7
2019/02/13 10:20:25 INFO: Waiting for Swarmpit...
```
docker 18.09.2
![image](https://user-images.githubusercontent.com/3780416/52705387-7025dd00-2f8b-11e9-87df-6014cc927ccc.png)

**Comment by angheladrianclaudiu** [comment]
It seems that it worked after I redeployed the stack. Is there a way for doing this without redeploying the stack?

**Comment by farodin91** [comment]
We had the same problem and we needed to add two env variables for the agent:
      - EVENT_ENDPOINT=http://swarmpit:8080/events
      - HEALTH_CHECK_ENDPOINT=http://swarmpit:8080/version

It would be helpful in agent to add some more information like the checked endpoint.

**Comment by lumir-mrkva** [comment]
interesting, this should work automatically as the agent is global service and as long that is in same network as swarmpit and same stack default event endpoint (http://app:8080) should work. this looks like some sort of network problem, what cloud provider are you using?

**Comment by nohaapav** [comment]
Also statistics are not shown immediately .. You need to wait till agent fetch first batch :) like 60 sec is default ..

**Comment by nohaapav** [comment]
Possible duplicate https://github.com/swarmpit/swarmpit/issues/272
