### ISSUE TITLE
Empty docker content digest causing service creation/update impossible

### ISSUE THREAD

**Issue by unglaublicherdude** [swarmpit/swarmpit#312]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

We deploy stacks on docker swarm via `docker stack deploy` with a "start" setting. For example a service is replicated 5 times. These settings can be adjusted via the UI but the changes cannot be applied.

**Steps to reproduce the issue:**
1. Deploy a stack with a service named whoami that is replicated with 5 replicas.
2. Login as admin into swarmpit
3. Search this service via swarmpit (it doesn't matter if you go through the stack or the services directly) and click on it.
4. Click on 'edit service'
5. Set 'Replicas' to 4
6. Click on 'Save' at the bottom of the page.

**What happens:**

* An error shows up 'Service update failed. authentication required'.
* The service change is not applied.

**What should happen:**

The service change should be applied and the error should be a confirmation. 

**Additional information (e.g. docker version, cluster setup,...):**

You can also inspect that via the browser developer-tools. 
Just redo all the steps.

A request is send to the correct hostname to the path `/api/services/id`. 
The status code of the request is 401 and the content is:
```json
{"error":"authentication required"}
```

We also looked into the docker-logs but there is no indication of an error or what happened.

**Comment by lumir-mrkva** [comment]
@unglaublicherdude this error refers to authentification with the registry of that image, please double check that you have added the registry to swarmpit correctly

**Comment by unglaublicherdude** [comment]
@lumir-mrkva we have set up a custom registry (Artifactory with public read), without any form of authentication

**Comment by nohaapav** [comment]
@unglaublicherdude Could you provide registry details (JSON when you review registry info) ?

**Comment by unglaublicherdude** [comment]
@nohaapav here you go
```json
{"_id":"7a89663b7aa31b2c93af038ec8001e5a","_rev":"1-30625c4589d63d67cb9916adf7250b70","name":"Artifactory","username":"","public":true,"type":"registry","withAuth":false,"url":"https://{MUNCHED}:6555","owner":"admin"}
```

@lumir-mrkva 
But when you say it is related to the registry. We use a complete inhouse system. With an own inhouse CA. Should we install that CA certificate into the swarmpit-container?

**Comment by unglaublicherdude** [comment]
Swarmpit does resolve the image tags - when on the edit-page of a service you can actually select the tags, that are in the registry - via the registry which it doesn't when no registry is configured. So I guess the general connection to the registry works.

**Comment by nohaapav** [comment]
@unglaublicherdude Could you provide details how registry was deployed ? (stackfile, cmd)
I'm trying to reproduce your issue with no luck so far ..

**Comment by unglaublicherdude** [comment]
Hi, the registry is a hard installed Artifactory, done by the documentation of JFROG. So it does not run in our swarm and does not have a stackfile.

**Comment by nohaapav** [comment]
That might be issue .. Standard v2 registry works just ok without credentials, maybe JFROG is doing some magic on top of the registry.  Need to check how the setup is done there.

**Comment by cadavre** [comment]
Solved by adding a Registry that matches image in edited service.

But there's another error keeping service from being updated in edit mode:
```
Service update failed. rpc error: code = InvalidArgument desc = ContainerSpec: "mycustomrepo.com/my-image:latest@" is not a valid repository/tag
```

Looks like the format is wrong and no digest is filled. `my-image:latest@` doesn't look like a valid repo image/tag.

**Comment by nohaapav** [comment]
@cadavre Sorry for late reply, pretty busy these days. Yes registry url have to match image name. Basically image is the only identifier based on which we lookup for linked registry. 

From error above it looks like image digest returned from registry for given repository tag has empty value. Not sure if this is valid behaviour.

Could you try this:

```
GET http://{your_registry_url}/{repository_name}/manifests/{repository_tag}

Authorization: {token}
Accept: application/vnd.docker.distribution.manifest.v2+json
```

Wondering about the result. Thanks you.

**Comment by nohaapav** [comment]
Found the problem. It looks like `docker-content-digest` is not mandatory response header attribute so nil is returned in this case.

Resp. Headers:
```
{"Content-Type" "application/vnd.docker.distribution.manifest.v2+json",
 "Date" "Fri, 15 Mar 2019 14:27:38 GMT",
 "Docker-Distribution-Api-Version" "registry/2.0",
 "Content-Length" "528",
 "Connection" "Close"}
```
Happens to me for Amazon ECR ..

**Comment by nohaapav** [comment]
Found it .. Looks like we need to use `HEAD` instead of `GET` method to have digest in response headers. Strange, doc says that we can choose any of these and looks like that for some v2 registries `GET` is working just fine..

**Comment by cadavre** [comment]
Sorry for lack of response, also had lack of time. Thank you for debugging and finding the problem. Will ease up much working with Swarmpit. GJ!
