### ISSUE TITLE
Volumes are not shown (request timeout)

### ISSUE THREAD

**Issue by rodneygp** [swarmpit/swarmpit#314]
**Description**

Unfortunately, we see no volumes in corresponding page. Attempt to open it results in "Request timeout" message. I believe, the issue has it's roots in the fact, that we have a lot of volumes and many of them reside on ceph/rbd. Obviously, it takes quite some time to list them (also on docker cli it takes around 22 seconds). It would be cool to have possibility to set the volumes ls timeout.

**Steps to reproduce the issue:**
1. Organize in some way that your docker volume ls takes over 22 seconds. How? I installed two instances of rexray/rbd drivers with different default pools. This helped.
2. Create 40+ rbd images.
3. Open swarmpit and try to open Volumes page.

**What happens:**
I see "Request timeout" message.

**What should happen:**
I should see list of volumes (I suppose),

**Additional information (e.g. docker version, cluster setup,...):**
Docker 18.09.0, 6 nodes + ceph cluster with two pools. Each node has 2 rexray drivers (differently named and with different default pool).

**Comment by nohaapav** [comment]
Hi @rodneygp 

Currently timeout is hardcoded for 5 sec [see](https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/docker/engine/http.clj#L37)

We can introduce some env variable so you can change client timeout for docker sock communication.
