### ISSUE TITLE
standalone containers and also images on each node

### ISSUE THREAD

**Issue by marriamda** [swarmpit/swarmpit#315]
Does swarmpit monitor standalone containers and images on each node? I want to see the images, non-swarm containers existing on each swarm node and also the stopped but not removed containers. 
thanks

**Comment by rarous** [comment]
Swarmpit is Docker Swarm management Tool. It doesn't and will not support something else, for focus and simplicity reasons.

**Comment by marriamda** [comment]
Thanks . although it's better to know more about host and its load etc, it can have the feature to run exec on each container in the swarm. 
thanks for the reply

**Comment by nohaapav** [comment]
@marriamda Actually you can see host load in node section -> non-swarm containers are counted in report as well !!! Exec is on feature list, see https://github.com/swarmpit/swarmpit/issues/93
