### ISSUE TITLE
Remove Nodes

### ISSUE THREAD

**Issue by edward-of-clt** [swarmpit/swarmpit#316]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Admins should be able to remove nodes after draining them (or quite frankly forcefully remove a host).

**Description**

In the Docker CLI you can run `docker node rm <node_id>` or `docker node rm -f <node_id>`. Swarmpit should include such features to modify the nodes within the swarm.

**Comment by dedupely** [comment]
Thumbs up on this!!
