### ISSUE TITLE
Remove Volumes

### ISSUE THREAD

**Issue by FxIII** [swarmpit/swarmpit#317]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Long labeled volumes can not be removed through UI**

When a volume has a long label (tipically if its hash is used), the UI stretches and the trash button goes out of screen.
I resolved through browsers devs tools by altering the css of .Swarmpit-card-header-responsive-title:
```css
max-width: 16em;
text-overflow: ellipsis;
overflow: hidden; 
```

**Comment by nohaapav** [comment]
Could you elaborate more ? I see no issue with volume names.

<img width="382" alt="screen shot 2019-02-26 at 8 57 07 am" src="https://user-images.githubusercontent.com/4179104/53396393-9d6b8580-39a4-11e9-836e-b69d656d9a33.png">
<img width="768" alt="screen shot 2019-02-26 at 8 57 16 am" src="https://user-images.githubusercontent.com/4179104/53396394-9d6b8580-39a4-11e9-9ddd-016d2e431b74.png">
<img width="1030" alt="screen shot 2019-02-26 at 8 57 25 am" src="https://user-images.githubusercontent.com/4179104/53396396-9d6b8580-39a4-11e9-8e28-56c9e4655ac0.png">
<img width="1443" alt="screen shot 2019-02-26 at 8 57 34 am" src="https://user-images.githubusercontent.com/4179104/53396398-9d6b8580-39a4-11e9-85cc-67d28bf493e5.png">

**Comment by FxIII** [comment]
On my mac it seams to affect only firefox [65.0.1 (64 bit)]
<img width="1677" alt="schermata 2019-02-26 alle 09 20 04" src="https://user-images.githubusercontent.com/1052649/53397600-d22d0c00-39a7-11e9-808e-439dcd5b7586.png">

**Comment by nohaapav** [comment]
I see .. Looks like this is FF & IE issue. These browsers not supporting `break-word` just `break-all`.
