### ISSUE TITLE
Removing any label from a service removes the last label instead

### ISSUE THREAD

**Issue by letscodehu** [swarmpit/swarmpit#320]
**Description**

When somebody intends to remove a label from a specific service, the UI reflects that he removes the last label instead. It might be a UI only glitch which is not reflected in the command when the change is submitted.

**Steps to reproduce the issue:**
1. Navigate into a service details page which has multiple labels assigned.
2. Click on the edit button under the labels section.
3. From the enumerated labels, click on the first label's delete button.
4. Observe the result.

**What happens:**
The last label disappears from the list.

**What should happen:**
The selected label should be removed from the list.

**Additional information (e.g. docker version, cluster setup,...):**
Dokcer 18.09.1 on both the manager and the worker.

**Comment by nohaapav** [comment]
@letscodehu What version of swarmpit are u using ? This should be already fixed ..

**Comment by letscodehu** [comment]
> @letscodehu What version of swarmpit are u using ? This should be already fixed by [cf29c82](https://github.com/swarmpit/swarmpit/commit/cf29c82bc4d1f62b207335c8910d88d75be8d1fd)

1.6, the latest stable release according to github. It was released 27 days ago. The commit you linked was done 25 days ago, so I doubt that it's in that release but it's already taken care of then.

**Comment by nohaapav** [comment]
Actually this commit has been cherry picked in 1.6 .. so please update redeploy swarmpit_app to fetch the latest stable image.

**Comment by letscodehu** [comment]
@nohaapav I pulled the latest image on the manager, removed the stack then run the install docker command. Even then I had to clear my browser cache to see the changes, but it's fixed now, thank you.

**Comment by nohaapav** [comment]
Redeploy swarmpit_app service from UI and clear browser cache should be enough :) But glad that it works.
