### ISSUE TITLE
Service detail menu is not entirely visible

### ISSUE THREAD

**Issue by martykan** [swarmpit/swarmpit#324]
There is a minor UI bug In the service view.
If the title of a service is longer, it pushes the menu items out of bounds.

[<img src="https://i.imgur.com/GDWhto8.png" width=400>](https://i.imgur.com/GDWhto8.png)

**Comment by nohaapav** [comment]
@martykan We need more details such browser, swarmpit version, screen resolution etc ..

**Comment by martykan** [comment]
Version is 1.6-5cb209c
You can replicate this by resizing the window to a narrower width, when it almost changes to the mobile UI.

**Comment by nohaapav** [comment]
@martykan You're using some old version regarding commit number `5cb209c `. This is fixed already. Please update to recent version or stable milestone 1.6.
