### ISSUE TITLE
Reverse proxy and Swarmpit

### ISSUE THREAD

**Issue by hpbieker** [swarmpit/swarmpit#326]
**Description**

In previous versions I was able to use Swarmpit behind a reverse proxy with an address such as http://somehost/swarmpit/, but with the latest version I am not able to do that because the urls for css and js points to the root directory.

It looks like this issue was introduced in https://github.com/swarmpit/swarmpit/commit/1ee0ca1261b9377ab563159cdde739fef908658a#diff-f64602509ae576a39f37077e2cf40627

**What happens:**
I get 404 because index.html assumes that css and js folders are located in the root folder.

**What should happen:**
It should use relative addresses or make it possible to specify a base address.

**Comment by rarous** [comment]
I'll create ENV property where you can set base address.

**Comment by rarous** [comment]
You can set `SWARMPIT_BASE_URL` env to overrride root path.

**Comment by robertofabrizi** [comment]
There is no docker image on dockerhub that already supports this right?

**Comment by nohaapav** [comment]
@rarous 🔝 Check it please

**Comment by nohaapav** [comment]
We need to probably prefix api's with base url as well.

**Comment by robertofabrizi** [comment]
There is still something strange going on, now it loads all files, but the page says that it can't find what I was looking for...

![image](https://user-images.githubusercontent.com/6720929/55287840-a342f500-53ae-11e9-9378-03f9d675204b.png)

**Comment by nohaapav** [comment]
@robertofabrizi Well PR is not merged yet as far as i can see

**Comment by robertofabrizi** [comment]
@nohaapav I used the docker image feature-base-url tag that should

**Comment by nohaapav** [comment]
@robertofabrizi Could you share visited url ? Interesting about the uri ..

**Comment by robertofabrizi** [comment]
@nohaapav Ofc.
This is the docker compose relevant bit:

>      swarmpit-app:
>       image: swarmpit/swarmpit:pr-337
>       environment:
>         SWARMPIT_DB: http://swarmpit-db:5984
>         SWARMPIT_BASE_URL: /swarmpit/

I visit this url: http://10.46.90.125:8383/swarmpit and I get the printscreens above

**Comment by nohaapav** [comment]
@robertofabrizi And if you go e.g. services ? [http://10.46.90.125:8383/swarmpit/services](http://10.46.90.125:8383/swarmpit/services) does it work ? 

There is actually no view on base path, we redirect user to stack view until proper dashboard is done. My point is maybe just initial redirect is broken ?

**Comment by robertofabrizi** [comment]
@nohaapav Sadly no they show the exact same page as above.

**Comment by nohaapav** [comment]
@rarous Check that please .. I have this feeling that prefixing frontend-path is not necessary to have
See https://github.com/swarmpit/swarmpit/commit/7def509c8e5d90ef27e5f9da775eb48dc1b4458e#diff-232834d2b9268736826a6a93fc0e5986R170

**Comment by s8sg** [comment]
I have the same problem.
My Nginx is configured as 
```conf
 # route platform admin portal request
 location ~ ^/platform/portal(.*)$ {
                set $upstream swarmpit:8080;
                proxy_pass http://$upstream$1;
 }
```
Docker compose is set as
```yaml
     # Swarm console
    swarmpit:
        image: swarmpit/swarmpit:latest
        environment:
            - SWARMPIT_DB=http://swarmpit-db:5984
            - SWARMPIT_BASE_URL=/platform/portal/
```

Although when I go to `http://localhost:8000/platform/portal`, I get the below page 
<img width="1274" alt="Screen Shot 2019-05-15 at 11 04 22 AM" src="https://user-images.githubusercontent.com/7374058/57743748-4ce10a00-7701-11e9-9cd0-8a99d1dc10c9.png">

**Comment by rarous** [comment]
Sorry guys I'm a bit busy.

**Comment by nohaapav** [comment]
I reverted the new pushy config to old bidi router so everything should work as in old 1.5 version

**Comment by lucaspouzac** [comment]
Hi, is it possible to configure swampit behind a reverse proxy with a context path ? 

It looks like a rollback was done on the commit. Thanks

```
  app:
    image: swarmpit/swarmpit:1.8
      labels:
        traefik.port: 8080
        traefik.frontend.rule: "Host:${DOMAIN};PathPrefixStrip:/swarmpit/"
```

**Comment by lucaspouzac** [comment]
Maybe, you need use x-forwarded-prefix header to add path-prefix ?

https://docs.traefik.io/v1.7/basics/#matchers

**Comment by nohaapav** [comment]
@lucaspouzac Sorry .. Will check the impl .. reverse proxy was working fine however we changed routing from bidi to reitit so it might be possible that something is not working fine ..
