### ISSUE TITLE
Cannot upgrade interface

### ISSUE THREAD

**Issue by zeg-io** [swarmpit/swarmpit#328]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

I had an older version of swarmpit installed.  (Blue interface) I am attempting to update it to the latest.  I installed using the install script, which worked.  But... I still have the blue interface rather than the purple one.  How do I ACTUALLY upgrade?

It lists the current version as `1.7-1603e3e` although the login and interface are all the old blue one.

**Comment by lumir-mrkva** [comment]
try to hard refresh page (shift refresh) or delete cache

**Comment by nohaapav** [comment]
@zeg-io Login is true the same because you didn't remove database volume first (clean installation).
