### ISSUE TITLE
network not appearing during service creation/edition

### ISSUE THREAD

**Issue by UnclePhil** [swarmpit/swarmpit#338]
hello,

When i'm creating a new service through the interface, i cannot bind it to any network.
there is no part of the edition form related to network 

* Configuration
Swarmpit 1.6 

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

![image](https://user-images.githubusercontent.com/471443/54931723-d7836500-4f19-11e9-9aa9-f471f463e118.png)

Best regards
Ph Koenig

**Comment by nohaapav** [comment]
Thanks for reporting Phil. Accidentally we removed this field during huge material refactoring. It's back now. Please fetch the latest release.
