### ISSUE TITLE
Button delete is out of the screen

### ISSUE THREAD

**Issue by sinacek** [swarmpit/swarmpit#339]
**What happens:**
For long name of volume is Delete button out of the screen

**What should happen:**
Shorten volume name or use z-index. 
![Volumes __ swarmpit](https://user-images.githubusercontent.com/1140123/55007340-8d64b700-4fdf-11e9-87e3-2ab9347e6542.jpg)

**Comment by nohaapav** [comment]
@sinacek You have probably some old version of swarmpit. This has been already fixed in recent version.

**Comment by nohaapav** [comment]
<img width="1679" alt="Screen Shot 2019-03-26 at 4 40 10 PM" src="https://user-images.githubusercontent.com/4179104/55011195-dae42280-4fe5-11e9-9730-fc52b7689d17.png">

**Comment by sinacek** [comment]
I have downloaded today 1.6. Ok nice, I'm looking forward for stable 1.7
