### ISSUE TITLE
Cannot add dockerhub registry

### ISSUE THREAD

**Issue by dmitrym0** [swarmpit/swarmpit#354]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

Attempting to add a Dockerhub registry.

**Steps to reproduce the issue:**
1. Install 1.7-00f00d7
2. Login into the interface
3. Click registry
4. Go through the registry process for dockerhub with known good credentials
5. Click "Finish"

**What happens:**

Error banner: "Dockerhub user cannot be added".

**What should happen:**

User should be added.

**Additional information (e.g. docker version, cluster setup,...):**

Docker Version:	17.12.1-ce
2 nodes in a cluster.

**Comment by nohaapav** [comment]
I've tried with 4 different accounts and works ok. Unless you provide more details there is nothing we can do about that.

**Comment by dmitrym0** [comment]
Are there logs somewhere?

**Comment by nohaapav** [comment]
Not really .. it's pretty strange that there is no Reason message linked. Could you try the following:

```
curl -X POST \
  https://hub.docker.com/v2/users/login \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"username": "${HUB_USERNAME}",
	"password": "${HUB_PASSWORD}"
}'
```
Are you able to get the token ?

**Comment by dmitrym0** [comment]
I can get the token, yes. Very strange ;(

![2019-05-07 at 7 59 AM](https://user-images.githubusercontent.com/707020/57310473-bc6e4e00-709e-11e9-9e3a-ecbca4f05d1c.png)

![2019-05-07 at 8 02 AM](https://user-images.githubusercontent.com/707020/57310465-b8dac700-709e-11e9-883c-372344b9e63a.png)

**Comment by nohaapav** [comment]
@dmitrym0 Btw do you have access to internet from cluster running Swarmpit as i can't see loaded avatar ..

**Comment by dmitrym0** [comment]
@nohaapav the terminal output is from the same machine where swarmpit is running. 

No idea why avatar isn’t showing I noticed that too.

**Comment by nohaapav** [comment]
@dmitrym0 
1) Can you `Inspect -> Network` to see whether all swarmpit related queries on F5 are OK ?
2) Please check if you have same error with PWD: https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/swarmpit/swarmpit/master/docker-compose.yml

**Comment by dmitrym0** [comment]
@nohaapav I couldn't get PWD working, but I spun up a local swarm instance. First thing I noticed is that the selection dialog for "Link image registry" now contains 5 items (Dockerhub, Registry v2, Amazon ECR etc). This is more than when I tested it last time. When I went to my remote instance, it now showed 5 items too! And the link worked. Where would 3 extra items come from?

**Comment by nohaapav** [comment]
@dmitrym0 Well in current master you have 5 providers .. If you see only 2 that means you need to clear your browser cache .. Probably frontend is being cached in your case (old one is used) and that means FE is calling invalid old BE api which result in given error.

**Comment by dmitrym0** [comment]
That's gotta be it!
