### ISSUE TITLE
Stacks added missing after Reboot

### ISSUE THREAD

**Issue by ClaudioBsh** [swarmpit/swarmpit#355]
My running Swarmpit is working within Docker-Swarm together with Traefik and an own private Registry started with scriptfile on commandline.

After start i do login to Swarmpit. 

I add a new stack using Swarmpit: "+New Stack"

The Service (whoami) is starting and works.

Then i stop the swarm (docker swarm leave --force), after it is stopped i start my runscript again and this brings swarmpit, traefik and my own registry up.

**
My Questions:

But i am wondering, the stack with service whoami i did add before is not longer available! Are Stacks created with Swarmpit not saved as other settings?

What does Swarmpit save and what does Swarmpit  not save? Is there a dcoumentation available?
**

Thanks in advance for support:-)

-------------------------------------------

Details of my runscript:
`#! /usr/bin/bash`
`docker swarm init`
`docker network create --attachable -d overlay traefik-frontends-network`
`docker stack deploy -c docker-compose.traefik.yml traefik`
`docker stack deploy -c docker-compose.registry.yml registry`
`export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')`
`docker node update --label-add swarmpit.db-data=true $NODE_ID`
`docker stack deploy -c docker-compose.swarmpit.yml swarmpit`

Details of my docker-compose,swarmpit.yml:
version: '3.3'

networks:
  traefik-frontends-network:
    external: true
  swarmpit-network:
    driver: overlay
    attachable: true

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - traefik-frontends-network
      - swarmpit-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.docker.network=traefik-frontends-network
      - traefik.port=888
      - traefik.enable=true
      - traefik.tags=traefik-frontends-network

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - swarmpit-network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit-network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

volumes:
  db-data:
    driver: local

**Comment by nohaapav** [comment]
Swarmpit does generate stacks view from current engine state. If service is no longer available of course you can't see service in compose. To check what was the last known state you need to choose
`last deployed`  compose source instead of `current engine state`
