### ISSUE TITLE
service details with volume mount

### ISSUE THREAD

**Issue by pbe-axelor** [swarmpit/swarmpit#356]
**Description**

When create a docker service with a volume mount, the service details page display nothing and result in a blank page

**Steps to reproduce the issue:**
1. Create a service with a volume mount : 
```
docker service create --name helloworld --mount type=volume,volume-driver=local,target=/app/data,volume-opt=type=none,volume-opt=device=/data,volume-opt=o=bind alpine ping docker.com
```
2. Go to the swarmpit service details page : `localhost:888/services/helloworld`

**What happens:**
The service details page display nothing and result in a blank page
Error in console : 
```
Ck
columnNumber: undefined
data: k {meta: null, I: 0, B: Array(0), F: -15128758, o: 16647951, …}
description: undefined
fileName: undefined
lineNumber: undefined
message: "Cannot form URI without a value given for :name parameter"
name: "Error"
number: undefined
sf: null
stack: "Error: Cannot form URI without a value given for :name parameter"
```

**What should happen:**
See service details

**Additional information (e.g. docker version, cluster setup,...):**
Docker version 18.09.6, build 481bc77
Swarmpit 1.7-00f00d7

Regards

**Comment by RemiBou** [comment]
I got this problem as well

**Comment by nohaapav** [comment]
Looks like missing `Source` is causing the issue .. We're using source to generate link to volume 
resource and as value is nil link happens to be invalid

**Comment by RemiBou** [comment]
I can confirm that adding an explicit source path to a volume fixes the UI

**Comment by RemiBou** [comment]
Fixed it by adding a named volume

**Comment by pbe-axelor** [comment]
Yes, while inspecting the service, `Source` is missing. 
Adding `source=testvolume` to the `--mount` flag fix the issue.

It seems that `source` can be omitted ([docker docs](https://docs.docker.com/storage/volumes/)) : 

> The source of the mount. For named volumes, this is the name of the volume. For anonymous volumes, this field is omitted. May be specified as source or src.
