### ISSUE TITLE
Tasks "View Logs" button is greyed out

### ISSUE THREAD

**Issue by amitm02** [swarmpit/swarmpit#357]
I'm using version 1.7-e22a62d.
The "View Logs" is greyed out for all tasks (in all services/stacks).
See attached image.

<img width="520" alt="Screen Shot 2019-05-27 at 17 04 14" src="https://user-images.githubusercontent.com/1888927/58425058-86baf480-80a1-11e9-966d-bf3f9ee1295b.png">

**Comment by nohaapav** [comment]
@amitm02 What logdriver are u using ? view log works just for `json-file` and `journalId`

**Comment by amitm02** [comment]
I haven't specified any log driver. I assume it uses the default (json-file)
I worth mentioning, the view logs worked at 1.6

**Comment by nohaapav** [comment]
@amitm02 well you can see in service view what driver is used. In 1.6 view log button was enabled for all drivers which was wrong.

**Comment by amitm02** [comment]
@nohaapav, it seems the log driver is json-file. but the file is still greyed out.

<img width="386" alt="Screen Shot 2019-05-27 at 21 39 58" src="https://user-images.githubusercontent.com/1888927/58435208-06f45080-80c8-11e9-8be3-47f699d1681b.png">

**Comment by amitm02** [comment]
@nohaapav, after some more research, this is what i've found.
When running the stack locally on my laptop, the view logs seems to work file.
When running the stack on docker-machine, this is when the "view logs" buttons get greyed out.
Any ideas?

**Comment by nohaapav** [comment]
@amitm02 Could you check if given task returns valid logdriver ?

```
curl --unix-socket /var/run/docker.sock 'http:/v1.30/tasks/{id}' | jq '.Spec.LogDriver'
```

**Comment by amitm02** [comment]
curl --unix-socket /var/run/docker.sock 'http:/v1.30/tasks/h7zu1j9r1d9w6yylo2mjvfu5f'| jq '.Spec.LogDriver'
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1803  100  1803    0     0   428k      0 --:--:-- --:--:-- --:--:--  440k
null
```

curl --unix-socket /var/run/docker.sock 'http:/v1.30/tasks/h7zu1j9r1d9w6yylo2mjvfu5f'

`{"ID":"h7zu1j9r1d9w6yylo2mjvfu5f","Version":{"Index":191794},"CreatedAt":"2019-05-29T06:03:59.6255935Z","UpdatedAt":"2019-05-29T06:04:01.9399554Z","Labels":{},"Spec":{"ContainerSpec":{"Image":"couchdb:2.3.0@sha256:8529c4972c0269f6134c467049010dcf38a8b1b89d35d984118ead560da8639b","Labels":{"com.docker.stack.namespace":"swarmpit"},"Privileges":{"CredentialSpec":null,"SELinuxContext":null},"Mounts":[{"Type":"volume","Source":"swarmpit_db-data","Target":"/opt/couchdb/data","VolumeOptions":{"Labels":{"com.docker.stack.namespace":"swarmpit"},"DriverConfig":{"Name":"local"}}}],"Isolation":"default"},"Resources":{"Limits":{"NanoCPUs":300000000,"MemoryBytes":536870912},"Reservations":{"NanoCPUs":150000000,"MemoryBytes":268435456}},"Placement":{"Platforms":[{"Architecture":"amd64","OS":"linux"}]},"Networks":[{"Target":"q98i70rmbmeqt6m980dewjo85","Aliases":["db"]}],"ForceUpdate":0},"ServiceID":"yzfdwitzbdzm7lw9066xtxiqw","Slot":1,"NodeID":"vbe6xo4i0cnd6u40pp17il5ll","Status":{"Timestamp":"2019-05-29T06:04:01.86376Z","State":"running","Message":"started","ContainerStatus":{"ContainerID":"337c00a0f2d5f5030aaa352609cdb57a095d1c8bb8599c607a788fbccd1b241d","PID":91740,"ExitCode":0},"PortStatus":{}},"DesiredState":"running","NetworksAttachments":[{"Network":{"ID":"q98i70rmbmeqt6m980dewjo85","Version":{"Index":191785},"CreatedAt":"2019-05-29T06:03:56.7805642Z","UpdatedAt":"2019-05-29T06:03:56.7826869Z","Spec":{"Name":"swarmpit_net","Labels":{"com.docker.stack.namespace":"swarmpit"},"DriverConfiguration":{"Name":"overlay"},"Attachable":true,"Scope":"swarm"},"DriverState":{"Name":"overlay","Options":{"com.docker.network.driver.overlay.vxlanid_list":"4175"}},"IPAMOptions":{"Driver":{"Name":"default"},"Configs":[{"Subnet":"10.0.78.0/24","Gateway":"10.0.78.1"}]}},"Addresses":["10.0.78.3/24"]}]}
`

**Comment by nohaapav** [comment]
@amitm02 That is my point. Default should be taken from engine. 

```
curl --unix-socket /var/run/docker.sock 'http:/v1.30/info' | jq '.LoggingDriver'
```

This is how it is done for service API. I'll add support for task api as well.

**Comment by nohaapav** [comment]
Should be ok now.

**Comment by amitm02** [comment]
bug still exists on 1.7
I get "Log is empty in this service" for any task log.
1.6 works fine.

**Comment by nohaapav** [comment]
Cleanup cache, FE is being cached probably .. no such message "Log is empty in this service"
exist in 1.7

**Comment by amitm02** [comment]
using docker hub pull, 
swarmpit/swarmpit:1.7 - bug exists
swarmpit/swarmpit:latest - bug fixed

**Comment by nohaapav** [comment]
Refresh your cache!

It's not possible to see message "Log is empty in this service" as it was removed in this commit:

https://github.com/swarmpit/swarmpit/commit/78d2db896656e8db8c8a73fcabca1cfc732bc5e7#diff-d829121e5df958fafa4c76f73033e68aL133

which was way sooner than official 1.7 release

**Comment by amitm02** [comment]
After browser cache refresh, getting "No logs for given period." for all services.

**Comment by nohaapav** [comment]
Are you sure you selected correct time period ? By default swarmpit shows logs for last 15 minutes .. See:

<img width="1473" alt="Screen Shot 2019-07-14 at 11 05 40 AM" src="https://user-images.githubusercontent.com/4179104/61181483-895cb380-a627-11e9-92cc-d03eee3a5a99.png">

<img width="1476" alt="Screen Shot 2019-07-14 at 11 05 51 AM" src="https://user-images.githubusercontent.com/4179104/61181482-895cb380-a627-11e9-8044-f5b09aeb5bad.png">

<img width="1472" alt="Screen Shot 2019-07-14 at 11 06 01 AM" src="https://user-images.githubusercontent.com/4179104/61181481-895cb380-a627-11e9-9133-757faa8ae843.png">

**Comment by amitm02** [comment]
Yes. I'be also tested it for "All"

**Comment by nohaapav** [comment]
@amitm02 Send me please your stack configuration. And version of UI

**Comment by amitm02** [comment]
What do you mean by stack configuration? I'm using the docker compose file supplied by swarmpit github

**Comment by nohaapav** [comment]
I want to make sure everything is configured correctly on your side. I'm interested mainly about agent service from stackfile & revision of UI ..

**Comment by amitm02** [comment]
FOUND  THE ISSUE!!
agent service in the docker was missing:
```
labels:
        swarmpit.agent: 'true'
```
after adding it, all seems to work

**Comment by nohaapav** [comment]
Good to hear. I have added fallback to service API if this label is missing in 1.8 but preferably agent and container api should be used.
