### ISSUE TITLE
Support for Custom v2 Registries

### ISSUE THREAD

**Issue by Jaben** [swarmpit/swarmpit#358]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Please add support for "custom" registries like ProGet. It's very similar to adding "Registry v2" except nothing gets appended to the registry url (e.g. /v2).

Thanks.

**Comment by claflico** [comment]
Would this be what's preventing me from being able to add an Artifactory server (with authentication) as a registry? I'm able to login and pull images via command line (docker login, docker pull) but when I try to add the registry via swarmpit I get the error message "Registry creation failed. Forbidden"

**Comment by nohaapav** [comment]
@claflico artifactory server is not the same as registry itself so i guess yes

**Comment by nohaapav** [comment]
@Jaben Ready in master. If you wish custom API just select the `custom API` checkbox and specify basic url. In your just simply checkbox selection should be fine.

**Comment by shakeelosmani** [comment]
@nohaapav I am having the same issue. I have a artifactory server also nginx as reverse proxy in front I can login fine from command line. But using the same repository url and the same credentials I tried all the options like toggling the custom API on off, nothing worked. Any idea?
