### ISSUE TITLE
Upgrading to from 1.6 to 1.7 broke service logs completely

### ISSUE THREAD

**Issue by atmosx** [swarmpit/swarmpit#365]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

After upgrading to 1.7 and agent 2.1, I cannot add registries to swarmpit. Additionally, I don't see logs for any service, while logs are available from the CLI. I'm not sure if that's the problem, but I use the exact same backend couchDB I just upgraded swarmpit and the agent.

The agent v2.1 is deployed with the following env variables:

```
DOCKER_API_VERSION=1.39
EVENT_ENDPOINT=http://swarmpit:8080/events
HEALTH_CHECK_ENDPOINT=http://swarmpit:8080/version
```

Swarmpit v1.7 is deployed with service name "swarmpit".

See screenshots bellow. 

**What happens:**

 I cannot see logs and/or add registries. At one point I was able to see service/task logs and add an ECR registry, but that was just once.

**What should happen:**

I should be able to see service/task logs and add/remove docker registries.

<img width="677" alt="Screenshot 2019-06-13 at 21 55 17" src="https://user-images.githubusercontent.com/424885/59460136-09c0a680-8e27-11e9-8566-53e8392a54d5.png">
<img width="428" alt="Screenshot 2019-06-13 at 21 55 08" src="https://user-images.githubusercontent.com/424885/59460137-09c0a680-8e27-11e9-8a11-c7cfe1525000.png">

**Comment by nohaapav** [comment]
@atmosx Clear your browser cache or run swarmpit in browser incognito mode ..

**Comment by atmosx** [comment]
@nohaapav it works, thanks!

**Comment by nohaapav** [comment]
@atmosx Yeah, we need to introduce some hashing or versioning of `main.css` & `main.js` so the browser reload these automatically when new build out instead of dropping cache (not the best user xp).
