### ISSUE TITLE
Stack creation and updates fails since upgrade to 1.7

### ISSUE THREAD

**Issue by Sinnohd** [swarmpit/swarmpit#366]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
**Description**

Creation of new stacks or update of existing stacks, fails, throwing an HTTP Error 500.

**Steps to reproduce the issue:**

1. Try to create the following stack:

`version: '3.3'
services:
  redis:
    image: redis:alpine
    networks:
     - default
    logging:
      driver: json-file
  web:
    image: 111111111111.dkr.ecr.eu-central-1.amazonaws.com/helloworld:dev
    ports:
     - 5001:5000
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
`
The helloworld image was build, following step by step from here (https://docs.docker.com/compose/gettingstarted/) and uploaded in our AWS ECR. 

**What happens:**

It fails, without any further information. In browser console, I can see a HTTP 500 error.

`{"via":[{"type":"java.net.MalformedURLException","at":["java.net.URL","<init>","URL.java",627]},{"type":"java.lang.NullPointerException"}],"trace":[]}`

Had also one with more output:

`{"via":[{"type":"java.net.MalformedURLException","at":["java.net.URL","<init>","URL.java",627]},{"type":"java.lang.NullPointerException","at":["java.net.URL","<init>","URL.java",532]}],"trace":[["java.net.URL","<init>","URL.java",532],["java.net.URL","<init>","URL.java",490],["java.net.URL","<init>","URL.java",439],["cemerick.url$url_STAR_","invokeStatic","url.clj",87],["cemerick.url$url_STAR_","invoke","url.clj",87],["cemerick.url$url","invokeStatic","url.clj",135],["cemerick.url$url","invoke","url.clj",121],["swarmpit.api$registries_by_stackfile$fn__15729","invoke","api.clj",600],["clojure.core$filter$fn__5878","invoke","core.clj",2817],["clojure.lang.LazySeq","sval","LazySeq.java",42],["clojure.lang.LazySeq","seq","LazySeq.java",51],["clojure.lang.LazySeq","cons","LazySeq.java",94],["clojure.lang.LazySeq","cons","LazySeq.java",17],["clojure.lang.RT","conj","RT.java",673],["clojure.core$conj__5375","invokeStatic","core.clj",85],["clojure.core$conj__5375","invoke","core.clj",82],["swarmpit.api$stack_login","invokeStatic","api.clj",1133],["swarmpit.api$stack_login","invoke","api.clj",1130],["swarmpit.api$create_stack","invokeStatic","api.clj",1146],["swarmpit.api$create_stack","invoke","api.clj",1142],["swarmpit.handler$fn__16806$fn__16808","invoke","handler.clj",639],["bidi.ring$fn__19854","invokeStatic","ring.clj",20],["bidi.ring$fn__19854","invoke","ring.clj",17],["bidi.ring$fn__19839$G__19834__19848","invoke","ring.clj",12],["bidi.ring$make_handler$fn__19859","invoke","ring.clj",37],["ring.middleware.resource$wrap_resource$fn__19008","invoke","resource.clj",37],["buddy.auth.accessrules$wrap_access_rules$fn__18256","invoke","accessrules.clj",347],["swarmpit.server$wrap_client_exception$fn__20084","invoke","server.clj",25],["swarmpit.server$wrap_fallback_exception$fn__20087","invoke","server.clj",33],["swarmpit.authentication$wrap_authentication$fn__19251","invoke","authentication.clj",31],["swarmpit.server$wrap_path_params$fn__20091","invoke","server.clj",42],["ring.middleware.json$wrap_json_params$fn__18465","invoke","json.clj",72],["ring.middleware.json$wrap_json_response$fn__18477","invoke","json.clj",87],["ring.middleware.flash$wrap_flash$fn__18521","invoke","flash.clj",39],["ring.middleware.session$wrap_session$fn__18731","invoke","session.clj",108],["ring.middleware.keyword_params$wrap_keyword_params$fn__18765","invoke","keyword_params.clj",36],["ring.middleware.nested_params$wrap_nested_params$fn__18815","invoke","nested_params.clj",89],["ring.middleware.multipart_params$wrap_multipart_params$fn__18972","invoke","multipart_params.clj",173],["ring.middleware.params$wrap_params$fn__18988","invoke","params.clj",67],["ring.middleware.cookies$wrap_cookies$fn__18640","invoke","cookies.clj",175],["ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__19095","invoke","absolute_redirects.clj",47],["ring.middleware.resource$wrap_resource$fn__19008","invoke","resource.clj",37],["ring.middleware.content_type$wrap_content_type$fn__19059","invoke","content_type.clj",34],["ring.middleware.default_charset$wrap_default_charset$fn__19075","invoke","default_charset.clj",31],["ring.middleware.not_modified$wrap_not_modified$fn__19041","invoke","not_modified.clj",53],["ring.middleware.x_headers$wrap_x_header$fn__18492","invoke","x_headers.clj",22],["ring.middleware.x_headers$wrap_x_header$fn__18492","invoke","x_headers.clj",22],["ring.middleware.x_headers$wrap_x_header$fn__18492","invoke","x_headers.clj",22],["ring.middleware.gzip$wrap_gzip$fn__19185","invoke","gzip.clj",100],["org.httpkit.server.HttpHandler","run","RingHandler.java",91],["java.util.concurrent.Executors$RunnableAdapter","call","Executors.java",511],["java.util.concurrent.FutureTask","run","FutureTask.java",266],["java.util.concurrent.ThreadPoolExecutor","runWorker","ThreadPoolExecutor.java",1142],["java.util.concurrent.ThreadPoolExecutor$Worker","run","ThreadPoolExecutor.java",617],["java.lang.Thread","run","Thread.java",745]]}`

**What should happen:**

It should create or update a stack.

**Additional information (e.g. docker version, cluster setup,...):**

Swarmpit version updated from 1.6 to 1.7.
Docker version 18.09.6
Swarmpit service log is not showing any error.

**Comment by nohaapav** [comment]
Refresh your browser cache or try to run in incognito window .. probably still 1.6 is cached. ..

**Comment by Sinnohd** [comment]
Did this already and didn't helped. Saw the same issue already in the past with some dev build of 1.7 release.

**Comment by nohaapav** [comment]
<img width="1482" alt="Screen Shot 2019-06-17 at 5 46 53 PM" src="https://user-images.githubusercontent.com/4179104/59618177-f57ef100-9127-11e9-9239-fd432f7b8b23.png">

<img width="1464" alt="Screen Shot 2019-06-17 at 5 47 02 PM" src="https://user-images.githubusercontent.com/4179104/59618191-fa43a500-9127-11e9-961f-e34e3f050e3e.png">

Just test it and works fine ..

**Comment by nohaapav** [comment]
```

**Comment by nohaapav** [comment]
Just to be sure: Did you link your ECR registry with Swarmpit right ?

As it looks like Swarmpit can't find registry by ID. See:
`["swarmpit.api$registries_by_stackfile$fn__15729","invoke","api.clj",600],`

**Comment by Sinnohd** [comment]
Yep, ECR is linked. Thanks for the hint with the registry, I believe it's then the combination of our company proxy in combination with swarmpit (this proxy is already a pita - now need to figure out, how to setup Swarmpit, to talk through the proxy with AWS - so far, adding proxy parameters to java command and setting environment parameters weren't successful).

**Comment by nohaapav** [comment]
Just out of curiosity: Is ECR linked as `ECR` or standard `V2` registry ?

**Comment by Sinnohd** [comment]
Ok, removing the proxy from the path solved the issue. ECR was linked as ECR, but during the setup, the URL was not detected and set. The empty URL part, then led to the java stack trace.

FYI, the dataset for the registry, looked like this in the CouchDB (replaced access and secret key with xxx).

`{"id":"efe2699da5b49c61dc87a7afdf0021ff","key":"efe2699da5b49c61dc87a7afdf0021ff","value":{"rev":"1-b0195382bd9c8942b5a0802ddf4e9ace"},"doc":{"_id":"efe2699da5b49c61dc87a7afdf0021ff","_rev":"1-b0195382bd9c8942b5a0802ddf4e9ace","registryType":"ecr","accessKeyId":"xxx","public":true,"type":"ecr","region":"eu-central-1","accessKey":"xxx","url":null,"user":"docker-registry-bot","owner":"admin"}}
]}`

Another solution would be, to overwrite the entrypoint and configure the proxy as part of the java VM.

As example:

```version: '3.3'
services:
  app:
    image: swarmpit/swarmpit:1.7
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
    entrypoint: [ "/usr/bin/java", "-Dhttp.proxyHost=10.10.10.20", "-Dhttp.proxyPort=8080", "-Dhttps.proxyHost=10.10.10.20", "-Dhttps.proxyPort=8080", "-Dhttp.nonProxyHosts=\"localhost|127.*|db|10.*\"", "-jar", "/usr/src/app/swarmpit.jar" ]
...
```

However, solved now, so I will close this one.

**Comment by nohaapav** [comment]
Yes makes sense as it failed here: `["cemerick.url$url_STAR_","invokeStatic","url.clj",87],` Not valid url

Great that you figure it out )
