### ISSUE TITLE
Feature Request: Webhooks Support

### ISSUE THREAD

**Issue by Jaben** [swarmpit/swarmpit#368]
First of all, love Swarmpit -- thank you for all your hard work. It's excellent.

One feature I'd love to see added is a simple webhook per service that would force "pull latest." Portainer has this feature and we used it for scheduled deployments.

Thanks!

**Comment by nohaapav** [comment]
@Jaben Hi Jaben, you can just enable autoredeploy .. :) We have agent in place that is checking your registry (if linked with swarmpit) for new digest .. if new one is in place, service is automatically redeployed .. 

You can enable autoredeploy via service API (deployment section)
or by adding this label under deploy section if you're using application stack: `swarmpit.service.deployment.autoredeploy = true`

**Comment by Jaben** [comment]
I didn't realize it had that feature! Excellent! But we need scheduled deployments. Production needs to be updated at, say, 10:00pm.

**Comment by nohaapav** [comment]
Maybe as a workaround you can call our backend api directly :) 

POST `/api/services/{service_id}/redeploy` which is basically force update(if there is new image it gets updated). You just have to generate token in user/settings API ACCESS section.

**Comment by nohaapav** [comment]
Or your goal is to have some scheduler on our side to force update at 10pm?

**Comment by Jaben** [comment]
API call world work perfectly. Thank you!

**Comment by Jaben** [comment]
Appreciate all the help -- closing as my needs are met without additional features.
