### ISSUE TITLE
Environment variable order when editing stack

### ISSUE THREAD

**Issue by tlaukkan** [swarmpit/swarmpit#369]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

Environment variables appear in random order when editing stack.

**Steps to reproduce the issue:**
1. Create stack
2. Edit stack
3. Observe the order of environment variables

**What happens:**

Environment variables are in random order.

**What should happen:**

Environment variables should retain their order or be in alphabetical sort.

**Additional information (e.g. docker version, cluster setup,...):**

Swarmpit 1.6

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by nohaapav** [comment]
Well the stack is generated from `current application state` by default so you have always actual data (in case that someone changed for example service via cli or service api)

So basically what you see are the data returned directly from engine. Only thing we can do is some sorting in alphabetical order.

**Comment by tlaukkan** [comment]
Alphabetical sort would be great as finding variables currently can be quite hard if you have many.

**Comment by tlaukkan** [comment]
read_only: true is also lost if it is directly under service to set root file system read only.
