### ISSUE TITLE
Logs not working after upgrade from swarmpit 1.6 to 1.7

### ISSUE THREAD

**Issue by tlaukkan** [swarmpit/swarmpit#370]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

Logs not working after upgrade from swarmpit 1.6 to 1.7.

1. Upgrade existing swarm from swarmpit 1.6 to 1.7 and agent from 2.0 to 2.1.
2. Set agent label as instructed in release.

**What happens:**
No log rows can be seen in logs view for tasks and services.

**What should happen:**
Logs should be viewable normally.

**Additional information (e.g. docker version, cluster setup,...):**
Reverting to swarmpit 1.6 and swarmpit 2.1 fixed the log viewing.

Logs can be normally viewed from docker logs <containerid>
No errors appear in swarmpit and agent container logs.

**Comment by nohaapav** [comment]
Clear your browser cache to fix it. It's known issue see:

https://github.com/swarmpit/swarmpit/issues/365

**Comment by tlaukkan** [comment]
Thank you. It would be helpful if this information could be included in the release notes.

**Comment by nohaapav** [comment]
Yeah, i will probably introduce some hotfix to 1.7 this week.
