### ISSUE TITLE
Swagger API documentation

### ISSUE THREAD

**Issue by danielwrayois** [swarmpit/swarmpit#377]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Hi, I can't seem to find any documentation covering the API spec, is there currently any generated  (Swagger, or Redoc, etc) documentation, if not is this something that is planned for the future?

**Comment by nohaapav** [comment]
Hi @danielwrayois .. Yes, we plan to introduce swagger for swarmpit API. Basically you can read api definition from this [routing](https://github.com/swarmpit/swarmpit/blob/master/src/cljc/swarmpit/routes.cljc#L6) and check via browser inspect what kind of data are being sent.

**Comment by nohaapav** [comment]
Swagger integration done. You can list backend API by visiting `/api-docs` or clicking version in UI.
