### ISSUE TITLE
Random ports not allocated when using host mode networking

### ISSUE THREAD

**Issue by dpkirchner** [swarmpit/swarmpit#378]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

When you specify that you want to use host mode networking and then leave Host blank (or the default 0) no port will be allocated and the service will remain unreachable to the outside world.

**Steps to reproduce the issue:**
1. Create a service, any service
2. Under "ports", specify your container's default port and protocol, choose "Host" under "Mode", and then either leave "Host port" blank or specify 0

**What happens:**

The service is not configured to use host mode networking. No exposed ports are published. Almost as bad, no error message is shown or logged. The request to use host mode networking is silently ignored.

**What should happen:**

The service should be configured to use host mode networking. Exposed ports should be published.

**Additional information (e.g. docker version, cluster setup,...):**

Specifying a host mode port is sort of a workaround, but has obvious problems.

Creating services on the command line works as expected when specifying `--publish` e.g.

`sudo docker service create --mode replicated --publish mode=host,target=8080 --name whatever --network whatever whatever/whatever:latest`

however, subsequent edits made using the UI will cause the port to be unpublished when the services are recreated.

I don't know clojure but I suspect the bug might be at https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/docker/engine/mapper/outbound.clj#L32

Versions:
* Docker version 19.03.0, build aeac9490dc
* Swarmpit 1.7 (using Swarmpit agent 2.1, installed using Swarmpit installer 1.7)

**Comment by nohaapav** [comment]
This is on purpose. If you have to expose service to outside world with port directly you should be aware of port number instead of some random number. We suggest you to specify host port manually instead of using automatic port range.
