### ISSUE TITLE
Add possibility to launch a command in interactive mode via web

### ISSUE THREAD

**Issue by cadavre** [swarmpit/swarmpit#383]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

It would be awesome if we could launch a command in interactive mode and attach to it. This way we could have a "console via web" if command is `/bin/bash`.

**Comment by lumir-mrkva** [comment]
@cadavre we have it in a roadmap a long time, but now we're fetching logs from individual nodes though agent and this finally allows us to implement stream back that would allow this feature

https://github.com/swarmpit/swarmpit/issues/93
