### ISSUE TITLE
Test user is with admin permission

### ISSUE THREAD

**Issue by hopik007** [swarmpit/swarmpit#389]
I have created test user for share swarmpit with our developers without possibility changing configuration or deploy task but test user has admin permission.

**How to reproduce:**
Created test user with user role. 
Check user tabs in section `is admin` is `yes`  instead `no` but directly checking role on user is showing user role but I can still modify services, configuration and deploy stack same as with admin role.

**Comment by nohaapav** [comment]
Yes you can. But you can't access admin section which is now only USERS. For advanced configuration we'll introduce permissive model in future.

**Comment by hopik007** [comment]
ok thanks a lot for information.
