### ISSUE TITLE
How disable influx?

### ISSUE THREAD

**Issue by sinacek** [swarmpit/swarmpit#392]
I didn't found how disable usage of INFLUX and without setuped ENV variable I wasn't able run master branch.

**Comment by nohaapav** [comment]
currently you can't .. influx was introduced in order to show extra statistics and collect data necessary for auto-scaling etc ..

**Comment by sinacek** [comment]
Is necessary to use your database `swarmpit`? I would like to connect swarm to `telegraf` database, where Telegraf store much more information about docker and I dont need store same information on two places.

**Comment by nohaapav** [comment]
@sinacek We'll make it optional so existing users can update current stack without outage. Basically you can't use different database as we're using different data structure but you can use same influx and have two separate DB's swarmpit & telegraf

**Comment by sinacek** [comment]
Do you have any time estimation of this feature and release of the new version?

**Comment by nohaapav** [comment]
I hope we can make it this weekend for master branch which means it's going to be supported in EDGE version, official release date of 1.8 is end of month but as some of DEVs are in Osaka on conference it might take a bit longer.

**Comment by sinacek** [comment]
Thanks a lot! This information is very helpful for me! I'm looking forward

**Comment by nohaapav** [comment]
@sinacek You can now disable influx by omitting SWARMPIT_INFLUXDB. However we're going to build some extra features based on influx data so these won't be supported for you.

**Comment by sinacek** [comment]
I tried it with latest official docker image and it doesn't work.
```
INFO: Waiting for InfluxDB ...
Oct 08, 2019 1:11:58 PM swarmpit.database invoke
SEVERE: ... timeout
Exception in thread "main" java.lang.IllegalArgumentException: Additional data must be non-nil.
 at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:31)
 at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:22)
 at clojure.core$ex_info.invokeStatic(core.clj:4783)
 at clojure.core$ex_info.invoke(core.clj:4783)
 at swarmpit.database$wait_for_db.invokeStatic(database.clj:31)
 at swarmpit.database$wait_for_db.invoke(database.clj:22)
 at swarmpit.database$init_influx.invokeStatic(database.clj:58)
 at swarmpit.database$init_influx.invoke(database.clj:54)
 at swarmpit.database$init.invokeStatic(database.clj:64)
 at swarmpit.database$init.invoke(database.clj:61)
 at swarmpit.server$_main.invokeStatic(server.clj:60)
 at swarmpit.server$_main.doInvoke(server.clj:58)
 at clojure.lang.RestFn.invoke(RestFn.java:397)
 at clojure.lang.AFn.applyToHelper(AFn.java:152)
 at clojure.lang.RestFn.applyTo(RestFn.java:132)
 at swarmpit.server.main(Unknown Source)
Oct 08, 2019 1:13:34 PM swarmpit.server invoke
INFO: Swarmpit is starting...
Oct 08, 2019 1:13:34 PM swarmpit.database invoke
INFO: Waiting for CouchDB ...
Oct 08, 2019 1:13:34 PM swarmpit.database invoke
INFO: ... connected after 0 sec
Oct 08, 2019 1:13:34 PM swarmpit.database invoke
INFO: Waiting for InfluxDB ...
```

```
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
#      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - swampit
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.50'
          memory: 1.5GB
      placement:
        constraints:
          - node.role==manager
      update_config:
        order: start-first
...
```

**Comment by nohaapav** [comment]
@sinacek Try now (once latest built) .. There was still default config pointing to localhost.

**Comment by sinacek** [comment]
There is no new build https://hub.docker.com/r/swarmpit/swarmpit/tags

**Comment by nohaapav** [comment]
yes, travis is somehow broken .. we need to fix it first

**Comment by nohaapav** [comment]
should be ready now

**Comment by sinacek** [comment]
It works, thanks!
