### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by 1moere1** [swarmpit/swarmpit#396]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

Starting a container results in this output on my Rpi 4:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Steps to reproduce the issue:**
1. `docker run -it --rm --name swarmpit-installer --volume /var/run/docker.sock:/var/run/docker.sock
swarmpit/install:1.7`

**What happens:**
^

**What should happen:**
Should start normally the swarmpit setup in a container

**Additional information (e.g. docker version, cluster setup,...):**
`Docker version 19.03.2, build 6a30dfc`

**Comment by nohaapav** [comment]
@1moere1 We have to prepare arch installer first in order to make it work. You can still use manual installation here with arm stack prepared by @lumir-mrkva here:
https://github.com/swarmpit/swarmpit/tree/arm
