### ISSUE TITLE
Swarmpit using HTTP/HTTPS Proxy

### ISSUE THREAD

**Issue by farflungfish** [swarmpit/swarmpit#397]
**Swarmpit using HTTP/HTTPS Proxy**

I cannot seem to link the dockerhub registry despite http_proxy and https_proxy being set in my compose file:

`version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
      - "http_proxy=http://x.x.x.x:3128"
      - "https_proxy=http://x.x.x.x:3128"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
`

**Steps to reproduce the issue:**
1. Use above part inside of docker-compose.yml
2. docker exec into the application container and able to curl google etc
3. Attempt to link via the site

**What happens:**
I get the error: Docker hub account creation failed. hub.docker.com: Try again -- despite being the correct credentials

**What should happen:**
The registry should correctly link using the http_proxy and https_proxy as appropriate

**Additional information (e.g. docker version, cluster setup,...):**
Latest version of docker 19, latest version of swarmpit

**Comment by nohaapav** [comment]
```
- "http_proxy=http://x.x.x.x:3128"
- "https_proxy=http://x.x.x.x:3128"
```
Where did zou get these from ? There is list of supported env variables for swarmpit:

https://github.com/swarmpit/swarmpit/blob/master/doc/configuration.md

**Comment by farflungfish** [comment]
Hi thanks for your response. I didn’t get them from anywhere, they are standard Linux variables to set a proxy.

I have reviewed the variables you mention and I am aware of them, though I don’t see anything helpful in regards to http proxy requests

**Comment by nohaapav** [comment]
I see .. i guess that problem is that swarmpit registry client is not aware of linux config at the moment.

**Comment by farflungfish** [comment]
As yet untested, but I think if I set the following in my composer then the jar possibly will pick up the proxy?
JAVA_FLAGS=-Dhttp.proxyHost=10.0.0.1 -Dhttp.proxyPort=3128

**Comment by farflungfish** [comment]
Sadly tested with JAVA_FLAGS and JAVA_OPTS, no luck!

**Comment by farflungfish** [comment]
Oddly I cannot make any changes to any existing services

**Comment by nohaapav** [comment]
@farflungfish Well yes, jar should pick up the proxy, but still this is not tested yet. We have to check it out ..

**Comment by ziadkiwan** [comment]
Hello! we are facing the same issue?? did you resolve it so far ?

**Comment by anisenBRU31** [comment]
In compose using this command

**Comment by anisenBRU31** [comment]
In Compose using this Command

**Comment by anisenBRU31** [comment]
Hello!
Insert this command in docker-compose

Command overwrite cmd in dockerfile
```` yml
command: java -Dhttp.nonProxyHosts="localhost|127.0.0.1|10.*.*.*|*.yourdomaine.com|influxdb|db" -Dhttp.proxyHost=yourpoxyhost  -Dhttp.proxyPort=3128 -Dhttps.proxyHost=yourpoxyhost -Dhttps.proxyPort=3128 -jar swarmpit.jar
````
Replace yourpoxyhost  by your proxy host
