### ISSUE TITLE
Can not get system resource monitoring.

### ISSUE THREAD

**Issue by otokaze** [swarmpit/swarmpit#399]
**Description**
The same version of system os
The same version of docker ce
However, some instances can get system resource monitoring, but some can't. Why is that?

**Detail screenshot**
![image](https://ws1.sinaimg.cn/large/c2f00e48gy1g7qvjjynp1j21bb0idgnm.jpg)

**What happens:**
can not get system resource monitoring.

**What should happen:**
All instances should be subject to resource monitoring.

**Additional information (e.g. docker version, cluster setup,...):**
```shell
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by nohaapav** [comment]
@otokaze Is `swarmpit_agent` running on these nodes ?

**Comment by otokaze** [comment]
@nohaapav Yes, `swarmpit_agent` on all instances is working properly
![image](https://ws1.sinaimg.cn/large/c2f00e48gy1g7qwzlzeeoj21b80akgn3.jpg)

**Comment by nohaapav** [comment]
Can you share logs from agent instances running on nodes not showing stats ?

**Comment by otokaze** [comment]
@nohaapav  Of course! But it looks like there is only one log record :(
![image](https://ws1.sinaimg.cn/large/c2f00e48gy1g7sfe2ymiuj213009gad5.jpg)

**Comment by nohaapav** [comment]
@otokaze that one is good enough. As you can see agent is still waiting for swarmpit .. Basically that means that agent can't connect to Swarmpit and send statistics over there. So you see nothing.

Looks like there is some networking issue.

**Comment by otokaze** [comment]
However, apart from this, I don't see any logs to describe which step failed. Why is 'Waiting for Swarmpit'? The information I get is very limited.

I tried to use telnet to request the port 2377 that swarmpit is listening on. As expected, the service is up and running and the connection is successful on the faulty node:
![2019-10-20_234511.png](http://ws1.sinaimg.cn/large/c2f00e48gy1g853tdgoxxj20fv03ymyv.jpg)

Can you tell me what to do next?

**Comment by nohaapav** [comment]
@otokaze Waiting for swarmpit just means that Agent can't connect to Swarmpit (not Swarmpit is not running). Probably there is something wrong with network between Swarmpit and Agent .. (broken/wrong configuration) ...

**Comment by otokaze** [comment]
I also know that there is a problem with the network. Hahaha

Let's go further, What is the internal implementation of the process of `agent` connection to the `swarmpit` ? Which API or port was requested?

I want to know which step failed, in order to solve the problem better :)

**Comment by otokaze** [comment]
Thank you for your ideas! @nohaapav 

#### Reason
After various attempts at the `agent` container, I found that the problematic server could not access `http://app` after joining the `overlay` cross-host network environment of the `manager` node via `docker swarm join`. 

#### Solve 
I re-assigned the environment variable `DOCKER_API_VERSION` & `HEALTH_CHECK_ENDPOINT` to the container and the `agent` successfully connected to `swarmpit`.
![image](https://user-images.githubusercontent.com/10130882/67500716-b2c0bd00-f6b5-11e9-98b9-1f07b4e230e8.png)

#### New problem
But it also created a new problem, that is, the service deployed on this node can not be combined with other `Node` or `manager` implements `load balance` (access to the service deployed on this failed node, will not be dispatched by the scheduler to other nodes)
![image](https://user-images.githubusercontent.com/10130882/67502341-50b58700-f6b8-11e9-9c76-925024782c1b.png)

#### Example
Problematic node (centos7-jp): http://140.238.55.105:8888 
Normal node: http://35.229.159.113:8888

**Comment by nohaapav** [comment]
Yes true. We only recommend to use agent with overlay network so swarm do the internal LB out of the box. Static IP is never going to do any good. I suggest to check docker engine logs regarding overlay issue first.
