### ISSUE TITLE
Service Creation failed

### ISSUE THREAD

**Issue by akshayvijapur** [swarmpit/swarmpit#405]
Hi team,
 
We are encountering "Service creation failed" , when i tried to create any service. I am using 

git clone https://github.com/swarmpit/swarmpit
docker stack deploy -c swarmpit/docker-compose.yml swarmpit

to deploy swarmpit.

Can anybody help me what i can do? 

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**What happens:**

**What should happen:**

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by akshayvijapur** [comment]
Consider there are 4 nodes, if i reboot a leader node. then swarm pit UI is not  accessible.

**Comment by nohaapav** [comment]
Provide more data: E.g. inspect (http request) .. Version of swarmpit ..

**Comment by akshayvijapur** [comment]
swarm pit version is latest stable version.

Swarm pit app logs :

swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | INFO: Swarmpit running on port 8080
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | Oct 30, 2019 9:47:29 AM swarmpit.setup invoke
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | INFO: Docker API: 1.40
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | Oct 30, 2019 9:47:29 AM swarmpit.setup invoke
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | INFO: Docker ENGINE: 19.03.0
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | Oct 30, 2019 9:47:29 AM swarmpit.setup invoke
swarmpit_app.1.uw0l8v4idxxo@ubuntu-5vfxnx12ar1odjnt6aeqf1zed1wt0tk0    | INFO: Docker SOCK: /var/run/docker.sock



Swarm pit agent logs:

swarmpit_agent.0.ydttcdi6bs86@ubuntu-r94y9t5k45cxc48rd3widi6v9q5ucj31    | 2019/10/30 09:45:56 INFO: Waiting for Swarmpit...
swarmpit_agent.0.ydttcdi6bs86@ubuntu-r94y9t5k45cxc48rd3widi6v9q5ucj31    | 2019/10/30 09:47:31 INFO: Swarmpit OK
swarmpit_agent.0.ydttcdi6bs86@ubuntu-r94y9t5k45cxc48rd3widi6v9q5ucj31    | 2019/10/30 09:47:31 INFO: Event collector started.


Swarm pit DB logs : 
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:48:35.450184Z nonode@nohost <0.1960.0> 727dc8ee34 db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 2
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:48:36.054232Z nonode@nohost <0.1961.0> 414d81445f db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 2
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:49:06.872649Z nonode@nohost <0.2645.0> 24c296fcc8 db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 39
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:49:07.075652Z nonode@nohost <0.2647.0> 4e2b4b2617 db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 9
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:49:07.648083Z nonode@nohost <0.2649.0> b81c69af0c db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 2
swarmpit_db.1.jmyxc3xii55l@ubuntu-zpdtq68v6ss18v5g1mst4axmmqo9o8x6    | [notice] 2019-10-30T09:49:08.181812Z nonode@nohost <0.2650.0> 6e06ae01c8 db:5984 10.0.2.9 undefined POST /swarmpit/_find 200 ok 2

Swarm pit influx db logs:

swarmpit_influxdb.1.ieseu2y8yj17@ubuntu-lyzy2b2gtw4u1tpf5a98cx5hlwhl444o    | [httpd] 10.0.2.9 - - [30/Oct/2019:09:50:12 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" aac9693f-fafa-11e9-806e-02420a000211 35000
swarmpit_influxdb.1.ieseu2y8yj17@ubuntu-lyzy2b2gtw4u1tpf5a98cx5hlwhl444o    | [httpd] 10.0.2.9 - - [30/Oct/2019:09:50:12 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" aacfb8d7-fafa-11e9-806f-02420a000211 35348
swarmpit_influxdb.1.ieseu2y8yj17@ubuntu-lyzy2b2gtw4u1tpf5a98cx5hlwhl444o    | [httpd] 10.0.2.9 - - [30/Oct/2019:09:50:12 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" aad609e2-fafa-11e9-8070-02420a000211 35621

**Comment by nohaapav** [comment]
@akshayvijapur Provide http request from inspect.

**Comment by akshayvijapur** [comment]
![image](https://user-images.githubusercontent.com/16234889/67848179-2d606100-fb2a-11e9-8bb7-93af5e77235d.png)

**Comment by akshayvijapur** [comment]
{"spec":"(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:spec$266/labels :spec$266/repository :spec$266/hosts :spec$266/mounts :spec$266/secrets :spec$266/mode :spec$266/variables :spec$266/networks :spec$266/ports :spec$266/logdriver :spec$266/deployment :spec$266/serviceName :spec$266/resources :spec$266/configs] :opt-un [:spec$266/dir :spec$266/user :spec$266/replicas :spec$266/command :spec$266/tty]), :type :map, :leaf? false})","problems":[{"path":[],"pred":"(clojure.core/fn [%] (clojure.core/contains? % :secrets))","val":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"via":[],"in":[]},{"path":[],"pred":"(clojure.core/fn [%] (clojure.core/contains? % :configs))","val":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"via":[],"in":[]}],"type":"reitit.coercion/request-coercion","coercion":"spec","value":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"in":["request","body-params"]}

**Comment by akshayvijapur** [comment]
`{"spec":"(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:spec$266/labels :spec$266/repository :spec$266/hosts :spec$266/mounts :spec$266/secrets :spec$266/mode :spec$266/variables :spec$266/networks :spec$266/ports :spec$266/logdriver :spec$266/deployment :spec$266/serviceName :spec$266/resources :spec$266/configs] :opt-un [:spec$266/dir :spec$266/user :spec$266/replicas :spec$266/command :spec$266/tty]), :type :map, :leaf? false})","problems":[{"path":[],"pred":"(clojure.core/fn [%] (clojure.core/contains? % :secrets))","val":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"via":[],"in":[]},{"path":[],"pred":"(clojure.core/fn [%] (clojure.core/contains? % :configs))","val":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"via":[],"in":[]}],"type":"reitit.coercion/request-coercion","coercion":"spec","value":{"labels":[],"repository":{"name":"hello-world","tag":""},"hosts":[],"mounts":[],"mode":"replicated","variables":[],"networks":[],"ports":[],"logdriver":{"name":"json-file","opts":[]},"replicas":1,"deployment":{"rollback":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"update":{"failureAction":"pause","parallelism":1,"order":"stop-first","delay":0},"autoredeploy":false,"restartPolicy":{"attempts":0,"condition":"any","delay":5},"placement":[]},"serviceName":"","resources":{"limit":{"memory":0,"cpu":0},"reservation":{"memory":0,"cpu":0}}},"in":["request","body-params"]}`

**Comment by akshayvijapur** [comment]
@nohaapav  Please help

**Comment by nohaapav** [comment]
@akshayvijapur You still didn't provide your Swarmpit version ..

**Comment by akshayvijapur** [comment]
@nohaapav  1.8-08679a0

**Comment by akshayvijapur** [comment]
@nohaapav  Let me know for any other info.

**Comment by nohaapav** [comment]
Thx .. I see the problem .. Will push the fix in few minutes .. Due to swagger integration we had to change routing a little ..

**Comment by nohaapav** [comment]
Thanks for reporting. Wait for new build and update Swarmpit accordingly. Should be fixed.

**Comment by akshayvijapur** [comment]
@nohaapav  Thanks for the help. Also i am seeing that, if i shutdown the leader in the docker swarm. I am not able to access the UI from reachable node. Any help for this issue?

**Comment by nohaapav** [comment]
@akshayvijapur Swarmpit does not need leader, but has to be running on manager node. If it's not you see nothing of course.

**Comment by akshayvijapur** [comment]
@nohaapav  Where can i download the latest fix of yours. i wanted to try to ensure everything is working fine?

**Comment by nohaapav** [comment]
just redeploy the stack or swarmpit_app service and new image will be used ..
