### ISSUE TITLE
Data persistence challenges in Swarm

### ISSUE THREAD

**Issue by andersonpem** [swarmpit/swarmpit#409]
Hey guys. First of all, great piece of software. I'm really enjoying trying out Swarmpit.
I haven't been able to find any reasonable solution to the brick wall I hit with containers so I'll ask you guys here. How to handle persistent storage on the swarm clustered environment?

I mean, imagine that I have a MySQL server service in my stack. It creates a volume in one of the nodes that the task randomly ended up in. For some reason it's recreated in another node. Then, using the default local driver, the new node will create a new empty volume for the service.

Would I need to use some sorcery like a network filesystem to ensure the volume is available to any of the nodes that happen to spawn the task? And if so, could you guys point me to any resources I could learn more? :)

I don't know if it's the lack of sleep (and caffeine) that is limiting my imagination or I really did hit a wall in my environment. ^^

Thanks guys. And pardon my beginner's question.

**Comment by nohaapav** [comment]
You have to use `shared` volume driver instead of `local`. E.g. `cloudstor` if you running your cluster in AWS/AZURE or [rexray](https://github.com/rexray/rexray) and [glusterfs](https://blog.ruanbekker.com/blog/2019/03/05/container-persistent-storage-for-docker-swarm-using-a-glusterfs-volume-plugin/) might be good option as well.

**Comment by lumir-mrkva** [comment]
@andersonpem what is your setup? are you running swarm on some cloud service or just bare metal?

**Comment by andersonpem** [comment]
Running it on some Vultr instances :)
