### ISSUE TITLE
Feature request: Allocated/Reserved resources by node

### ISSUE THREAD

**Issue by steache** [swarmpit/swarmpit#412]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

First of all, thank you for this project! :) 

Is it possible to show reserved/allocated resources per node like k8s does it by multiple rings? :)
Thank you for your response even if it's not possible to implement. :)

![2019-11-12_2255](https://user-images.githubusercontent.com/34166829/68714695-a63ad080-05a0-11ea-87d7-30c68f7a515a.png)

**Comment by nohaapav** [comment]
This is doable .. CPU/Memory usage is already displayed on dashboard, we just have to include reservation/limit ratio of all services deployed in cluster. Actually very good hint .. Thanks.
