### ISSUE TITLE
Node Update Fails

### ISSUE THREAD

**Issue by ztimson** [swarmpit/swarmpit#417]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
**Description**
I am unable to edit nodes through swarmpit preventing me from changing a node's labels, role and availability. It appears that what ever node the swarmpit is running on can be updated successfully but all other nodes fail with a snackbar: Node update failed. 

**Steps to reproduce the issue:**
1. Click on Nodes in the sidebar
2. Click on a node **NOT** running swarmpit
3. Click the edit pencil
4. Make any changes
5. Hit save

**What happens:**
I get an error telling me the node failed to update.

**What should happen:**
The node should update without issue.

**Additional information (e.g. docker version, cluster setup,...):**
When I SSH into my swarm leader I can update nodes without issue: `docker node update --availability=active some_node` and the Swarmpit UI reflects the change in real time.

If I inspect the network tab of my browser I see that the POST request returns with a 400 (Bad Request) I don't know your stack but it looks like maybe the leader: null is killing some schema check?
**Request**
```
{ 
   "role":"worker",
   "labels":[ 

   ],
   "address":"10.10.10.2",
   "availability":"pause",
   "arch":"x86_64",
   "state":"ready",
   "leader":null,
   "id":"v2aoxavtmmgx60uaq1nsckoa4",
   "nodeName":"ubuntu-s-4vcpu-8gb-sfo2-01",
   "plugins":{ 
      "networks":[ 
         "bridge",
         "host",
         "ipvlan",
         "macvlan",
         "null",
         "overlay"
      ],
      "volumes":[ 
         "local"
      ]
   },
   "os":"linux",
   "engine":"19.03.5",
   "version":172511,
   "resources":{ 
      "cpu":4,
      "memory":7976
   },
   "stats":null
}
```
**Response**
```
{ 
   "spec":"(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:spec$268/role :spec$268/labels :spec$268/address :spec$268/availability :spec$268/arch :spec$268/state :spec$268/leader :spec$268/id :spec$268/nodeName :spec$268/plugins :spec$268/os :spec$268/engine :spec$268/version :spec$268/resources]), :type :map, :leaf? false})",
   "problems":[ 
      { 
         "path":[ 
            "leader"
         ],
         "pred":"clojure.core/boolean?",
         "val":null,
         "via":[ 
            "spec$268/leader"
         ],
         "in":[ 
            "leader"
         ]
      }
   ],
   "type":"reitit.coercion/request-coercion",
   "coercion":"spec",
   "value":{ 
      "role":"worker",
      "labels":[ 

      ],
      "address":"10.10.10.2",
      "availability":"pause",
      "arch":"x86_64",
      "state":"ready",
      "leader":null,
      "id":"v2aoxavtmmgx60uaq1nsckoa4",
      "nodeName":"ubuntu-s-4vcpu-8gb-sfo2-01",
      "plugins":{ 
         "volumes":[ 
            "local"
         ],
         "networks":[ 
            "bridge",
            "host",
            "ipvlan",
            "macvlan",
            "null",
            "overlay"
         ]
      },
      "os":"linux",
      "engine":"19.03.5",
      "version":172511,
      "resources":{ 
         "memory":7976,
         "cpu":4
      },
      "stats":null
   },
   "in":[ 
      "request",
      "body-params"
   ]
}
```

**Comment by nohaapav** [comment]
@ztimson You're right .. We introduced schema coercion in 1.8, unfortunately we forgot to fix node update .. should be fixed
