### ISSUE TITLE
Dashboard Cluster Metrics Not Updating

### ISSUE THREAD

**Issue by ztimson** [swarmpit/swarmpit#418]
# Bug Report
**Description**
The dashboard page has 4 metrics across the top (# Nodes, Disk, RAM, CPU). I have noticed that when nodes leave the cluster 2 metrics (Disk & RAM) fail to update. However they do update when nodes join the cluster. Thus you can quickly inflate your Disk & RAM metrics by having nodes leave and rejoin.

**Steps to reproduce the issue:**
1. Navigate to the Dashboard
2. Take note of the current metrics
3. Remove a node from the cluster `docker swarm leave` & `docker node rm NODE`
4. Wait for changes to take affect in swarmpit
5. Join the node back into the swarm `docker swarm join-token worker`
6. Wait for changes to take affect in swarmpit
7. Reapeat steps 3-6 a couple more times for good measure
8. Observe the new metrics in the dashboard

**What happens:**
The Storage and Memory metrics accumulated the proper amount each time the node joined but failed to reduce each time a node left leading the two metrics to grow each time.

**What should happen:**
The Storage and Memory should remain accurate

**Comment by nohaapav** [comment]
The stats from old nodes unfortunately remains in cache. We have to check the availability of node when computation is done and remove invalid keys.

**Comment by nohaapav** [comment]
@ztimson should be fixed with https://github.com/swarmpit/swarmpit/commit/d32517e343d146a561272f96033946c67322bf75
