### ISSUE TITLE
Large configs go off the screen

### ISSUE THREAD

**Issue by jlundy2** [swarmpit/swarmpit#421]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

If you have a large configuration value, the configs screen allows the textbox for the config value to run off the screen without making the page scrollable to the right.

**Steps to reproduce the issue:**
1. Take a large value (in the screenshot, I've taken the content of this issue) and create a config in your swarm cluster.
2. Go and view the config in swarmpit. You'll see that the textbox of the value goes off the right side of the screen and the window is not scrollable. This was experienced on Version 78.0.3904.108 (Official Build) (64-bit)
<img width="1207" alt="Screen Shot 2019-12-02 at 6 28 25 PM" src="https://user-images.githubusercontent.com/16428663/70003606-ab50c700-1531-11ea-80af-e75977b5e1e4.png">

**What happens:**
It's very cumbersome to explore the value contents.

**What should happen:**
Perhaps the screen should be a single column similar to the mobile view when the config value is large.

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by nohaapav** [comment]
There is UI/UX redesign in progress which should be merge into master in the end of week fixing this issue.

**Comment by jlundy2** [comment]
Thanks @nohaapav! Can you point me to where that redesign is in progress?

**Comment by nohaapav** [comment]
@jlundy2 Branch issues/415 .. Still in progress, service forms redesign remains .. Will be done & merged in master on Friday i guess, then our UX guy will check it out and put cherry on the cake.

**Comment by nohaapav** [comment]
@jlundy2 fixed in master
