### ISSUE TITLE
node label update not working on swarmpit 1.8 

### ISSUE THREAD

**Issue by prabhinmp** [swarmpit/swarmpit#422]
The node update failed.
the above-mentioned error is getting while adding a label on the swarmpit 1.8 version. Kindly please look into this issue. Whereas adding label works in the command line.

**Comment by nohaapav** [comment]
what version u have ? we got issue with node update in 1.8 but this one was fixed with https://github.com/swarmpit/swarmpit/commit/1f7ce178df73b73901fd765997353be6cfeb4e2a in 1.9

**Comment by prabhinmp** [comment]
I uses 1.8 version of swarmpit and docker ce 18 and 19 version.
from the official website, i can see only 1.8 is the latest one.

**Comment by nohaapav** [comment]
1.8 is latest stable version .. but the very last one is edge which is current master ..

**Comment by prabhinmp** [comment]
okay, how should I add label through swarmpit 1.8

**Comment by nohaapav** [comment]
@prabhinmp well you can't .. As i mentioned it's broken in 1.8, fixed in 1.9 ..
