### ISSUE TITLE
how to upgrade swarmpit 1.6 to swarmpit 1.8 version 

### ISSUE THREAD

**Issue by prabhinmp** [swarmpit/swarmpit#423]
how to upgrade swarmpit 1.6 to swarmpit 1.8 version?

is there any procedure or any document for this. Please let me know. if would be great if you share with me the details steps to achieve this.

**Comment by nohaapav** [comment]
Just check release compose and update your stack accordingly:

`https://github.com/swarmpit/swarmpit/blob/{version}/docker-compose.yml`

For 1.8:
https://github.com/swarmpit/swarmpit/blob/1.8/docker-compose.yml
