### ISSUE TITLE
Swarmpit doesn't start if there are other nodes in the swarm cluster

### ISSUE THREAD

**Issue by adamkdean** [swarmpit/swarmpit#424]
Really simple to recreate this. Initialise swarm and add two more nodes, and then run the install container. It spins up the required containers but spreads them out, and then the periodic curl check goes on forever before giving you the failure message.

```
Starting swarmpit.......................FAILED!
Swarmpit is not responding for a long time. Aborting installation...:(
Please check logs and cluster status for details.
```

I tried this a few times before wondering if it is meant to be setup on the manager alone, and when I tried that, it worked:

```
Starting swarmpit.............DONE.
Initializing swarmpit...DONE.

Summary
Username: admin
Password: <snip>
Swarmpit is running on port :888

Enjoy :)
```

So I think either the docs need updating to explain that there should only be one node in the cluster at the point of install, or there should be a way that it only deploys to the current node.

**Comment by nohaapav** [comment]
Interesting .. This should not be an issue as there is curl check in same network as swarmpit see: 
https://github.com/swarmpit/installer/blob/master/install.sh#L159

**Comment by goireu** [comment]
Same here with edge version, I tried with :
- 3 managers / 1 worker: fail
- 3 managers / 0 worker: fail
- 1 manager / 0 worker: OK

App logs

> Dec 09, 2019 11:54:22 AM swarmpit.server invoke
> INFO: Swarmpit is starting...
> Dec 09, 2019 11:54:22 AM swarmpit.database invoke
> INFO: Waiting for CouchDB ...
> Dec 09, 2019 11:56:05 AM swarmpit.database invoke
> SEVERE: ... timeout
> Exception in thread "main" java.lang.IllegalArgumentException: Additional data must be non-nil.
> 	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:31)
> 	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:22)
> 	at clojure.core$ex_info.invokeStatic(core.clj:4783)
> 	at clojure.core$ex_info.invoke(core.clj:4783)
> 	at swarmpit.database$wait_for_db.invokeStatic(database.clj:31)
> 	at swarmpit.database$wait_for_db.invoke(database.clj:22)
> 	at swarmpit.database$init_couch.invokeStatic(database.clj:49)
> 	at swarmpit.database$init_couch.invoke(database.clj:47)
> 	at swarmpit.database$init.invokeStatic(database.clj:63)
> 	at swarmpit.database$init.invoke(database.clj:61)
> 	at swarmpit.server$_main.invokeStatic(server.clj:92)
> 	at swarmpit.server$_main.doInvoke(server.clj:90)
> 	at clojure.lang.RestFn.invoke(RestFn.java:397)
> 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
> 	at swarmpit.server.main(Unknown Source)

DB Logs:

> **************************************************
> WARNING: CouchDB is running in Admin Party mode.
>          This will allow anyone with access to the
>          CouchDB port to access your database. In
>          Docker's default configuration, this is
>          effectively any other container on the same
>          system.
>          Use "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
>          to set it in "docker run".
> ****************************************************
> [info] 2019-12-09T11:53:47.140385Z nonode@nohost <0.9.0> -------- Application couch_log started on node nonode@nohost
> [info] 2019-12-09T11:53:47.230624Z nonode@nohost <0.9.0> -------- Application folsom started on node nonode@nohost
> [info] 2019-12-09T11:53:47.630747Z nonode@nohost <0.9.0> -------- Application couch_stats started on node nonode@nohost
> [info] 2019-12-09T11:53:47.631117Z nonode@nohost <0.9.0> -------- Application khash started on node nonode@nohost
> [info] 2019-12-09T11:53:47.648830Z nonode@nohost <0.9.0> -------- Application couch_event started on node nonode@nohost
> [info] 2019-12-09T11:53:47.649153Z nonode@nohost <0.9.0> -------- Application hyper started on node nonode@nohost
> [info] 2019-12-09T11:53:47.753091Z nonode@nohost <0.9.0> -------- Application ibrowse started on node nonode@nohost
> [info] 2019-12-09T11:53:47.849514Z nonode@nohost <0.9.0> -------- Application ioq started on node nonode@nohost
> [info] 2019-12-09T11:53:47.849864Z nonode@nohost <0.9.0> -------- Application mochiweb started on node nonode@nohost
> [info] 2019-12-09T11:53:47.945831Z nonode@nohost <0.206.0> -------- Apache CouchDB 2.3.0 is starting.
> 
> [info] 2019-12-09T11:53:47.945966Z nonode@nohost <0.207.0> -------- Starting couch_sup
> [notice] 2019-12-09T11:53:48.049456Z nonode@nohost <0.90.0> -------- config: [features] pluggable-storage-engines set to true for reason nil
> [notice] 2019-12-09T11:53:48.341774Z nonode@nohost <0.90.0> -------- config: [couchdb] uuid set to 16aa36e59ece06fcfa462a44a60e94f5 for reason nil
> [info] 2019-12-09T11:53:48.950067Z nonode@nohost <0.206.0> -------- Apache CouchDB has started. Time to relax.
> 
> [info] 2019-12-09T11:53:48.950645Z nonode@nohost <0.206.0> -------- Apache CouchDB has started on http://any:5986/
> [info] 2019-12-09T11:53:48.951503Z nonode@nohost <0.9.0> -------- Application couch started on node nonode@nohost
> [info] 2019-12-09T11:53:48.951976Z nonode@nohost <0.9.0> -------- Application ets_lru started on node nonode@nohost
> [notice] 2019-12-09T11:53:49.129871Z nonode@nohost <0.271.0> -------- rexi_server : started servers
> [notice] 2019-12-09T11:53:49.141345Z nonode@nohost <0.275.0> -------- rexi_buffer : started servers
> [info] 2019-12-09T11:53:49.141533Z nonode@nohost <0.9.0> -------- Application rexi started on node nonode@nohost
> [info] 2019-12-09T11:53:49.447273Z nonode@nohost <0.9.0> -------- Application mem3 started on node nonode@nohost
> [info] 2019-12-09T11:53:49.447323Z nonode@nohost <0.9.0> -------- Application fabric started on node nonode@nohost
> [info] 2019-12-09T11:53:49.746852Z nonode@nohost <0.9.0> -------- Application chttpd started on node nonode@nohost
> [info] 2019-12-09T11:53:49.936364Z nonode@nohost <0.9.0> -------- Application couch_index started on node nonode@nohost
> [info] 2019-12-09T11:53:49.936461Z nonode@nohost <0.9.0> -------- Application couch_mrview started on node nonode@nohost
> [info] 2019-12-09T11:53:49.936647Z nonode@nohost <0.9.0> -------- Application couch_plugins started on node nonode@nohost
> [notice] 2019-12-09T11:53:50.735171Z nonode@nohost <0.90.0> -------- config: [features] scheduler set to true for reason nil
> [info] 2019-12-09T11:53:51.030134Z nonode@nohost <0.9.0> -------- Application couch_replicator started on node nonode@nohost
> [info] 2019-12-09T11:53:51.049018Z nonode@nohost <0.9.0> -------- Application couch_peruser started on node nonode@nohost
> [info] 2019-12-09T11:53:51.145988Z nonode@nohost <0.9.0> -------- Application ddoc_cache started on node nonode@nohost
> [info] 2019-12-09T11:53:51.337681Z nonode@nohost <0.9.0> -------- Application global_changes started on node nonode@nohost
> [info] 2019-12-09T11:53:51.338645Z nonode@nohost <0.9.0> -------- Application jiffy started on node nonode@nohost
> [info] 2019-12-09T11:53:51.349565Z nonode@nohost <0.9.0> -------- Application mango started on node nonode@nohost
> [info] 2019-12-09T11:53:51.439900Z nonode@nohost <0.9.0> -------- Application setup started on node nonode@nohost
> [info] 2019-12-09T11:53:51.440841Z nonode@nohost <0.9.0> -------- Application snappy started on node nonode@nohost
> [notice] 2019-12-09T11:53:55.142496Z nonode@nohost <0.349.0> -------- couch_replicator_clustering : cluster stable
> [notice] 2019-12-09T11:53:55.157818Z nonode@nohost <0.417.0> -------- Started replicator db changes listener <0.537.0>
> [notice] 2019-12-09T11:54:04.130457Z nonode@nohost <0.275.0> -------- rexi_buffer : cluster stable
> [notice] 2019-12-09T11:54:04.130849Z nonode@nohost <0.271.0> -------- rexi_server : cluster stable

The 1.8 version exhibits a different problem here, this issue is described here: https://github.com/apache/couchdb-docker/issues/54

Regards,

**Comment by nohaapav** [comment]
Well this looks to me like DB issue not installer. From some reason Swarmpit can't connect to database and so installation fails.

```
Dec 09, 2019 11:54:22 AM swarmpit.database invoke
INFO: Waiting for CouchDB ...
Dec 09, 2019 11:56:05 AM swarmpit.database invoke
SEVERE: ... timeout
```

**Comment by goireu** [comment]
Just tried 1.8 and edge, with another stack name (I previously simply rm'ed swarmpit stack). They both fail the same way with the https://github.com/apache/couchdb-docker/issues/54 issue (_users database doesn't exist in couchdb).
Configuration: 3 managers / 1 worker

**Comment by nohaapav** [comment]
@goireu Well that is not an issue .. Swarmpit can't connect to DB is the main issue. User DB creation is handled by swarmpit migration scripts but in order to trigger these scripts DB must be up and running. I'll do some investigation on my own.

**Comment by goireu** [comment]
Agreed, the issue most probably lies within the DB start.
It isn't clear why the DB would start in a single manager cluster configuration though... I'll keep digging

**Comment by nohaapav** [comment]
@goireu Well DB has started according logs correctly .. Problem is that Swarmpit can't reach the DB container due some reason. My colleague just successfully install EDGE version in our private cluster so it might be some infrastructure related issue.

**Comment by goireu** [comment]
In my second attempt, with different stack names, 3 Managers / 1 Worker: DB didn't even start, whether 1.8 or edge

**Comment by goireu** [comment]
Continuing with random stack names, 1 Manager / 0 Worker: swarmpit starts fine with both 1.8 and edge

**Comment by goireu** [comment]
Could it be your setup already has the correct volume in `/var/lib/docker/volumes/<stackname>_db-data/` so the DB starts properly?
It seems to me like the DB will only start properly from scratch on a single node swarm cluster.

**Comment by adamkdean** [comment]
Just to add to this, this failed for me on the first ever attempt to install swarmpit onto three fresh machines. So I don't think it's a case of there being previous install artefacts breaking it.

**Comment by goireu** [comment]
What I meant is: previous artefacts could enable DB to come up since the DB problem lies within uninitialized DBs.

**Comment by adamkdean** [comment]
Ah, that's an interesting twist!

**Comment by nohaapav** [comment]
@goireu Can you share logs in case of DB failure ? The one [above](https://github.com/swarmpit/swarmpit/issues/424#issuecomment-563208725) looks just fine.

**Comment by goireu** [comment]
It looks exactly like the issue I mentioned, you will most probably find the solution there :)

**Comment by nohaapav** [comment]
@goireu As i mentioned, this is not an issue here. These errors are harmless and can be fixed by calling by single node setup which is done by swarmpit [here](https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/couchdb/migration.clj#L16) But in order to make it happen connection between swarmpit and couch must be established which is not.

**Comment by nohaapav** [comment]
I'll try to simulate this case tomorrow in empty cluster ..

**Comment by goireu** [comment]
I see, you already worked around the issue. Sorry for not understanding that. I now get this is a network issue between `app` and `db`.

Basic tests:
- no ping to `db` from `app` or `influxdb` (can't `sh` on agent)
- `app`, `influxdb` and `agent` can ping each other

Let's see what the DNS says on `db`:
> # host app
> #
Let's see what the DNS says on `influxdb`:
> # host app
> app has address 10.0.13.2
> #

Skipping DNS, just in case, trying to ping 10.0.13.2 from `db` fails although the network interface is properly configured.

We most probably are facing an overlay network issue here although I can't see any difference when inspecting services...

**Comment by nohaapav** [comment]
It's definitely overlay issue but wondering what might be the problem. Do you have some special provisioning ? or maybe using ipv6 addresses range ?

**Comment by goireu** [comment]
This is a fresh cluster install on new Scaleway instances, send me your SSH key I will install them on the nodes. (mail in my account details)

**Comment by nohaapav** [comment]
@goireu sorry to get back to you bit later. Can you try to install Swarmpit via manual installation:

https://github.com/swarmpit/swarmpit#manual-installation

Just wondering if result is going to be the same.

**Comment by matthanley** [comment]
@goireu do you have firewalls enabled on the nodes? Overlay traffic goes over different ports to swarm management traffic. Does your VPN also allow UDP traffic?

**Comment by goireu** [comment]
No firewalling, UDP traffic goes well, overlay traffic is perfectly fine.
I'll have some time to work on this at the end of the month, I'll keep you posted. Sorry for not being more active on this one.

**Comment by 4ng3lp** [comment]
hi, same problem here.
The solution was to remove the snap package (ubuntu 18.04 lts) and install docker from docker website instructions.

sudo snap remove docker

https://docs.docker.com/engine/install/ubuntu/

**Comment by eramosr16** [comment]
Any update here?, I'm having the same issue. I found that the swarmpit_app start giving DB Timeouts after a day working I restart the App service and everything return to normal, I don't have to touch the DBs at all. Seems there is an exception that makes the app to fail.

**Comment by nohaapav** [comment]
@eramosr16 Are you sure it's not network issue ? swarmpit_app is using overlay network swarmpit_net to hit the swarmpit_db. From time to time overlay net just act fishy ..

**Comment by eramosr16** [comment]
I don't think it is the overlay network since I restart the service and everything start to work again, there is no other change I do to the cluster. I would try to add health check or something to see if the swarm detect the service is down and restart it automatically, is really annoying, besides that congratulations  to all Swarmpit developers is a great and useful software.

**Comment by kenashkov** [comment]
I have similar issue: "Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded."
I tried Edge and 1.9. The cluster I have is 3 managers (in PAUSE mode, nothing runs on them) and 3 workers.

**Comment by eramosr16** [comment]
I found a temporary solution to the problem basically I added a health check inside the app service to test the swarmpit port, this prevent the app from failing and if it does docker automatically restart the service.
`healthcheck:
      test:
       - CMD
       - curl
       - -f
       - http://localhost:8080
      interval: 90s
      timeout: 10s
      retries: 3`

**Comment by nohaapav** [comment]
@eramosr16 I'm now working on the same.

https://github.com/swarmpit/swarmpit/issues/440

Basically we are going to remove swarmpit_net attachable flag and use health-check instead of direct http ping via swarmpit_net.

**Comment by nohaapav** [comment]
Should be fixed in master. See:
[swarmpit](https://github.com/swarmpit/swarmpit/commit/cf891c2dfe305652569f4577383bd47aedc06465)
[installer](https://github.com/swarmpit/installer/commit/c9dfab4bff9066969f7353dba90ebff168b6b6f3)
