### ISSUE TITLE
show service update status and offer rollback

### ISSUE THREAD

**Issue by lumir-mrkva** [swarmpit/swarmpit#43]

**Comment by nohaapav** [comment]
UNKNOWN = 0;
UPDATING = 1;
PAUSED = 2;
COMPLETED = 3;
ROLLBACK_STARTED = 4;
ROLLBACK_PAUSED = 5; // if a rollback fails
ROLLBACK_COMPLETED = 6;

These are valid states. We're currently showing just flag "updating" if updating state is present.

Regarding to 1.28 API we can specify rollback strategy as follow:

"RollbackConfig": {
"Parallelism": 1,
"Delay": 1000000000,
"FailureAction": "pause",
"Monitor": 15000000000,
"MaxFailureRatio": 0.15
}

there should be new value in update config for failure action : rollback .. if that is the case we can set this to rollback by default and set some default rollback strategy or let user decide if rollback is wanted.
