### ISSUE TITLE
Swarmpit not starting after reboot!

### ISSUE THREAD

**Issue by bd8392** [swarmpit/swarmpit#434]
when you reboot the linux-host swarmpit is not starting anymore! (Installed with swarmpit stable (1.8 tag and agent 2.1))

**Description**

**Steps to reproduce the issue:**
1. Provision Linux host (rancheros)
2. Install Swarmpit with docker-compose
3. Reboot the machine

**What happens:**

**What should happen:**
Swarmpit should startup regularly

**Additional information (e.g. docker version, cluster setup,...):**
(Running on rancheros)

**Comment by nohaapav** [comment]
Can you share logs from `swarmpit_app` `swarmpit_db` services ...

**Comment by bd8392** [comment]
Sorry for the delay...I just checked the logs and there is only "waiting for swarmpit" in the app...the DB seems to initialize successful...do you need more output for the DB here? App sadly doesn't provide more logs...

**Comment by nohaapav** [comment]
@bd8392 That looks like overlay network between swarmpit and db is not working. Probably swarm issue, not swarmpit.

**Comment by bd8392** [comment]
sorry for the late answer...It's resolved by new server and I don't know what was wrong :-/ thanks for the help =)
