### ISSUE TITLE
Feature Request -- Change Node ip-adresses in Interface

### ISSUE THREAD

**Issue by bd8392** [swarmpit/swarmpit#435]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Can you build in an interface, to change the (fixed) ip adress of the nodes? And maybe for wlan? So you can do all the configuration out of swarmpit =) that would be really cool! (For example bind mount /etc/network/interfaces) ?

**Comment by nohaapav** [comment]
Most of the users are using VM provisioning and in order to support multiple providers we would have to implement different strategies. Not worth the effort at the moment compared to added value.
