### ISSUE TITLE
Tasks pagination

### ISSUE THREAD

**Issue by mtmsig** [swarmpit/swarmpit#436]
Add pagination to the tasks view. Currently it shows all tasks, and when you have a lot of tasks it gets really sluggish.

**Comment by nohaapav** [comment]
@mtmsig I guess we can't do much here as docker API does not support pagination ... Don't think that rendering takes most of time .. How long take the ajax call to BE ?

**Comment by mtmsig** [comment]
the call to /api/tasks takes 500-1000 ms. but it takes a bit to render it. The window freezes between the call is finished and it's rendered for maybe 1-3 seconds. I have +1000 tasks. The spinner still spins, but if I move my mouse over the menu items the hover effect doesn't show. So I do think it's rendering too many items at once.

**Comment by nohaapav** [comment]
interesting .. i'll try to simulate .. how many do you have exactly ? we got around ~ 500 + on each cluster and everything is smooth ..

**Comment by mtmsig** [comment]
1230 at the moment

**Comment by Doflatango** [comment]
@nohaapav How will you sort the tasks? sometime, i want to know which task is running on heavy load.

**Comment by nohaapav** [comment]
@Doflatango We do not .. Please raise an issue, we can apply a filter to sort tasks out

**Comment by Doflatango** [comment]
@nohaapav Thanks for your response, i have submitted an issue for this feature request.

**Comment by mtmsig** [comment]
@nohaapav Thank you! Much appreciated.
