### ISSUE TITLE
New Feature Request: Container Console

### ISSUE THREAD

**Issue by neygomon** [swarmpit/swarmpit#438]
Hello
The request to add the ability to "fall through" into the container to execute any commands inside the container using the GUI. This is a very convenient function when you need to quickly re-read something from application configs (the same nginx -s reload). Portainer has this chip, but there are enough bugs there, so I switched to swarmpit, and I would like to see the console here too.

**Comment by lumir-mrkva** [comment]
we are always pushing this feature away in #93, we're closer than ever to actually being able to support it with the new agent, but i think that will still take couple of releases before we get to it
