### ISSUE TITLE
Configs support Chinese. not only just in Latin1 range

### ISSUE THREAD

**Issue by lndj** [swarmpit/swarmpit#448]
**Description**
When Add a config contains Chinese, Js error:
 Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Steps to reproduce the issue:**
1.  Add a config contains Chinese on UI

**What happens:**
Js error

**Comment by elgerm** [comment]
I ran into the same problem, but then with Thai language. I guess supporting utf-8 would cover both

**Comment by lndj** [comment]
@elgerm  Yes, UTF-8 is right.  Current problem is caused by Javascript

**Comment by nohaapav** [comment]
Should be fixed in master.
