### ISSUE TITLE
[UI Bug] force scroll when editing service

### ISSUE THREAD

**Issue by Doflatango** [swarmpit/swarmpit#450]
**Description**
The service page always force scroll to the specific `Section` when you are editing other sections.

**Steps to reproduce the issue:**
1. go into a  `Service` view
2. click the `Edit` icon on such `Secrets` panel
3. scroll to page bottom and try update some thing(no need to submit the form)

**What happens:**
Page force scroll to the `Section` where the URL query  parameter(`edit?section=Xxxxx`) indicated.

**What should happen:**
No auto scroll.

**Additional information**
swarmpit 1.8

Looks like the UI has been upgraded in 1.9(#411 )，so this issue may no longer exist? 

And, i recommend use a FAB button instead of the current `Save` button.

Thanks.

**Comment by nohaapav** [comment]
> Looks like the UI has been upgraded in 1.9(#411 )，so this issue may no longer exist?
> 

Yes, issue has been fixed in 1.9
