### ISSUE TITLE
Viewing large logs make my server go wild

### ISSUE THREAD

**Issue by laurenskling** [swarmpit/swarmpit#452]
Hey guys,
When i want to view a log of a service that has been running a while, my servers gets a total CPU overload and crashes. It has the 15 minute setting on, but i guess it's trying to open the full file first? I'm using `driver: json-file`, no idea why. Just the default I guess. There's a bunch of logging options but I don't know what does what. What is the best option when i only view logs in swarmpit?

**Comment by lumir-mrkva** [comment]
please provide more info about your setup, docker info, swarmpit stack file. did you set max-size of log? can you estimate size of logs?

**Comment by laurenskling** [comment]
How to set a max-size prop? Estimate? Well... letting Nginx logs run for a month large ;)

**Comment by lumir-mrkva** [comment]
Edit service -> Logs -> Add option -> max-size, 100m
