### ISSUE TITLE
Service update failed when use Amazon ECR registry 

### ISSUE THREAD

**Issue by reg2005** [swarmpit/swarmpit#453]
Hello guys! I use latest commit of master branch (v 1.9-f8d6a61) and when i make redeploy (docker images stored in Amazon ECR) i getting error

**Steps to reproduce the issue:**
1. Add amazon ECR in regstry of swarmpit
2. Edit any service where uses Amazon ECR
3. Clck "Deploy"

**What happens:**
<img width="1422" alt=""  src="https://user-images.githubusercontent.com/4133683/72202111-cb4aa300-346c-11ea-9478-ac5829f963f3.png">

Service update failed. rpc error: code = InvalidArgument desc = ContainerSpec: "23423423423.dkr.ecr.us-east-2.amazonaws.com/mswefwdfsdfs:bfdea049sdfsdfsdfsdfsdfsc6b@" is not a valid repository/tag

**What should happen:**
Success deploy

**Additional information (e.g. docker version, cluster setup,...):**
In version 1.8-bb32809 deploy from ECR work is normally, this bug only in v 1.9-f8d6a61. 
I think the error in the character  "@" at the end of the address

**Comment by nohaapav** [comment]
@lumir-mrkva Can you check ? It looks like ARM digest commit might broke this ..

**Comment by nohaapav** [comment]
@reg2005 Should be fixed in master

**Comment by reg2005** [comment]
@nohaapav Thanks! Everything works 👍
