### ISSUE TITLE
consider to not share dockerhub accounts system-wide

### ISSUE THREAD

**Issue by lumir-mrkva** [swarmpit/swarmpit#46]
mby just add "shared" checkbox

**Comment by nohaapav** [comment]
We can add private checkbox so account repositories will be hidden to other users if checked

**Comment by nohaapav** [comment]
Lets discuss over these issues 
https://github.com/swarmpit/swarmpit/issues/30

**Comment by dbecvarik** [comment]
I think "shared" checkbox is much better than "private". From security point of view everything you create and contains access to something private should not be shared in system by default.

**Comment by nohaapav** [comment]
Agree. We already discussed this topic and default behaviour will be same as your proposal @dbecvarik . By default dockerhub accounts will be accessible only for given swarmpit user with possibility to make it public (shared) ..
