### ISSUE TITLE
Upgrade service with specific image tag version by CD pipeline

### ISSUE THREAD

**Issue by otokaze** [swarmpit/swarmpit#460]
**Description**
Is there an existing API that allows me to update the image version of the deployed service quickly and easily?
I have tried this API, but it is not suitable for the CICD scenario because there are too many parameters to be passed. API: `curl -X POST https://DOMAIN/api/services/SERVICE_ID`

**Comment by nohaapav** [comment]
@otokaze Hi if the version is the same, just different SHA use redeploy API:
<img width="977" alt="Screen Shot 2020-01-29 at 4 22 19 PM" src="https://user-images.githubusercontent.com/4179104/73369908-abf8a600-42b3-11ea-9dcd-79a5207623b6.png">

or you can enable service autoredeploy flag and swarmpit agent will take care of that action.

**Comment by otokaze** [comment]
However, I prefer that each deployment allows me to specify the version number, because this allows me to see the version that the current service is running rather than a unified `latest`.

And the API Document like the picture above, where can I view and use?

**Comment by nohaapav** [comment]
For such case we have to prepare new API like `/upgrade` with version payload. 

<img width="1609" alt="Screen Shot 2020-01-30 at 10 40 41 AM" src="https://user-images.githubusercontent.com/4179104/73437692-1d386780-434d-11ea-9bf7-269dabca9b33.png">

See bottom left corner -> Swagger API

**Comment by otokaze** [comment]
thank you very much!

I updated the docker image of swarmpit to the latest version and found the API documentation I wanted.
But I didn't find an API that would solve my problem. I wonder if there are plans to support this need in the future?

**Comment by nohaapav** [comment]
@otokaze Yeah actually i can create such API .. it's easy one.

**Comment by otokaze** [comment]
@nohaapav  Great! I urgently need such an API. 

And I think this will be common in CI/CD scenarios!

**Comment by otokaze** [comment]
I suggest adding a `tag` parameter in the`POST /api/services/{id}/deploy` API to specify the version of the deployment image, which is the current release version by default.

**Comment by nohaapav** [comment]
@otokaze To me it makes more sense to create new API `/api/services/{id}/upgrade` with `version` param. In the end it is not redeploy (same version, although SHA might differ) but component upgrade to new version.

**Comment by otokaze** [comment]
Okay, this is also good!

**Comment by nohaapav** [comment]
Done in master
