### ISSUE TITLE
Stack update failed. service influxdb: undefined volume "influx-data"

### ISSUE THREAD

**Issue by haolun-zhang-n4l** [swarmpit/swarmpit#470]
swarmpit_app containers do not have enough to run so I tried to update stack config to enlarge the RAM limitation on app.

Stack update failed. service influxdb: undefined volume "influx-data" popped up from bottom just after I clicked the deploy button.

Why there is a missing volume and how should I create it?

**Comment by haolun-zhang-n4l** [comment]
Problem solved by creating volume swarmpit_influx-data manually on every manager node.
```
docker volume create swarmpit_influx-data
```

Could you please give a hint than only show error messages when error happened?

**Comment by nohaapav** [comment]
@haolun-zhang-n4l Well during update, influx container has been probably rescheduled to different node without influx volume. You should use shared volumes to avoid such scenario or placements.
