### ISSUE TITLE
Handle fixed strings in service command

### ISSUE THREAD

**Issue by uniwuppes** [swarmpit/swarmpit#473]
**Description**

When creating a new service, the command seems to be split by spaces and handled as an array.
This breaks the support for fixed text strings inside a command, e.g.:
`sh -c "echo hello world"`
which is causes the following error
`hello: line 1: syntax error: unterminated quoted string`

**Steps to reproduce the issue:**
1. Create a new service
2. Enter a command with a fixed text string that contains spaces

**What happens:**
The fixed text string is split by spaces

**What should happen:**
The fixed string should be handled as a single array element

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by nohaapav** [comment]
@lumir-mrkva Can you check pls ?

**Comment by lumir-mrkva** [comment]
@uniwuppes we don't have any clever parsing yet, you can to enter every token on separate line as the workaround now

like this:
```
sh
-c 
"echo hello world"
```

this will supply command as the array of tokens directly to docker

**Comment by uniwuppes** [comment]
@lumir-mrkva Thanks, this workaround is sufficient for now.
