### ISSUE TITLE
Wrong IP address for manager leader

### ISSUE THREAD

**Issue by cpoetter** [swarmpit/swarmpit#476]
**Description**
If you have more than one manager in your Docker Swarm and the leader is _not_ the initial creator of the swarm, the IP address of the leader node is shown as 0.0.0.0.

As far I I could see this happens because Swarmpit uses `Status.Addr` to determine the IP address of _all_ nodes. According to https://github.com/moby/moby/issues/35437, Swarmpit should use `Status.Addr` for the worker nodes and `ManagerStatus.Addr` for manager nodes.

**Steps to reproduce the issue:**
1. Create a cluster with one manager and one worker.
2. Install Swarmpit in the swarm.
3. Promote the worker to a manager.
4. Reboot the original manager.

**What happens:**
The _new_ leader has the IP address 0.0.0.0 in the node detail page in Swarmpit.

**What should happen:**
The node detail page should ideally show show the advertisement IP address of the manager node.

**Additional information (e.g. docker version, cluster setup,...):**
- Ubuntu 18.04.4 LTS
- Docker version 19.03.6, build 369ce74a3c
- Swarmpit v1.9-0b9f47a

**Comment by velychkovsky** [comment]
Hello, I have the same issue.

- CentOS Linux release 7.7.1908 (Core)

- docker-ce-19.03.5-3.el7.x86_64

- Swarmpit  v1.9-0b9f47a

**Comment by diegoernestofarias** [comment]
https://github.com/moby/moby/issues/35437

**Comment by nohaapav** [comment]
Fixed by [38ffbe0](https://github.com/swarmpit/swarmpit/commit/38ffbe08e717d8620bf433c99f2e85a9e5984c32)
