### ISSUE TITLE
Preset user name and user password

### ISSUE THREAD

**Issue by rwanito** [swarmpit/swarmpit#477]
Hi !
I'm searching a way to preset the default user name and password after installation with docker compose file.
Is it possible ?

I can't manage with swarmpit/installer because my environment is offline, so I need to have images on my custom registry before install it.

And other question if possible, exists it a global swarmpit ?
I have multiples docker swarm cluster, it is possible de manager all with only one place ?

Thanks a lot for your work !

**Comment by mrspartak** [comment]
> I have multiples docker swarm cluster, it is possible de manager all with only one place ?
Smarmpit manages only one cluster is connected to. Look at Portainer for this

**Comment by lumir-mrkva** [comment]
@rwanito you can use swarmpit installer in non-interactive mode, see https://github.com/swarmpit/installer#non-interactive-mode

**Comment by nohaapav** [comment]
I guess we can close this one. Feel free to reopen if needed.
