### ISSUE TITLE
Gitlab private registry. Autoredeploy is not working

### ISSUE THREAD

**Issue by mrspartak** [swarmpit/swarmpit#479]
The public registry works fine, but my new private images do not redeploy with new version, only 'redeploy' button helps
I checked swarmpit logs and got only this message
```
pahlt  Mar 10, 2020 6:55:40 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
pahlt  WARNING: Invalid cookie header: "Set-Cookie: experimentation_subject_id=Im256ef19edec0c8e77; domain=.gitlab.com; path=/; expires=Sat, 10 Mar 2040 18:55:40 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 10 Mar 2040 18:55:40 -0000
```

**Comment by mrspartak** [comment]
As a temporary solution, I made an image, that works as a hook for CI to redeploy any swarmpit image
https://github.com/mrspartak/swarmpit-ci-deploy

**Comment by nohaapav** [comment]
try to redeploy swarmpit .. maybe cron job is rotten due some reason .. Cron job is using same API as redeploy basically ..

**Comment by mrspartak** [comment]
I tried. Redeploy from public hub works fine, only my private repo causing problems. 
Also, main feature of the image I provided above is it redeploys by ServiceName, but your API allows only to do so via service id only.

**Comment by mrspartak** [comment]
We are developing the second project and after 3 weeks got the same issue. The solution I made earlier (https://github.com/mrspartak/swarmpit-ci-deploy) works not as expected. 
I use API token, but it expires/removes at some point and at that point I have to get a new one and restart service with it.

**Comment by nohaapav** [comment]
@mrspartak Token does not expire unless you revoke it. It looks more like some issue with DB volume. I will try to debug the issue in 2.0 rel.

**Comment by mrspartak** [comment]
This happened only 2 times in the past. I use DigitalOcean droplets for a cluster.
Current cluster is only 1 droplet and in the last project, I had 2 droplets.
I can try to provide any logs, etc...

**Comment by laurenskling** [comment]
I just had the situation (on master) where my gitlab private registry wasn't autoredeploying. Removing the swarmpit stack and starting it again did fix it for me.

**Comment by nohaapav** [comment]
@laurenskling This is really strange .. We saw similar cases but restart/redeploy of swarmpit_app should be enough to fix it. This is due to cron job which from time to time dies and there is no logic to restart it internally.

**Comment by laurenskling** [comment]
It _was_ enough for me :) it _did_ fix it :)

**Comment by nohaapav** [comment]
Tested with private repo and is working just fine. Anyway please use primary Swarmpit API in order to redeploy image via CI (hooks). Autoredeploy checks image digest and i already saw few cases where 3rd party didn't implement correct response headers for registry manifest endpoint which caused similar malfunction.
