### ISSUE TITLE
bash sh cli support

### ISSUE THREAD

**Issue by mrspartak** [swarmpit/swarmpit#484]
I know, I'm asking a big thing, but this thing is needed sometimes.

So every time I need to look into the container I do:
1. Check node that runs my container in Swarmpit
2. Login to this server
3. docker ps
4. docker exec -it [service_hash] /bin/sh

**Comment by nohaapav** [comment]
There is already issue to cover this functionality. See https://github.com/swarmpit/swarmpit/issues/93
