### ISSUE TITLE
--Feature Request-- make compose on one node

### ISSUE THREAD

**Issue by bd8392** [swarmpit/swarmpit#486]
It would be a really nice feature when you would be able to deploy in swarm or in compose mode an a selected node. The interface of swarmpit is perfect for management and some deployments don't support swarm (like Mailserver)

**Comment by lumir-mrkva** [comment]
@bd8392 sorry, i am not totally sure what you mean, can you clarify by some example please?

**Comment by bd8392** [comment]
Yes :-) I mean that you can decide, if you want to deploy in stack mode, or docker-compose mode :-) Mailservers sadly don't run on stacks...

**Comment by nohaapav** [comment]
well stack / services are just container abstraction .. Don't see any reason why you can't run mailserver as service ..

**Comment by bd8392** [comment]
Because some functionality is missing in swarm...like cap add...

**Comment by nohaapav** [comment]
@bd8392 true story. The thing is: We can make it happen but you won't see containers in Swarmpit anyway as we don't support container API. And we won't support container API anytime soon i guess as we have other priorities and lack of capacities unfortunately. 

See https://github.com/swarmpit/swarmpit/blob/master/ROADMAP.md#overview
```
Swarmpit is aimed to support Docker Swarm Mode and its abstraction. Therefore we won't be supporting the majority of container API or any different orchestration platform.
```

**Comment by bd8392** [comment]
Ok I see :-) no problem :-) thanks for looking into it :-)
