### ISSUE TITLE
Repositories fetching failed. hub.docker.com

### ISSUE THREAD

**Issue by yaseco** [swarmpit/swarmpit#495]
### BUG REPORT

**Description:**

Getting this message when trying to create a new service from "public":

> Repositories fetching failed. hub.docker.com

**Steps to reproduce the issue:**
1. Go to Services -> NEW SERVICE
2. Choose registry "public"
3. Search for some service (e.g. 'mysql')

**What happens:**
Failure

> Repositories fetching failed. hub.docker.com

**What should happen:**
Show a list of services to install

**Additional information (e.g. docker version, cluster setup,...):**
I'm using Ubuntu with a disabled firewall

**Comment by nohaapav** [comment]
<img width="1207" alt="Screen Shot 2020-04-28 at 8 55 17 AM" src="https://user-images.githubusercontent.com/4179104/80456517-02ff2d00-892e-11ea-82f1-c71b72e0421f.png">

Works pretty well. Maybe hub was down at the moment or you had some network issues.

**Comment by yaseco** [comment]
@nohaapav 
The problem exists for long time (it was okay until some point)

1. Is there a way to debug it? 
2. Can you have a guess of what might cause the problem?

**Comment by nohaapav** [comment]
Well my guess is some network issue .. There is no much to debug .. you can check the API and try to run some curl to see if you can get the result from your WS ..

GET TOKEN:
https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/docker/auth/client.clj

CALL HUB:
https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/docker/hub/client.clj
