### ISSUE TITLE
Service auto-update on Docker images pushed to Registry

### ISSUE THREAD

**Issue by petit-romain** [swarmpit/swarmpit#498]
Hi,

First of all thanks to you for Swarmpit !

It's more a question than an issue, but I wanted to know how I can automatically update services with their new Docker image pushed on my Docker Registry.

On your website it said that servies checks if there is a new image but do you I need to configure it or it is by default ?

Kind regards

**Comment by mrspartak** [comment]
Hey @petit-romain!
You can do this using switch "Autoredeploy" on the Deployment tab.
![image](https://user-images.githubusercontent.com/993910/81411399-fc04c580-914a-11ea-977e-20d67a4d9034.png)

**Comment by petit-romain** [comment]
Oh sorry, I forgot you to toggle that switch .. Thank you !

Is it possible to configure this from my docker-compose file ?

**Comment by mrspartak** [comment]
I doubt you can. I guess this is a swarmpit feature, like a Watchtower for simple containers.

**Comment by petit-romain** [comment]
Ok that's fine. I have a last question :D

Do you why my Stack rollback button is greyed ?

**Comment by nohaapav** [comment]
@petit-romain @mrspartak it is possible .. You can easily check by service -> edit -> compose .. 
Every swarmpit feature can be enabled by label. This one with:

```
swarmpit.service.deployment.autoredeploy: 'true'
```

It's greyed because you just deployed new stack -> there is no other last state than actual one.

**Comment by petit-romain** [comment]
Oh great thank you !
