### ISSUE TITLE
Swarmpit health check unable to load Pi Zero stats.

### ISSUE THREAD

**Issue by prajal** [swarmpit/swarmpit#499]
**Steps to reproduce the issue:**
1. Installed the latest version of swarmpit - 1.9
2. Docker version 19.03.8,

<img width="1139" alt="Screenshot 2020-05-12 at 9 33 10 AM" src="https://user-images.githubusercontent.com/5576869/81637435-f43b6e80-9433-11ea-8f54-616e0ff99f3f.png">
<img width="1449" alt="Screenshot 2020-05-12 at 9 32 08 AM" src="https://user-images.githubusercontent.com/5576869/81637439-f6053200-9433-11ea-93a5-047cc6ede7df.png">

**Comment by nohaapav** [comment]
@prajal Is swarmpit agent running in that node ?

**Comment by nohaapav** [comment]
Closing due to inactivitty. Feel free to reopen.
