### ISSUE TITLE
A disk usage operation is already running

### ISSUE THREAD

**Issue by sanchobouillant** [swarmpit/swarmpit#500]
I'm using version 1.9 of swarmpit but I already saw that error on swarmpit 1.8. Sometimes, docker system prune solves the issue. I try to reboot the server and docker.

I can manage my swarm with docker. A command like docker volume ls working. There is a problem only with swarmpit.

```
/api/volumes
{"error":"a disk usage operation is already running"}
```

Docker version 19.03.8, build afacb8b7f0

Any ideas? 

Thanks for reading :)

Edit:

```
/api/stacks/traefik/compose
{"error":"a disk usage operation is already running"}
```

**Comment by nohaapav** [comment]
@sanchobouillant Hi, probably `docker system df` is still running .. Swarmpit calls that endpoint to check disk usage.. Do you have many volumes ? Or big ones ?

**Comment by sanchobouillant** [comment]
I made more tests. When I use swarmprom I get errors. I have a lot of volumes but only 1 big.

**Comment by nohaapav** [comment]
i will disable DF check so this won't happen .. system api is obviously slow if there are many resources which is causing the issue.

**Comment by kubw19** [comment]
> i will disable DF check so this won't happen .. system api is obviously slow if there are many resources which is causing the issue.

@nohaapav Is it fixed? If so, on which docker tag? We are using 1.9 and issue stil persists.
