### ISSUE TITLE
Feature Request: Detailed Error messages

### ISSUE THREAD

**Issue by splitice** [swarmpit/swarmpit#503]
Is there any chance of getting error messages with more information in them? Current error messages are very generic.

This does not appear to be a UI bug, the underlying API calls do not report any cause in their response. Most API calls return `null` in the error field (https://drive.google.com/uc?id=1JZo6P85HRJWJb6DKnr6ANR4RnEXnazlB). This may be a bug.

In the case for the screenshot provided as an example it's displayed as "service creation failed" error. From a users perspective it provides no insight into the cause,

**Comment by nohaapav** [comment]
https://github.com/swarmpit/swarmpit/blob/master/CONTRIBUTING.md#reporting-issues

Without details we're unable to help you debug the case.

**Comment by splitice** [comment]
I've rephrased the report as it seems you miss-understood. I don't need your help debugging anything.

If you wish to replicate the API returning null responses then from my experience most errors relating to registries do this. In my case it's an attempt to pull an image from a private (docker.pkg.github.com) registry that fails.

The underlying issue that cause the error is something I'm still looking into  (it looks like there is compatibility issues with docker.pkg.github.com however it's too early to say for sure and without anything logged or outputted in the response of the API call it's likely going to be an extensive troubleshooting process.

**Comment by nohaapav** [comment]
We're not supporting github registries. There is already issue to make support. Null is not a bug, if we got just http code we can't show you the actual reason why underlying 3rd party app failed. In this case you're trying to use something that has no build support so of course you get some 500/400 .. and response is null
