### ISSUE TITLE
Bugs: Registry Edit & Create form bugs (Minor)

### ISSUE THREAD

**Issue by splitice** [swarmpit/swarmpit#504]
1. Currently saving the registry form causes a secured registry password to be saved regardless of if the user has entered / changed it. This means that making a change is not possible if you do not know the password of the account (as it will be set to blank). The generally accepted convention for behavior with password forms is to persist the existing password when blank.
2. When pressing back (e.g to adjust a mistake) from the third page of the add registry form the Registry name ends up in the Registry URL input.

**Comment by nohaapav** [comment]
Please again provide step by step info to reproduce the issue .. we're not really wizards to figure out what you did .. 

Ad 1) On registry change you're entering just new password if you wish, if not you leave the field blank. New one (unless blank) is then compared with old on BE and if there is delta old one is replaced with new .. this is wanted behavior not a bug.

**Comment by splitice** [comment]
Not interested any longer.
