### ISSUE TITLE
Edit Stack via Swagger API not working

### ISSUE THREAD

**Issue by cpoetter** [swarmpit/swarmpit#505]
I am trying to edit/update a stack via the Swagger API via bash. So far I have the following script:

```
DOCKER_COMPOSE=$(cat docker-compose.yml)
DOCKER_COMPOSE="${DOCKER_COMPOSE//$'\n'/'\\n'}"

REQUEST_DATA="{\"name\": \"string\", \"spec\": {\"compose\": \"$DOCKER_COMPOSE\"}}"

curl -X POST -d ${REQUEST_DATA} --header "Content-Type: application/json" --header "Accept: application/json" --header "authorization: Bearer ....." "https://my-swarmpit.com/api/stacks/my-stack-name"
```

But I receive the following error:

```
{"error":"Stack invalid."}
```

I think what I don't understand is how to submit the new lines in the YML file correctly. Can you help me here?

Thanks!

**Comment by nohaapav** [comment]
@cpoetter Actually problem is that name in stack must match the one used in api call. In your case you should replace `string` with `my-stack-name`

**Comment by cpoetter** [comment]
Hi @nohaapav ,
I did that, sorry. I think my problem was how I replaced the new lines. It is working now with this code:
```
DOCKER_COMPOSE="${DOCKER_COMPOSE//$'\n'/\n}"
```
Thank you for your quick help though!
