### ISSUE TITLE
Cron scheduler

### ISSUE THREAD

**Issue by plockare** [swarmpit/swarmpit#515]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

**Cron like feature**

Would be nice to have possibility to start image at specific cronlike time. 

**Use case:**

Have service that is recounting statistics once a day. I don't want the service to run all day long with internal scheduler or with exposed API EP to trigger the event. We could save resources with on demand scheduling.

**Comment by lumir-mrkva** [comment]
you can already do that with cron service with mapped docker sock to spawn containers/services

alternatively this can be achieved with restart policy delay on service

**Comment by abellion** [comment]
Swarm jobs are coming : https://github.com/moby/moby/issues/39447

According to https://github.com/moby/moby/pull/40307, this will be release in version 20.03.0.

**Comment by nohaapav** [comment]
@abellion Thanks for info man.
