### ISSUE TITLE
Is there a debug setting available?

### ISSUE THREAD

**Issue by SysEngDan** [swarmpit/swarmpit#517]
I'm attempting to create a new service with Swarmpit, but when I get to the end of the options and click the "Deploy" button, an error is presented after some seconds which says "Service creation failed. Request timeout." When I check the container's logs ("docker logs"), there are no errors displayed. 

Is there a debug logging level available? I read through everything I could find in the repo but discovered nothing of this type.

**Comment by nohaapav** [comment]
By default docker client timeout is set to 5000 ms, see https://github.com/swarmpit/swarmpit/blob/master/doc/configuration.md#swarmpit_docker_http_timeout.. Try to increase it. There is no debug at the moment. Make sure you're using latest version of Swarmpit.

**Comment by nohaapav** [comment]
For debug i've created new issue to track progress. See https://github.com/swarmpit/swarmpit/issues/518
