### ISSUE TITLE
Add Node Column To Tasks Table

### ISSUE THREAD

**Issue by ztimson** [swarmpit/swarmpit#521]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------
If you either click on the tasks tab in the left nav or you open a service you will see a grid/table of tasks & the amount of CPU & memory used. It would be extremely useful to also know what node it is speaking about.

I have a particular use case where I want to make sure I have several replicas of a service spread between multiple servers. If I have to check 3 tasks I have to click into the task, then click "see node", make note of the name, then hit the back button twice to get back to the service page and then repeat that process twice more to check the other two (4 clicks * 3 tasks = 12 clicks). It would be a lot nicer if it was just there on the grid so it takes 0 clicks.

Hope this picture helps if I was unclear. Thanks in advance!

![image](https://user-images.githubusercontent.com/5761827/84207558-a7bd7000-aa7f-11ea-9659-b392956cee09.png)

**Comment by nohaapav** [comment]
Funny, it was actually there but we decided to remove it. The reason is: only case we found node info useful was in case of error. But now you can easily hover task status to see actual docker engine error that contains node info if related.

But let's move it back then.

**Comment by ztimson** [comment]
I thought it used to be there! I did find that useful plus it gives context to the other two columns, cpu & mem.

I didn't know I could hover so I will use that in the mean time, Thanks!

**Comment by nohaapav** [comment]
Back thx to @azrikahar
