### ISSUE TITLE
Feature request: Improve responsiveness of graphs for mobile devices 

### ISSUE THREAD

**Issue by AlexGustafsson** [swarmpit/swarmpit#530]
Most of Swarmpit works great on mobile devices, but the Plotly graphs, however, is another story. Below are a couple of screenshots highlighting the issue.

Browser is Safari on iOS with a screen size of 1 334 by 750 pixels, which on the web is 667 by 375 pixels. The Swarmpit version is 1.9.

![IMG_3789](https://user-images.githubusercontent.com/14974112/85231662-86eb0800-b3f9-11ea-9a00-b1375dc0a379.png)

The above image highlights two issues. The graph cannot be read at all, since the legend covers most of the card. Furthermore, the timestamps clip out of the card.

![IMG_3791](https://user-images.githubusercontent.com/14974112/85231663-894d6200-b3f9-11ea-9bcd-411e8762dc32.png)

The above image shows that it works as expected for the memory and CPU utilization by node graphs, leading me to think this might actually be a bug.

I haven't used Plotly before, but I suppose it's feasible to simply move the legend to the top or bottom of the graph if the screen becomes too small.

**Comment by nohaapav** [comment]
I guess we can hide legend on small devices .. user can tap the graph to see report at certain time. Plotly is supporting horizontal & vertical positioning however this is quite buggy (especially horizontal) .. I do not think any user will investigate graph data on mobile device, support is there mainly to quickly check what's happening in cluster & quick actions.

<img width="381" alt="Screen Shot 2020-06-26 at 3 55 43 PM" src="https://user-images.githubusercontent.com/4179104/85865291-f67c4100-b7c5-11ea-8e26-f3416626736b.png">

This is iphone X without legend. I guess pretty readable.

**Comment by AlexGustafsson** [comment]
Would it be hard to move the legend to under the graph?

**Comment by nohaapav** [comment]
If i do that legend is overriding part of x axis and act strange when redrawing (appears on the top and so on) .. only way i see this make to work will be custom legend outside of svg drawn by plotly and it's not worth the effort.

**Comment by AlexGustafsson** [comment]
I see, I suppose that’s fine for the time being

**Comment by nohaapav** [comment]
if device w < 600 (mobile) = Hidden legend & smaller L&R margins.
