### ISSUE TITLE
Unable to use more than 2.0 CPU

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#531]
Hi ,

  In the swarmpit UI max cpu limit is given as 2.0 , is there a way to make it 4.0.

**Comment by azrikahar** [comment]
Will it be too naive if we just change the max value from 2 to 4 in this line? https://github.com/swarmpit/swarmpit/blob/master/src/cljs/swarmpit/component/service/form_resources.cljs#L64

~~Or do we need to check the available CPU cores on the host?~~ On second thought, I'm not sure if this check is feasible in swarm. Silly me was thinking about a single host here 🤦‍♂️

**Comment by nohaapav** [comment]
@azrikahar There can be multiple strategies:

1) use minimal value across cluster
2) use minimal value across worker nodes

Or maybe just hardcode the value to 4 .. Docker will eventually fail (not sure) or just behave like undefined

**Comment by azrikahar** [comment]
> * use minimal value across cluster
> * use minimal value across worker nodes

These strategies are very sound indeed. Do we just use the `/api/nodes` API and filter them? Sample truncated payload:

```
[
  {
    ...
    "role": "worker",
    "leader": null,
    "nodeName": "node2",
    "resources": {
      "cpu": 8,
      ...
    },
    ...
  },
  {
    ...
    "role": "manager",
    "leader": true,
    "nodeName": "node1",
    "resources": {
      "cpu": 8,
      ...
    },
    ...
  }
]
```

Or perhaps there is a better direct approach that is what the API uses under the hood?

> Or maybe just hardcode the value to 4 .. Docker will eventually fail (not sure) or just behave like undefined

Yea this is true as well. Did a quick search (never faced requirement this before) about with people stating this exact behavior by Docker. I also did a quick test just to be sure, here's a sample output:

```
$ nproc
2
$ docker run -d --cpus 4 nginx
docker: Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available.
See 'docker run --help'.
```

Hope that helps to verify the default behavior by Docker for you :)

**Comment by nohaapav** [comment]
I do not really think there is a need to set more than 4CPUs per task in swarm. So the easiest way will be to change hardcoded value from 2 to 4 and let engine handle validation check.

**Comment by vermachandra** [comment]
Hi,

Thanks for your reply, where can we change the hard-coded value
