### ISSUE TITLE
unable to set ulimits in service configuraiton

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#534]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Setting up ulimits in service configuration

**Comment by nohaapav** [comment]
ulimit is container specific not service specific as far as i know

**Comment by vermachandra** [comment]
As of now i cant find ulimit configuration option while configuring a container through swarm pit, is there any way to do it ? please suggest if any,

**Comment by nohaapav** [comment]
Swarmpit is not supporting most of the container API. See ROADMAP overview:
https://github.com/swarmpit/swarmpit/blob/master/ROADMAP.md#overview
Unless there is support in docker service api to set ulimit you can't.

**Comment by vermachandra** [comment]
Hi Pavol,

i could see ulimit support on docker API, please have a look.

https://docs.docker.com/engine/api/v1.24/

Thanks.

**Comment by nohaapav** [comment]
This is **container** API not service API ... 
See https://docs.docker.com/engine/api/v1.40/#operation/ServiceCreate
`TaskTemplate  ->  ContainerSpec` section

**Comment by vermachandra** [comment]
Thank you..
