### ISSUE TITLE
Server / Docker crash causes Swarmpit to reset and allows creation of admin account through the web interface.

### ISSUE THREAD

**Issue by AfaanBilal** [swarmpit/swarmpit#538]
Hello,

Thank you for this amazing tool!

I've been testing out Swarmpit for a few days and while load testing my stack, every time my server / docker daemon crashed due to heavy load, Swarmpit resets and asks to create a new admin account through the web interface (as if it were starting the first time). This could be a huge security issue if a cluster were the target of a DDoS attack which crashes the server / docker daemon and then on reboot, allows the attacker to create a new admin account and access all kinds of sensitive data such as those stored in environment variables which are easily accessible through the Swarmpit UI.

**Steps to reproduce the issue:**
1. Install Swarmpit (tested with the lastest version: 1.9)
2. Apply heavy load (enough to crash the server / docker daemon)
3. Restart the server / docker daemon
4. Open Swarmpit interface in the browser
5. It prompts to create a new admin account - setup an admin username / password

And you're in.

**What happens:**
Swarmpit resets and allows anyone to create the admin account.

**What should happen:**
Swarmpit should preserve the initially created admin account even on server / docker daemon crash.

**Additional information:**
Docker CE 19.03 on Ubuntu 20.04
Cluster is composed of a replicated web app with Redis as cache.

**Comment by nohaapav** [comment]
@AfaanBilal Hi, are you sure that after restoring the cluster `swarmpit_db` (couch) is running on same node as before crash ? This looks like it was spawned on different node and because of that volume was not found (unless shared) and swarmpit_db created brand new empty db schema.

**Comment by AfaanBilal** [comment]
@nohaapav Hi, thanks for the quick reply!

 I'm not sure if the `swarmpit_db` was loaded on the same node. Is there any way I can make sure that the `swarmpit_db` loads on the same node as before without resorting to a compose file-based swarmpit installation? (I currently use the installation command directly).

**Comment by AfaanBilal** [comment]
@nohaapav I just checked and the `db` did indeed load on a different node after the crash. That seems to be the cause of the reset. I think there should be a way to make sure that the `db` loads on the same node or you could have an option to specify a default username / password to use (in the compose file or via secrets) in such a case.

**Comment by nohaapav** [comment]
@AfaanBilal Well if you are using `local` volume driver which is used by default you should set constraint placement after initial load on that particular node for `swarmpit_db` container. That way container will be searching for existing volume instead of creating new one.

Or you can specify shared volume driver of your choice see:
https://github.com/swarmpit/installer#optional
In that case no matter the node volume is distributed.

**Comment by AfaanBilal** [comment]
@nohaapav Yeah, I think placement constraints should do the job. Thanks!

**Comment by lumir-mrkva** [comment]
@AfaanBilal yeah, but good observation, we should at least introduce some env variable that would prevent the admin setup password screen when the swarmpit was installed already

**Comment by nohaapav** [comment]
To me this is configuration issue. With constraint in case of local volume such incident should not happen. We suggest to use shared volume driver for DB for the best experience thought.
