### ISSUE TITLE
Misleading claims

### ISSUE THREAD

**Issue by alexellis** [swarmpit/swarmpit#54]
This project describes itself as "Lightweight Docker Swarm orchestration" but in fact it's not an orchestration offering at all - it's just a UI. It is a clean UI which looks very useful but it's not orchestration - Docker Swarm and Kubernetes are examples of orchestration platforms.

I'd suggest you update the tagline to: "Lightweight Docker Swarm UI" or "Lightweight UI for Docker Swarm"

Does that make sense?

**Comment by nohaapav** [comment]
@alexellis you're right Alex. We're in rush with product page so there might be some misleading data still. If you check project description you can see "Docker swarm management UI" as a title. We'll update the claims ASAP. Thank you for your feedback.

**Comment by alexellis** [comment]
This is an improvement.

Do you support stacks for the "public services" tab I saw in your intro GIF? It would be good to see [Serverless FaaS for Docker](https://github.com/alexellis/faas) deployed with Swarmpit.

**Comment by nohaapav** [comment]
@alexellis Well not yet. We’ll try to cover most of swarm API in version 1.0 which should be out till the end of month i guess. And probably some extras as well (autoredeploy, user management, ...) In next release we’re planning to introduce application stacks for sure and also thinking about serverless support, so we can collaborate on this one. I've created new issue so lets discuss this possibility there.

https://github.com/swarmpit/swarmpit/issues/57
