### ISSUE TITLE
Swarmpit GUI :  non responsive

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#541]
I have observed that , after working for 1-2 days the GUI is not accessible and every time i need to restart swarmpit stack.

not able to find any logs also through docker logs command.

can you please suggest further .

**Comment by nohaapav** [comment]
Hard to say without any details. Probably matter of your setup. Really strange that you don't get any logs.

**Comment by vermachandra** [comment]
Hi , 

you can please close this issue ,  java heap issue was the root cause , we have increased the memory setting in swarmpit.yml file.
