### ISSUE TITLE
How to reset Admin Password?

### ISSUE THREAD

**Issue by synthomat** [swarmpit/swarmpit#543]
Hey,

Unfortunately I have forgotten my admin password and I have no idea how to reset it. Have I missed documentation for that procedure? I guess I have to set a new password directly in CouchDB (maybe using some hashing?)

Any help would be very appreciated. Thanks!

**Comment by nohaapav** [comment]
@synthomat Hi, i guess easiest way is to drop couch volume and let swarmpit recreate one. That way you lose all related data (linked registries/users/...).

If you wish to prompt new admin creation you can drop admin user document from couch. But result is going to be pretty much the same as related registries/dashboards won't be linked with such user unless you manually relink them.

Or you can change password in admin user doc as you suggested. We're using `pbkdf2+sha512` with `200000` iterations see:
https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/config.clj#L13

**Comment by synthomat** [comment]
@nohaapav hey, thanks for the explanation and pointing me to the right place in the code!
I've built a one-liner with `buddy-hashers` to generate a new password and updated the user document inside CouchDB.

Is there a feature request for Password Resets yet? I guess it would require storing the email address of the user and setting up a mailer? 🤨

**Comment by nohaapav** [comment]
@synthomat Not yet, please raise one. We plan to integrate google & github sso so in these cases reset is going to be email friendly and i guess default swarmpit user mngmnt should work the same.
