### ISSUE TITLE
docker one of the service getting killed.

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#545]
i am not really sure whether its because of swarmipt , though i noticed the application works fine though docker-compose but when running though swarmpit  applications stops exactly at 10 min with below error in systemlog.

"2020-07-28T14:50:43.231085479+05:45" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

please close if not related with swarmpit.

**Comment by vermachandra** [comment]
complete error
ul 28 14:50:43 prbt_mc2srv containerd: time="2020-07-28T14:50:43.221432574+05:45" level=info msg="shim reaped" id=a89d81cc537922e00644d8fdc5108c6ddc597eb4550adf7f3bf5ddde5a953892
Jul 28 14:50:43 prbt_mc2srv dockerd: time="2020-07-28T14:50:43.231085479+05:45" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

**Comment by nohaapav** [comment]
Probably not related to swarmpit. However if not sure just inspect service deployed via swarmpit & compose to see the difference.
