### ISSUE TITLE
Error: Stack deployment failed. Error: Cannot perform an interactive login from a non TTY device

### ISSUE THREAD

**Issue by waynehaffenden** [swarmpit/swarmpit#548]
**Description**
When trying to add a new stack through the web UI I receive the error "Stack deployment failed. Error: Cannot perform an interactive login from a non TTY device"

**Steps to reproduce the issue:**
1. Click create stack
2. Paste config
3. Click deploy and receive error "Stack deployment failed. Error: Cannot perform an interactive login from a non TTY device"
4. Nothing else happens.

**What happens:**
Nothing

**What should happen:**
Stack should deploy!

**Additional information (e.g. docker version, cluster setup,...):**
If I copy the config to the server and do a manual stack deploy it works as expected. Running latest version of swarmpit and docker. Debian 10.

**Comment by nohaapav** [comment]
@waynehaffenden Did you link your registry prior to stack deployment in Swarmpit ?

**Comment by waynehaffenden** [comment]
@nohaapav Thank you for the quick reply. I had just added a private docker v2 registry just before doing so, would this be the cause?

**Comment by waynehaffenden** [comment]
@nohaapav Interestingly, as soon as I remove the linked repository it works? I would have expected the opposite result!?

**Comment by waynehaffenden** [comment]
@nohaapav Sorry, also, any ideas why when using a Github Package/Repository (docker.pkg.github.com) the autodeploy feature doesn't work!? (Sorry this should be a separate issue)

**Comment by nohaapav** [comment]
I guess there is something wrong with your v2 registry setup. If you're using **Github** as v2 registry then this won't work as we don't support github yet.

**Comment by waynehaffenden** [comment]
@nohaapav I've managed to solve this issue by adding authentication to my registry and re-adding it to Swarmpit linked registries. Interestingly, a registry running without authentication added as a linked Swarmpit registry, will receive this error and will fail: "Stack deployment failed. Error: Cannot perform an interactive login from a non TTY device" and any existing images added manually won't auto-redeploy. So not sure whether this is an actual issue without authentication.
