### ISSUE TITLE
Can't connect to Docker Hub for autoredeploy

### ISSUE THREAD

**Issue by andresmoschini** [swarmpit/swarmpit#556]
**Description**

I was getting this error in the log after activating autoredeploy in services based on private images:

```
ERROR [swarmpit.agent:27](15) - Service f0rcnyxjnw64ejgy2ozrurkql (doppler-swarm-int_doppler-forms) autoredeploy failed! {:status 401, :type :http-client, :headers {"Content-Type" "application/json", "Docker-Distribution-Api-Version" "registry/2.0", "Www-Authenticate" "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:fromdoppler/doppler-forms:pull\",error=\"insufficient_scope\"", "Date" "Tue, 15 Sep 2020 23:28:17 GMT", "Content-Length" "168", "Connection" "close", "Strict-Transport-Security" "max-age=31536000"}, :body {:error nil}}
      "Www-Authenticate" : "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:fromdoppler/doppler-forms:pull\",error=\"insufficient_scope\"",
```

**Steps to reproduce the issue:**
1. Deploy a stack-based in a private Docker Hub image, with the label `swarmpit.service.deployment.autoredeploy=true`
2. Run swarmpit.
3. Add Docker Hub credentials to swarmpit.

**What happens:**

* The service is not updated when the image is modified.
* The log has a lot of entries with the error mentioned before.

**What should happen:**

* It should autoredeploy the updated image.

**Additional information (e.g. docker version, cluster setup,...):**

It seems that the `namespaces` field in the DB document related to the registry entry has wrong values.

In my case, it had `dnoyareader` (the username), when it should have `fromdoppler` (the namespace):

<img width="936" alt="image" src="https://user-images.githubusercontent.com/1157864/93277558-81068800-f798-11ea-95c1-e60f23429f4c.png">

At least, I understand that because this is the filter used to find the credentials:

https://github.com/swarmpit/swarmpit/blob/6da5ab9dcd1a0aed51bda0225b4dd3d2c7c6a0f2/src/clj/swarmpit/api.clj#L699-L705

https://github.com/swarmpit/swarmpit/blob/6da5ab9dcd1a0aed51bda0225b4dd3d2c7c6a0f2/src/clj/swarmpit/api.clj#L553-L558

After I manually modified the namespace value, it started to work as expected.

**Comment by nohaapav** [comment]
@andresmoschini Well the namespaces are fetched via dockerhub api. Looks like your account is missing `fromdoppler` namespace for some reason.

E.g. this is my record: 

Default user namespace `nohaapav` plus 2 linked organization namespaces `swarmpit` & `topmonks`

```
{:role "User",
 :_id "c24195870380eb2afc879397210020b3",
 :namespaces ["nohaapav" "swarmpit" "topmonks"],
 :_rev "1-d0765d809333287d78c8f0452daf9517",
 :name "Pavol Noha",
 :username "nohaapav",
 :type "dockerhub",
 :location "",
 :company "",
 :owner "admin"}
```

**Comment by nohaapav** [comment]
Btw check this feed: 

https://github.com/swarmpit/swarmpit/issues/532

Maybe it's related to your issue.

**Comment by andresmoschini** [comment]
Thanks @nohaapav! #532 is the right issue: when I used the _user account_ the DB document was fine:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/1157864/93331668-06b92080-f7f7-11ea-9dd4-f051bf7b4386.png">

By the moment I will work around it using the _user account_. 

But there should be a way to fix it, in the Doppler UI it seems to be working fine:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1157864/93331748-29e3d000-f7f7-11ea-9dbe-488958b42651.png">

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1157864/93331764-2f411a80-f7f7-11ea-8bb3-2e0430571e1e.png">
