### ISSUE TITLE
swarmpit loses data  / goes to old data on server restart

### ISSUE THREAD

**Issue by shakeelosmani** [swarmpit/swarmpit#559]
**Description**

**Steps to reproduce the issue:**
1. Restart linux servers part of swarm cluster

**What happens:**
Data gets lost, couch db does not start.

**What should happen:**
It should recover like any other service

**Additional information (e.g. docker version, cluster setup,...):**
Docker version 19.03.8, build afacb8b7f0

![image](https://user-images.githubusercontent.com/9120484/94281587-ce16f680-ff1c-11ea-9014-58814868db0e.png)

**Comment by nohaapav** [comment]
Are you using shared volume type for couch container ? 

If local volume type is used are you sure that couch db container is spawned on the same node as before restart ? Looks like another node was picked and couch db can't find it's volume.

**Comment by shakeelosmani** [comment]
That must be it, great catch. It is most likely a local volume. Can you explain how to accomplish either shared volume and local sticky volume. I will pick one strategy. Is it possible to accomplish this through swarmpit UI, thanks.

**Comment by nohaapav** [comment]
@shakeelosmani Easiest way to fix it is to use placement constraint https://docs.docker.com/compose/compose-file/#placement with local volume. This can be done via UI.

For shared volume there are few options out there. For AWS/Azure you can use cloudstor, otherwise some NFS one e.g. GlusterFS.
