### ISSUE TITLE
Bug in service startup

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#571]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

![image](https://user-images.githubusercontent.com/45089946/100098276-d7243580-2e83-11eb-8ac8-b59ad9d49bdb.png)
when service is run through swarmpit , another service with status as "complete" is started automatically.

**What happens:**
there is a continuous error response from docker daemon
![image](https://user-images.githubusercontent.com/45089946/100098430-0a66c480-2e84-11eb-8186-8466db748591.png)

Not able to figure out the root cause of it , is it due to swarmpit agent? please help to fix.

**Comment by nohaapav** [comment]
This is due to wrong configuration of your service. Probably exec command and this is done by swarm not swarmpit.
