### ISSUE TITLE
Clustered CouchDB

### ISSUE THREAD

**Issue by nscarlson** [swarmpit/swarmpit#578]
I had the unfortunate experience of the CouchDB container moving to a different node that didn't have the existing data volume, after I restarted the Swarm manager's Docker Daemon.  Is there a recommended sequence of steps to upgrade the default, single-container DouchDB into a Clustered more resilient setup?

**Comment by nohaapav** [comment]
See manual installation section:

https://github.com/swarmpit/swarmpit#manual-installation

<img width="918" alt="Screen Shot 2021-01-22 at 10 46 14 AM" src="https://user-images.githubusercontent.com/4179104/105474895-12ce5680-5c9f-11eb-801a-d8988e3ce477.png">

We're not using clustered mode but shared volume driver. In that case couch can be running on whatever node without any issue. Clustered mode is good for HA but this is not the case. You can however if you like run couch in clustered mode, but be aware that every single instance is going to consume resources.

**Comment by nscarlson** [comment]
> We're not using clustered mode but shared volume driver. In that case couch can be running on whatever node without any issue. Clustered mode is good for HA but this is not the case. You can however if you like run couch in clustered mode, but be aware that every single instance is going to consume resources.

What do you mean "we're using a shared volume driver"?  In Docker swarm it's `local` by default.  I'm using `local`.

Also your manual installation section mentions nothing about how to upgrade a single-container CouchDB into a clustered setup, which is what I asked.

**Comment by nohaapav** [comment]
@nscarlson Yes by default `local` volume driver is used, but volume using such driver is not shared between nodes. You should check for different drivers like `glusterFS` `rex-ray` `pxd` ... just to name a few. That way your volume is shared across cluster so you don't have to care about placements or couch clustering.
