### ISSUE TITLE
Help with API please

### ISSUE THREAD

**Issue by kklepper** [swarmpit/swarmpit#579]
looking at `http:/xxxx.yy:888/api-docs/index.html#!/statistics/get_api_stats` I see

_authorization (required)_

`Try it out`

Now where do I get that authorization?

`see more at https://swarmpit.io/` does not help

![image](https://user-images.githubusercontent.com/6130319/105610530-51076b00-5db0-11eb-919e-ffa7b990607c.png)

**Comment by nohaapav** [comment]
Click user and see settings section:
<img width="249" alt="Screen Shot 2021-01-24 at 10 50 42 AM" src="https://user-images.githubusercontent.com/4179104/105626741-0e867280-5e32-11eb-8591-451c253f17a8.png">

You can generate token under API Access section
<img width="601" alt="Screen Shot 2021-01-24 at 10 50 30 AM" src="https://user-images.githubusercontent.com/4179104/105626748-24943300-5e32-11eb-9667-48f68410f260.png">

**Comment by kklepper** [comment]
Thank you! Perfect.
