### ISSUE TITLE
Feature request: Registry linking automatization

### ISSUE THREAD

**Issue by SvyatoslavFedynyak** [swarmpit/swarmpit#581]
Hi,
I'm looking for a way to configure registry linking programmatically (through API, by setting envs, etc.).
Unfortunately I haven't found anything that can help me with it neither in API docs nor in ENV configuration.
Could you, please, describe possible solution or make such feature (if there is no such).
Thank you in advance!

**Comment by nohaapav** [comment]
Hi,

what is the use case of such feature ? 

Anyway there is also API available for that see (just no swagger):
https://github.com/swarmpit/swarmpit/blob/master/src/cljc/swarmpit/routes.cljc#L457

E.g.:
*Gitlab* POST `/api/registry/gitlab`
```
{
    "gitlabUrl": "https://gitlab.com",
    "hosted": false,
    "public": false,
    "token": "token_value",
    "url": "https://registry.gitlab.com",
    "username": "username"
}
```

*Amazon Container Registry* POST `/api/registry/acr`
```
{
    "name": "myacr",
    "public": false,
    "spId": "0123456789",
    "spName": "swarmpit-acr",
    "spPassword": "pass"
}
```

and so on .. you can open inspect to see how the rest of types is linked...

**Comment by SvyatoslavFedynyak** [comment]
Hi Pavol,
Yeah, thank you for help, it works.
We're trying to make fully automatized Swarmpit service deploy, and setting up registry link is part of it.
But I discovered that in order to make any API call we need user API token first. Which, looks like, can only be get through UI dashboard.
Maybe, you could point me into some other way to get this token or generate it programmatically?

**Comment by nohaapav** [comment]
@SvyatoslavFedynyak sure ..Basically everything can be done via API.

*Create token* **POST** `/api-token`

```
{"token":"Bearer ABCDEFGH"}
```
Make sure you store the value, it can't be fetched additionally via another api call.

*Remove token* **DELETE** `/api-token`

**Comment by nohaapav** [comment]
You just have to be logged in order to call these apis.. So you need your user token.

**Comment by sprnza** [comment]
As soon as we don't have ability to set user on deployment we won't be able use API. I think what OP is asking for is a way to pass parameters during depoloyment so a registry is being registered before user is being added.

**Comment by nohaapav** [comment]
@sprnza Actually registry is attached to swarmpit user so you need a user in order to link registry. And only this particular user can then create/update service or stack via swarmpit because of registry access to given image unless registry is linked as public.

**Comment by sprnza** [comment]
ah, okay. Thank you!
