### ISSUE TITLE
:latest not actually latest

### ISSUE THREAD

**Issue by mcknight89** [swarmpit/swarmpit#587]
Hey,

So just wanted to recommend you update the git repo instructions to detail which version is the latest or better yet start using the latest docker tag, Many people me included will use tutorials like https://dockerswarm.rocks/swarmpit/ to get started but you end up with a fairly old version of swarmpit. 

I don't recommend people using the latest as you always want to check new versions, However, I expect it to be the most updated like in git i'd expect master to be the stable branch.

Anything I think would really help people trying to use this awesome software.

**Comment by nohaapav** [comment]
Latest is always latest(current master branch a.k.a. EDGE release). If not something is wrong on your side.

**Comment by nohaapav** [comment]
I've just switched to latest see:

<img width="1892" alt="Screen Shot 2021-03-18 at 4 42 37 PM" src="https://user-images.githubusercontent.com/4179104/111654386-00891880-8809-11eb-91a5-7f0e2376009a.png">

Version in left upper corner is `v1.10-38ffbe0` and actual master commit is [38ffbe08e717d8620bf433c99f2e85a9e5984c32](https://github.com/swarmpit/swarmpit/commit/38ffbe08e717d8620bf433c99f2e85a9e5984c32)
