### ISSUE TITLE
Swarmpit install on docker standalone and subscribe multiple docker swarm

### ISSUE THREAD

**Issue by SiOuz** [swarmpit/swarmpit#590]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Swarmpit will be install on docker standalone and can subscribe to multiple swarm with swarmpit agent.

Why ? dont have to install influxdb,couchdb and swarmpit:latest on server production in order to save memory and cpu.

**Comment by lumir-mrkva** [comment]
duplicate with #478
