### ISSUE TITLE
User stack Permission

### ISSUE THREAD

**Issue by thiagocpv** [swarmpit/swarmpit#593]
Hi,

Is there a way to just the user see the own stack or service?
When login with user role, the user has the same role than admin has.

Swarmpit version: 1.10-38ffbe0

Thanks.

Thiago

**Comment by nohaapav** [comment]
No this is not possible yet.

Currently only difference is that admin can create users, user not.

**Comment by thiagocpv** [comment]
Ok, thanks for the information.
I will waiting for this feature to start the use.

**Comment by nohaapav** [comment]
Duplicate of https://github.com/swarmpit/swarmpit/issues/94

**Comment by thiagocpv** [comment]
@NeilInnes wow! I will do the tests soon.
Thx for the awesome work.
