### ISSUE TITLE
Add label to service not work

### ISSUE THREAD

**Issue by duskohu** [swarmpit/swarmpit#596]
I am trying add label to service:
open service > Edit service > Deployment > Add label for example `test:test`
and run deploy.
in swarmpit is label, but when I check container: `docker inspect [container-id]` I dont have my label in label list.

swarmpit: v1.9
docker: 
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by nohaapav** [comment]
because it is service label not container label
