### ISSUE TITLE
Volumes not detected on worker nodes

### ISSUE THREAD

**Issue by chrismueller** [swarmpit/swarmpit#597]
Volumes not detected on worker nodes

I was running a two node swarm cluster on Raspberry Pi 4B+ (8GB) / Ubuntu Server 20.04 LTS 64bit (arm64)

After deploying stacks on the cluster swarmpit recognizes all volumes on the master node (on which swarmpit is also running on). The volumes on the other node are not recognized (Equal if I'm using local volumes or shared ones)

Also when I then try to edit the stack with swarmpit the volume section in the yaml is empty. 

Afterwards I tried this also in amd64 virtual machines to see if this is a arm related issue. There I also have the same problems.
Maybe there is an issue with the agent containers... but I have no idea how to troubleshoot this.

**Comment by paulknulst** [comment]
this problem does also happen in an prod environment. within my swarm local volumes create on a worker node are not show in swarmpit-ui.

but if i add the name manually within the ui they are connected to the correct service. 

got idea from: https://github.com/swarmpit/swarmpit/issues/261

**Comment by lumir-mrkva** [comment]
duplicate with #261
