### ISSUE TITLE
ap-east-1 needs adding to ECR Repositories

### ISSUE THREAD

**Issue by ktechmidas** [swarmpit/swarmpit#601]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
-->

**Description**

**Steps to reproduce the issue:**
1. Go to the web UI
2. Go to Registries and add new Amazon ECR repo

**What happens:**
ap-east-1 (Hong Kong) is not in the list

**What should happen:**
ap-east-1 should be showing in here as it supports ECR

**Additional information (e.g. docker version, cluster setup,...):**
latest

**Comment by ktechmidas** [comment]
I'll put a PR in when I have the time, but it may not be for a little while... maybe someone knows where to change this :)

**Comment by ktechmidas** [comment]
Submitted a quick fix: https://github.com/swarmpit/swarmpit/pull/602

**Comment by nohaapav** [comment]
@ktechmidas pr merged
