### ISSUE TITLE
Comments get removed from Stack | Parts of the configuration gets alphabetically sorted

### ISSUE THREAD

**Issue by racoon-one** [swarmpit/swarmpit#604]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

As soon a Stack gets deployed the comments get removed and parts of the configuration gets sorted alphabetically.

**Steps to reproduce the issue:**
1. Create a new Stack with a Container configuration
2. Add Comments to Configuration
3. Deploy Stack

**What happens:**
All comments (#) get removed.
The lines in the configuration file get alphabetically sorted.

**What should happen:**
Comments should remain.
Lines should not get sorted alphabetically to have structure.

**Additional information (e.g. docker version, cluster setup,...):**
1 Node
Swarm Mode enabled
Swarm Version: v1.9
Docker Version: 20.10.2

**Comment by nohaapav** [comment]
> The lines in the configuration file get alphabetically sorted.

This one is done on purpose as feature.

**Comment by FOSY-The-Racoon** [comment]
is there a way to disable automatic sorting and auto removing comments?

**Comment by FOSY-The-Racoon** [comment]
> > The lines in the configuration file get alphabetically sorted.
> 
> This one is done on purpose as feature.

is there a way to disable automatic sorting and auto removing comments?

**Comment by lumir-mrkva** [comment]
@FOSY-The-Racoon the compose file is automatically generated always from the current state so there is no way to recover comments or order of items
