### ISSUE TITLE
Swarmpit api healtcheck endpoint

### ISSUE THREAD

**Issue by e-tip** [swarmpit/swarmpit#612]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

i've deployed swarmpit in a docker swarm cluster where we run our sandbox environment. Unfortunately, sometimes swarmpit stops and i have to restart the stack in order to make it work again ( seems that my 8GB server runs out of memory ). It would be nice to have a swarmpit endpoint to call in order to have a way to know it the server is alive or not

**Comment by nohaapav** [comment]
you can call version endpoint like a workaround :)

**Comment by e-tip** [comment]
Seems Good! thanks
