### ISSUE TITLE
Is this project DEAD?.

### ISSUE THREAD

**Issue by eramosr16** [swarmpit/swarmpit#618]
Last release was more than a year ago.

**Comment by nohaapav** [comment]
We do not actively develop Swarmpit right now, as swarm is more or less done without further development in progress.

**Comment by nohaapav** [comment]
I don't :) @dhpowrhost .. Docker Swarm has all it's major features in place already. It's simple, stable, easy to learn and that's all we need. There is no goal to make it second k8s which is great. We still use it and will in future as well and Swarmpit is covering all our needs and most of our customer needs right now.

@rarous summarized the status on twitter recently:
https://twitter.com/alesroubicek/status/1431485234596524037

**Comment by eramosr16** [comment]
I agree that it has all the features in place and it is indeed very stable, but still had bugs, I stopped from using it for example because had an issue with the cache that was causing the website to crash and all the services, I had to restart it every two days. At least the bug fixes would be something to take into account, if you don't have time or don't want to add features which I perfectly understand at least the bugs. 
I appreciate your responses and your time and congratulations to all the people that had worked here it is a great product indeed and make the live more easier to those who don't have time to get into k8s and need a solution to manage the services for testing and development.

**Comment by petersjostrom** [comment]
But there are still bugs that makes it less usable: #599

**Comment by lozhn** [comment]
To those who are not that familiar with Clojure world - there's beauty in making things complete and finished. This project is complete and that's wonderful!

**Comment by dhpowrhost** [comment]
We are switching to Hashicorp Nomad. Can't express how excited we are about Nomad. Really promising workload orchestrator.

**Comment by lumir-mrkva** [comment]
as @nohaapav said the app is pretty much complete and we're currently working on new release that will contain mostly just bug fixes, but we are welcoming any contribution to the project.
