### ISSUE TITLE
Feature Request: Remote management of docker swarms

### ISSUE THREAD

**Issue by ghost** [swarmpit/swarmpit#620]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Hi,

It would be great if swarmpit for monitor and deploy to remote swarms.

Example
A swarm with swarmit running to manage config and deployment  ( lets call it the management  stack)

A new swarm with  a deployed swarmpit agent/s within another swarm have the " management stack" connect to the swarm in question and be able to deploy and perhaps even shift between one or more swarms. Portainer has this feature and would be awesome if swarmpit would able to do this as well. 

I do prefer swarmpit look and feel to portainer, however it is lacking in some features that I would find very useful in a production environment

**Comment by lumir-mrkva** [comment]
duplicate with #478
