### ISSUE TITLE
container deployed outside of swarmpit that isn't using compose

### ISSUE THREAD

**Issue by lcslouis** [swarmpit/swarmpit#627]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

tasks created that are not swarm stacks are not visible 

**Steps to reproduce the issue:**
1. deploy non stacked task

**What happens:**

Not visible under tasks

**What should happen:**

should still be visible but with warning that container isn't a swarm service

**Additional information (e.g. docker version, cluster setup,...):**

1 node system.

**Comment by lumir-mrkva** [comment]
we only support management of containers that are deployed in docker swarm, that means either standalone service or complete stack. we dont support management of individual conteiners that are deployed locally on some swarm node. if you want to manage your contener deploy it as service.
