### ISSUE TITLE
Unable to create stack via TCP socket

### ISSUE THREAD

**Issue by lightningspirit** [swarmpit/swarmpit#633]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
**Unable to create stack when using docker socket via TCP**

Swarmpit is running on worker nodes and configured to connect to Docker socket via socat (api over TCP).
When trying to create a new stack it fails with given message:
```
Stack deploy failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Everything else works fine over the configured TCP.
It seems that in the stack creation operation it's ignoring the `:docker-sock` option which defaults to `/var/run/docker.sock`.

**Steps to reproduce the issue:**
1. Create a stack with `alpine/socat` and `swarmpit`
2. Configure `SWARMPIT_DOCKER_SOCK` to socat TCP endpoint
3. Try to create a new stack within swarmpit interface

**What happens:**
Unable to create a stack over TCP

**What should happen:**
It should be able to create the stack over TCP

**Additional information (e.g. docker version, cluster setup,...):**
Latest swarmpit version.
Docker 20.10

**Comment by lightningspirit** [comment]
Managed to successfully deploy new stacks by setting `DOCKER_HOST=tcp://socat:2375` to the swarmpit service.
This leads me to the question: Is it really useful to set both `SWARMPIT_DOCKER_SOCK` and `DOCKER_HOST` or would swarmpit suffice with just `DOCKER_HOST`?

**Comment by nohaapav** [comment]
https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/docker/engine/http.clj

Currently `SWARMPIT_DOCKER_SOCK` must be used in order to create socket factory succesfully.
