### ISSUE TITLE
Unsupported Content-Type header (text/plain; charset=UTF-8): must be 'application/json' when updating config

### ISSUE THREAD

**Issue by dutts** [swarmpit/swarmpit#653]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

We use the `/configs/create` endpoint to deploy new configs through teamcity. This has worked fine up to recently and then suddenly stopped working and is now complaining that the `Content-Type` header is not set properly. I can reproduce this through swagger.

**Steps to reproduce the issue:**
1. From the swagger page, https://<my_domain>/api-docs/index.html#!/config/post_api_configs.
2. Add a valid authorisation bearer token.
3. In the body, add:

```json
{
  "configName" : "testConfigName",
  "data" : "ewp9"
}
```

(this is just an empty json document, but any base 64 encoded json for `data` does the same thing)

**What happens:**

This creates an equivalent curl request to:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Bearer <my_token>' -d '{ \ 
   "configName" : "testConfigName", \ 
   "data" : "ewp9" \ 
 }' 'https://<my_domain>/api/configs'
 ```

Note the correct `Content-Type` header being set.

But instead we get

```json
{
  "error": "unsupported Content-Type header (text/plain; charset=UTF-8): must be 'application/json'"
}
```

The logs contain:

```
23-02-08 10:03:12 ERROR [swarmpit.http:71](15) - Request execution failed! Scope: Docker
|> POST http://localhost/v1.42/configs/create
|> Headers: null
|> Payload: {
  "Name" : "testConfigName",
  "Data" : "ewp9"
}
|< Message: clj-http: status 400
|< Data: {
  "headers" : {
    "Api-Version" : "1.42",
    "Content-Type" : "application/json",
    "Docker-Experimental" : "false",
    "Ostype" : "linux",
    "Server" : "Docker/23.0.0 (linux)",
    "Date" : "Wed, 08 Feb 2023 10:03:12 GMT",
    "Content-Length" : "102",
    "Connection" : "close"
  },
  "status" : 400,
  "body" : "{\"message\":\"unsupported Content-Type header (text/plain; charset=UTF-8): must be 'application/json'\"}\n",
  "reason-phrase" : "Bad Request",
  "type" : "clj-http.client/unexceptional-status"
}
```

Update:

I also get the same error when attempting to manually create a config through the UI.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/2182427/217509097-5bdeb4e0-0d8a-4a53-81a9-4e923f3366fe.png">

**What should happen:**

A config should be added to swarm pit with HTTP 200 and the id of the created config as response.

**Additional information (e.g. docker version, cluster setup,...):**

Doing the same thing using the secret endpoint in swagger works as expected.

Docker 23.0.0 (linux)
Swarmpit v1.10-37edab1

**Comment by RoodeyMental** [comment]
It might have something to do with the Docker Version. I am also using version 23.0.0 where i am experiencing the same issue. I just installed swarmpit on a test swarm using Docker 20.10.22, where the creation of the configuration works.

**Comment by dutts** [comment]
I wonder if swarmpit is doing something dodgy here that's being caught out by the latest docker release. I just tried to create a config directly through the docker socket, hoping to get a similar error but unfortunately (for swarmpit) it works.
```
sudo curl --unix-socket /var/run/docker.sock http://localhost/v1.42/configs/create -d '{ "Name": "foofoo","Data": "abcd"}' -H 'Content-Type:application/json'
{"ID":"u1xwoukxx0t4b25v22lcpqnvh"}
```

**Comment by rarous** [comment]
It seems that `swarmpit.http` doesn't send `Content-Type` header at all. Looks like it was not required in older versions of Docker.

**Comment by dutts** [comment]
> It seems that `swarmpit.http` doesn't send `Content-Type` header at all. Looks like it was not required in older versions of Docker.

Is this going to be an easy fix? We rely on this feature quite heavily yet aren't too keen on downgrading Docker. FWIW the secrets functionality through Swarmpit appears to still work so does that already send a `Content-type` header or is docker being inconsistent here?

I'm happy to take a look and raise a PR if you can point me in the right direction.

**Comment by Excalibrus** [comment]
Is there any update on this bug resolution?

**Comment by dutts** [comment]
@rarous is there any plan to fix this in the near future?

**Comment by viniciusingracio** [comment]
Hey guys! We have the same problem here! Do we have any updates?

**Comment by Schrammel** [comment]
i fixed it... 

ping @rarous @nohaapav

**Comment by rarous** [comment]
Merged into master. Thank you.

**Comment by Schrammel** [comment]
is there a release date?

**Comment by rarous** [comment]
I don't have admin rights to do one. It's up to @nohaapav or @mrq1911 .

**Comment by dutts** [comment]
Any update on this? Really could do with a new build, the docker image hasn't been updated in 2 years, we have a critical service affecting bug fix now in master but no release.

**Comment by elgerm** [comment]
search for swarmpit in the docker hub, there are others that built a fork and deployed it. It works, not the safest option though.

**Comment by elgerm** [comment]
Hi @nohaapav, with the new-ci configs can be saved again and I've tested deploying some new stacks and updated existing ones. Seems to work fine.

**Comment by dutts** [comment]
> Can you try with `swarmpit/swarmpit:new-ci` tag ? If all is fine i can release new latest ..

Looks good here too, thanks.

**Comment by nohaapav** [comment]
Good, latest already out in dockerhub ..
