### ISSUE TITLE
Swarmpit breaking down with current Docker versions: 500 errors, missing logs, exceptions in logs

### ISSUE THREAD

**Issue by Radiergummi** [swarmpit/swarmpit#656]
**Description**  
I know you have stated before that Swarmpit is "finished" in a way, because it works and is feature-complete. This doesn't hold anymore. With newer Docker versions, there are uncaught exceptions in the logs, random restarts, and usability issues (like task logs not being fetched). All of this probably relates to incompatibilities with newer Docker versions - the last Swarmpit release has been almost three years ago.

Is there any maintainer left interested in keeping this project alive? Otherwise, I'd ask you to put the repository into archive mode, so the community will know about the status and can search for alternatives accordingly.

Swarmpit is a neat piece of software, and we use it extensively to monitor our clusters. Sadly though, it started to become a hassle recently, and I'd very much love to see this project come back to live.

**Comment by nohaapav** [comment]
Hi @Radiergummi Let me check what docker we're using. If just outdated builds are the issue i can rebuild new images to support last docker LTE's etc ..

**Comment by batuhanfaik** [comment]
@nohaapav Do you have any updates on the build? I can also confirm that I am getting 500 errors constantly with the following version

```bash
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 OS/Arch:           linux/amd64

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42
 OS/Arch:           linux/amd64
```

**Comment by nohaapav** [comment]
We have to rebuild deployment pipeline .. @mrq1911 was on that so checking the status with him rn ..

**Comment by dutts** [comment]
Any update on this? Really could do with a new build, the docker image hasn't been updated in 2 years, we have a critical service affecting bug fix now in master but no release.

**Comment by nohaapav** [comment]
@dutts Can you try with `swarmpit/swarmpit:new-ci` tag ? If all is fine i can release new latest ..

**Comment by bluepuma77** [comment]
@nohaapav For the project it would look good if all required containers (swarmpit, agent, install) would get an update. Looking at Docker Hub the others are 3 years old, and in that time even the decencies probably got some bug fixes.
