### ISSUE TITLE
Is this Project still being active?

### ISSUE THREAD

**Issue by tbaror** [swarmpit/swarmpit#679]
Hello , 
I am looking into swarm cluster management, and i stumble on this nice project, but i can see that last release is 2020
So i wonder is there future release or its abandoned project that do not maintained anymore?
Thank you

**Comment by nohaapav** [comment]
Hi @tbaror , we still using swarmpit to manage our clusters yet there is no active dev anymore. Just required minimum in order to support docker upgrades etc .. 

PR's are welcome :)

**Comment by tbaror** [comment]
Thanks
