### ISSUE TITLE
ISSUE: Image and tag display abnormally at service edit page

### ISSUE THREAD

**Issue by jack6liu** [swarmpit/swarmpit#73]
The image and tag when using local registry will display abnormally at service edit page, while it will display well at service overview page. please check the below screenshots.

**service edit**
![20170720-103728](https://user-images.githubusercontent.com/8843389/28398281-0ef9e69a-6d39-11e7-93ee-cca2af1a236f.jpg)

**service overview**
![20170720-103710](https://user-images.githubusercontent.com/8843389/28398286-1257ee0e-6d39-11e7-8a3a-61126e2ca651.jpg)

**Comment by nohaapav** [comment]
I guess overview is ok. It uses same approach as default docker client that means if there is custom registry, image is prefixed with registry url .. But service edit is broken for sure if there is registry with port defined.

Maybe we can instead of using docker client prefixing way show which registry was image pulled.

**Comment by jack6liu** [comment]
I paste 2 kind of image from docker hub and local registry here, not sure if there is any situation that there is no 'tag' of some images.

**service inspect with local registry**
```json
{
        ...
        "TaskTemplate": {
            "ContainerSpec": {
                "DNSConfig": {},
                "Image": "192.168.200.8:5000/emilevauge/whoami:latest@sha256:5c0e00928e61abbe041b46ef35cfca5c91d8f1cdc1bae89458593548d7bd723b"
        ...
    "Spec": {
        ...
        "TaskTemplate": {
            "ContainerSpec": {
                "DNSConfig": {},
                "Image": "192.168.200.8:5000/emilevauge/whoami:latest@sha256:5c0e00928e61abbe041b46ef35cfca5c91d8f1cdc1bae89458593548d7bd723b"
            },
        ...
}
```

**service inspect with docker hub**
```json
{
        ...
        "Name": "swarmpit_db",
        "TaskTemplate": {
            "ContainerSpec": {
                "Image": "klaemo/couchdb:2.0.0@sha256:719ef1692b6491829bd86b7225fef711e2c26cfd4f1e075575e947f91fce02f1",
        ...
}
```

So maybe the whole `Image` string can be processed by `@` and last or second `:`

**Comment by nohaapav** [comment]
There should be always tag :) Basically the problem here is that we didn't count with the fact that registry can have port so if image is splitted by `:` and there is port -> `5000/emilevauge/whoami ` section is returned instead of tag.  Will fix it asap

**Comment by nohaapav** [comment]
@jack6liu Could you pull the latest version & check ? I've pushed the fix.

**Comment by jack6liu** [comment]
@nohaapav tested, working great !!

![image](https://user-images.githubusercontent.com/8843389/28415699-695fd83e-6d83-11e7-8765-eda2740d9b75.png)

**Comment by nohaapav** [comment]
Good. Closing the issue then.
