### ISSUE TITLE
ISSUE: unauthorized login should redirect to login page instead of show error 401

### ISSUE THREAD

**Issue by jack6liu** [swarmpit/swarmpit#77]
For the latest swarmpit version, if login session is expired, when re-open the non-login page, it will show http error 401 unauthorized, I think it better to redirect to login page.

**Error 401**, testing url is `http://host_name_or_ip/#/services`
![image](https://user-images.githubusercontent.com/8843389/28600868-6a7b8ebc-71e7-11e7-98f6-bf7dc289f096.png)

**Login page**, better to redirect to `http://host_name_or_ip/#/login`
![image](https://user-images.githubusercontent.com/8843389/28600883-80d97048-71e7-11e7-85ff-677ef335d062.png)

**Comment by nohaapav** [comment]
Well there is no session .. It's because swarmpit token expired. We can probably redirect user directly if token is expired instead of showing not authorized access(token invalid, insufficient rights). 

Anyway good point.
