### ISSUE TITLE
Q: Any plans to have Swarmpit agents?

### ISSUE THREAD

**Issue by gondor** [swarmpit/swarmpit#92]
I played with the UI and it looks great.  One thing lacking I have found in using Portainer is I have no way to view logs or exec in tasks within a service.  Are there any plans in this project to have optional agents to allow these capabilities?

**Comment by nohaapav** [comment]
In release 2.0 we will introduce service logs viewer for sure. Here is issue:
https://github.com/swarmpit/swarmpit/issues/20

Exec is not on list, but i agree it might be useful while debugging so we'll consider implementation as well.

**Comment by megastef** [comment]
@gondor Pls. check Sematext Docker Agent, it tags logs  with Swarm meta data like service name, task ID etc. you could use the agent with Elasticsearch or Sematext Cloud https://hub.docker.com/r/sematext/sematext-agent-docker/
