### ISSUE TITLE
Add DTR support 

### ISSUE THREAD

**Issue by nohaapav** [swarmpit/swarmpit#97]
Docker trusted registry is using token generated by docker auth instead of basic token.

**Comment by michaelwilde** [comment]
Let me know if you need a DTR to test against.

**Comment by nohaapav** [comment]
@michaelwilde That would be great. Otherwise i have to create UCP and DTR somewhere.

**Comment by nohaapav** [comment]
Closing in favour of 
https://github.com/swarmpit/swarmpit/issues/157
